# บทที่ 7: pandas Series และ DataFrame

ในบทก่อนหน้า เราได้เรียนรู้โครงสร้างข้อมูลพื้นฐานของ Python เช่น

- List
- Dictionary
- Condition
- Loop
- Function

โครงสร้างเหล่านี้ช่วยจัดเก็บและประมวลผลข้อมูลได้ดีในระดับพื้นฐาน แต่เมื่อข้อมูลมีหลายแถว หลายคอลัมน์ และต้องทำงานในลักษณะตาราง การใช้ List หรือ Dictionary เพียงอย่างเดียวจะเริ่มไม่สะดวก

ในบทนี้ เราจะเริ่มใช้ Library ชื่อ **pandas** ซึ่งมีโครงสร้างข้อมูลสำคัญ 2 ประเภท ได้แก่

1. **Series** — ข้อมูลหนึ่งมิติ คล้ายคอลัมน์หนึ่งคอลัมน์
2. **DataFrame** — ข้อมูลสองมิติ คล้ายตารางใน Excel

Series และ DataFrame เป็นพื้นฐานสำคัญสำหรับการนำเข้า ตรวจสอบ ทำความสะอาด แปลง และวิเคราะห์ข้อมูลในบทต่อไป

## ผลการเรียนรู้ที่คาดหวัง

เมื่อเรียนจบบทนี้ ผู้เรียนจะสามารถ

1. สร้างและอธิบายความแตกต่างระหว่าง Series และ DataFrame ได้
2. ตรวจสอบโครงสร้างพื้นฐานของ DataFrame ได้
3. เลือกคอลัมน์ แถว และกรองข้อมูลตามเงื่อนไขได้
4. สร้างคอลัมน์ใหม่จากการคำนวณ เงื่อนไข และ Function ได้

## ลำดับเนื้อหา

บทเรียนนี้ประกอบด้วยหัวข้อต่อไปนี้

1. เหตุผลที่ใช้ pandas
2. การนำเข้า pandas
3. การสร้าง Series
4. ความแตกต่างระหว่าง List และ Series
5. การสร้าง DataFrame
6. องค์ประกอบของ DataFrame
7. การตรวจสอบโครงสร้างเบื้องต้น
8. การเลือกคอลัมน์
9. การเลือกข้อมูลด้วย `.loc`
10. การเลือกข้อมูลด้วย `.iloc`
11. การกรองข้อมูลด้วยเงื่อนไข
12. การใช้หลายเงื่อนไข
13. การสร้างคอลัมน์ใหม่
14. การใช้ Function กับ DataFrame
15. การใช้ Loop กับ DataFrame อย่างเหมาะสม
16. ข้อผิดพลาดที่พบบ่อย
17. แบบฝึกหัดท้ายบท

## 1. เหตุผลที่ใช้ pandas

สมมติว่าเรามีข้อมูลผู้ตอบแบบสำรวจ 5 คน โดยแต่ละคนมีข้อมูลดังนี้

- รหัสผู้ตอบ
- พื้นที่
- อายุ
- คะแนนความต้องการความช่วยเหลือ
- สถานะแบบสำรวจ

หากใช้ List เราอาจต้องสร้าง List แยกสำหรับแต่ละข้อมูล

In [1]:
respondent_ids = [1, 2, 3, 4, 5]

areas = [
    "Bangkok",
    "Chiang Mai",
    "Bangkok",
    "Khon Kaen",
    "Songkhla",
]

ages = [34, 52, 41, 29, 63]

need_scores = [
    4.2,
    3.8,
    4.7,
    2.9,
    3.5,
]

statuses = [
    "Completed",
    "Completed",
    "Verified",
    "Draft",
    "Completed",
]

ข้อมูลแต่ละคนสัมพันธ์กันด้วยตำแหน่งเดียวกันในแต่ละ List

ตัวอย่างเช่น ข้อมูลของผู้ตอบคนแรกอยู่ที่ index `0` ของทุก List

In [2]:
print(respondent_ids[0])
print(areas[0])
print(ages[0])
print(need_scores[0])
print(statuses[0])

1
Bangkok
34
4.2
Completed

วิธีนี้มีข้อจำกัด ได้แก่

- ต้องรักษาลำดับของทุก List ให้ตรงกัน
- หากลบหรือเรียงข้อมูลผิดเพียง List เดียว ข้อมูลอาจคลาดเคลื่อน
- ไม่มีตารางที่แสดงความสัมพันธ์ของแถวและคอลัมน์อย่างชัดเจน
- การกรองและเลือกข้อมูลหลายเงื่อนไขทำได้ไม่สะดวก
- การตรวจสอบชนิดข้อมูลของแต่ละคอลัมน์ทำได้ยาก

pandas ช่วยจัดข้อมูลเหล่านี้ให้อยู่ในโครงสร้างตารางที่ชัดเจนและมีคำสั่งสำหรับงานข้อมูลโดยเฉพาะ

## 2. การนำเข้า pandas

ก่อนใช้ Series และ DataFrame ต้องนำเข้า Library `pandas`

โดยทั่วไปนิยมใช้ชื่อย่อว่า `pd`

In [3]:
import pandas as pd

คำสั่ง

```python
import pandas as pd
```

หมายถึง

- นำ Library `pandas` มาใช้งาน
- กำหนดชื่อย่อเป็น `pd`

ตัวอย่างคำสั่งที่ใช้ชื่อย่อนี้ ได้แก่

```python
pd.Series(...)
pd.DataFrame(...)
pd.read_csv(...)
pd.read_excel(...)
```

## 3. การสร้าง Series

**Series** คือโครงสร้างข้อมูลหนึ่งมิติของ pandas

สามารถมองว่า Series คล้าย

- คอลัมน์หนึ่งคอลัมน์ในตาราง
- List ที่มี index กำกับ
- ชุดค่าที่สามารถคำนวณพร้อมกันได้

เราสามารถสร้าง Series จาก List ด้วย `pd.Series()`

In [4]:
need_scores_list = [
    4.2,
    3.8,
    4.7,
    2.9,
    3.5,
]

need_scores_series = pd.Series(
    need_scores_list
)

need_scores_series

0    4.2
1    3.8
2    4.7
3    2.9
4    3.5
dtype: float64

Series ประกอบด้วยสองส่วนหลัก

- **index** อยู่ด้านซ้าย
- **value** อยู่ด้านขวา

หากไม่ได้กำหนด index เอง pandas จะสร้าง index เริ่มจาก `0` ให้อัตโนมัติ

In [5]:
type(need_scores_series)

pandas.Series

ผลลัพธ์คือ

```text
pandas.core.series.Series
```

แสดงว่าตัวแปรนี้เป็น pandas Series ไม่ใช่ List

### การกำหนดชื่อให้ Series

Series สามารถมีชื่อกำกับได้

In [6]:
need_scores_series = pd.Series(
    need_scores_list,
    name="need_score",
)

need_scores_series

0    4.2
1    3.8
2    4.7
3    2.9
4    3.5
Name: need_score, dtype: float64

ชื่อ `"need_score"` ช่วยอธิบายความหมายของข้อมูล และจะมีประโยชน์เมื่อนำ Series ไปใช้ร่วมกับ DataFrame

### การเข้าถึงข้อมูลใน Series

In [7]:
need_scores_series[0]

np.float64(4.2)

In [8]:
need_scores_series[0:3]

0    4.2
1    3.8
2    4.7
Name: need_score, dtype: float64

Series สามารถเข้าถึงข้อมูลด้วย index และ slicing คล้าย List

อย่างไรก็ตาม ใน pandas ควรใช้ `.loc` หรือ `.iloc` เมื่อการเลือกข้อมูลมีความซับซ้อน เพื่อให้ระบุได้ชัดเจนว่ากำลังเลือกด้วย label หรือตำแหน่ง

## 4. ความแตกต่างระหว่าง List และ Series

List และ Series เป็นข้อมูลหนึ่งมิติเหมือนกัน แต่ Series มีความสามารถที่เหมาะกับงานข้อมูลมากกว่า

| ประเด็น | List | Series |
|---|---|---|
| มีลำดับข้อมูล | มี | มี |
| มี index | ใช้ตำแหน่ง | มี index กำกับ |
| คำนวณทั้งชุดโดยตรง | ไม่ได้ตามปกติ | ได้ |
| เปรียบเทียบทั้งชุด | ต้องใช้ Loop | ได้ |
| มีชื่อกำกับ | ไม่มีโดยตรง | มีได้ |
| ใช้เป็นคอลัมน์ DataFrame | ต้องแปลงก่อน | ใช้ได้โดยตรง |

### การคำนวณกับ Series ทั้งชุด

หากต้องการเพิ่มคะแนนทุกค่าอีก `0.5` สามารถเขียนกับ Series ได้โดยตรง

In [9]:
need_scores_series + 0.5

0    4.7
1    4.3
2    5.2
3    3.4
4    4.0
Name: need_score, dtype: float64

หากใช้ List ต้องใช้ Loop หรือวิธีอื่นเพื่อคำนวณทีละค่า

In [10]:
adjusted_scores = []

for score in need_scores_list:
    adjusted_scores.append(score + 0.5)

adjusted_scores

[4.7, 4.3, 5.2, 3.4, 4.0]

### การเปรียบเทียบค่าทั้ง Series

In [11]:
need_scores_series >= 4.0

0     True
1    False
2     True
3    False
4    False
Name: need_score, dtype: bool

ผลลัพธ์คือ Series ของค่า Boolean

- `True` หมายถึงคะแนนถึงเกณฑ์
- `False` หมายถึงคะแนนไม่ถึงเกณฑ์

Boolean Series นี้สามารถนำไปกรองข้อมูลใน DataFrame ได้

## 5. การสร้าง DataFrame

**DataFrame** คือโครงสร้างข้อมูลสองมิติของ pandas

สามารถมองว่า DataFrame คล้ายกับ

- ตารางใน Excel
- Worksheet ที่มีหัวคอลัมน์
- ตารางฐานข้อมูล
- ชุดของ Series หลายชุดที่มี index ร่วมกัน

วิธีหนึ่งที่ใช้สร้าง DataFrame คือสร้างจาก Dictionary ที่แต่ละ value เป็น List

In [12]:
survey_data = {
    "respondent_id": [1, 2, 3, 4, 5],
    "area": [
        "Bangkok",
        "Chiang Mai",
        "Bangkok",
        "Khon Kaen",
        "Songkhla",
    ],
    "age": [34, 52, 41, 29, 63],
    "need_score": [
        4.2,
        3.8,
        4.7,
        2.9,
        3.5,
    ],
    "status": [
        "Completed",
        "Completed",
        "Verified",
        "Draft",
        "Completed",
    ],
}

In [13]:
df = pd.DataFrame(survey_data)

df

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
3              4   Khon Kaen   29         2.9      Draft
4              5    Songkhla   63         3.5  Completed

เมื่อสร้าง DataFrame จาก Dictionary

- key กลายเป็นชื่อคอลัมน์
- List ของแต่ละ key กลายเป็นข้อมูลในคอลัมน์
- สมาชิกตำแหน่งเดียวกันกลายเป็นข้อมูลในแถวเดียวกัน
- pandas สร้าง index ของแถวให้อัตโนมัติ

ข้อสำคัญคือ List ทุกชุดควรมีจำนวนสมาชิกเท่ากัน

## 6. องค์ประกอบของ DataFrame

DataFrame ประกอบด้วย

- **row** — แถวของข้อมูล
- **column** — ประเภทหรือตัวแปรของข้อมูล
- **index** — label ที่ใช้ระบุแถว
- **column name** — ชื่อที่ใช้ระบุคอลัมน์
- **value** — ค่าในแต่ละตำแหน่ง

ใน DataFrame ตัวอย่าง

- หนึ่งแถวแทนผู้ตอบหนึ่งคน
- หนึ่งคอลัมน์แทนข้อมูลหนึ่งประเภท

### เปรียบเทียบ DataFrame กับ Excel

| แนวคิด | Excel | pandas |
|---|---|---|
| ตารางข้อมูล | Worksheet หรือ Table | DataFrame |
| คอลัมน์หนึ่งคอลัมน์ | Column | Series |
| แถว | Row | Row |
| หัวตาราง | Header | Column name |
| เลขแถว | Row number | Index |
| ช่องข้อมูล | Cell | Value |
| เลือกคอลัมน์ | คลิกหัวคอลัมน์ | `df["column"]` |
| เลือกแถว | คลิกเลขแถว | `.loc` หรือ `.iloc` |
| กรองข้อมูล | Filter | Boolean selection |
| สร้างคอลัมน์ | ใส่สูตร | กำหนด Series ให้คอลัมน์ใหม่ |

DataFrame ไม่ได้แทนที่ Excel ในทุกงาน

Excel ยังสะดวกสำหรับ

- เปิดดูข้อมูลอย่างรวดเร็ว
- แก้ไขค่าด้วยมือ
- จัดรูปแบบรายงาน
- ตรวจสอบตารางด้วยสายตา

DataFrame เหมาะเมื่อ

- ต้องทำขั้นตอนซ้ำ
- ต้องประมวลผลข้อมูลจำนวนมาก
- ต้องกรองหรือคำนวณหลายเงื่อนไข
- ต้องการบันทึกขั้นตอนเป็นโค้ด

## 7. การตรวจสอบโครงสร้างเบื้องต้น

ก่อนเริ่มเลือกหรือวิเคราะห์ข้อมูล ควรตรวจสอบ DataFrame ก่อน

คำสั่งพื้นฐานที่ใช้บ่อย ได้แก่

- `.head()`
- `.shape`
- `.columns`
- `.dtypes`
- `.info()`

### ดูข้อมูลส่วนบนด้วย `.head()`

In [14]:
df.head()

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
3              4   Khon Kaen   29         2.9      Draft
4              5    Songkhla   63         3.5  Completed

`.head()` แสดงข้อมูล 5 แถวแรกโดยค่าเริ่มต้น

สามารถกำหนดจำนวนแถวที่ต้องการได้ เช่น

In [15]:
df.head(3)

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

### ตรวจสอบจำนวนแถวและคอลัมน์ด้วย `.shape`

In [16]:
df.shape

(5, 5)

ผลลัพธ์อยู่ในรูปแบบ

```python
(number_of_rows, number_of_columns)
```

ดังนั้น `(5, 5)` หมายถึงมี 5 แถวและ 5 คอลัมน์

### ตรวจสอบชื่อคอลัมน์ด้วย `.columns`

In [17]:
df.columns

Index(['respondent_id', 'area', 'age', 'need_score', 'status'], dtype='str')

หากต้องการแปลงชื่อคอลัมน์เป็น List สามารถใช้

In [18]:
df.columns.tolist()

['respondent_id', 'area', 'age', 'need_score', 'status']

### ตรวจสอบชนิดข้อมูลด้วย `.dtypes`

In [19]:
df.dtypes

respondent_id      int64
area                 str
age                int64
need_score       float64
status               str
dtype: object

ชนิดข้อมูลที่พบได้บ่อยใน pandas ได้แก่

| pandas dtype | ความหมาย |
|---|---|
| `int64` | จำนวนเต็ม |
| `float64` | จำนวนทศนิยม |
| `object` | มักใช้เก็บข้อความหรือข้อมูลหลายชนิด |
| `bool` | ค่า True/False |
| `datetime64` | วันที่และเวลา |

### ดูข้อมูลสรุปด้วย `.info()`

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   respondent_id  5 non-null      int64
 1   area           5 non-null      str
 2   age            5 non-null      int64
 3   need_score     5 non-null      float64
 4   status         5 non-null      str
dtypes: float64(1), int64(2), str(2)
memory usage: 332.0 bytes

`.info()` ช่วยตรวจสอบ

- จำนวนแถว
- ชื่อคอลัมน์
- จำนวนค่าที่ไม่ว่าง
- ชนิดข้อมูล
- การใช้หน่วยความจำเบื้องต้น

ในบทการนำเข้าและ EDA เราจะใช้คำสั่งนี้เพื่อตรวจสอบคุณภาพข้อมูลเพิ่มเติม

## 8. การเลือกคอลัมน์

### เลือกคอลัมน์เดียว

ใช้รูปแบบ

```python
df["column_name"]
```

ผลลัพธ์เป็น Series

In [21]:
df["area"]

0       Bangkok
1    Chiang Mai
2       Bangkok
3     Khon Kaen
4      Songkhla
Name: area, dtype: str

In [22]:
type(df["area"])

pandas.Series

เมื่อเลือกคอลัมน์เดียว ผลลัพธ์เป็น Series

ดังนั้น Series สามารถมองได้ว่าเป็นคอลัมน์หนึ่งคอลัมน์ที่ถูกดึงออกจาก DataFrame

### เลือกหลายคอลัมน์

ใส่ชื่อคอลัมน์ไว้ภายใน List

```python
df[["column_1", "column_2"]]
```

ผลลัพธ์เป็น DataFrame

In [23]:
df[["area", "need_score"]]

         area  need_score
0     Bangkok         4.2
1  Chiang Mai         3.8
2     Bangkok         4.7
3   Khon Kaen         2.9
4    Songkhla         3.5

In [24]:
type(df[["area", "need_score"]])

pandas.DataFrame

สรุปความแตกต่าง

- `df["area"]` ได้ Series
- `df[["area"]]` ได้ DataFrame
- `df[["area", "need_score"]]` ได้ DataFrame

แม้จะเลือกเพียงคอลัมน์เดียว แต่หากใช้ List ซ้อนอยู่ ผลลัพธ์จะยังเป็น DataFrame

In [25]:
type(df[["area"]])

pandas.DataFrame

## 9. การเลือกข้อมูลด้วย `.loc`

`.loc` ใช้เลือกข้อมูลด้วย **label**

มักใช้กับ

- ชื่อ index
- ชื่อคอลัมน์
- Boolean Series

รูปแบบทั่วไปคือ

```python
df.loc[row_selection, column_selection]
```

### เลือกแถวตาม index

In [26]:
df.loc[0]

respondent_id            1
area               Bangkok
age                     34
need_score             4.2
status           Completed
Name: 0, dtype: object

### เลือกค่าจากแถวและชื่อคอลัมน์

In [27]:
df.loc[0, "area"]

'Bangkok'

### เลือกหลายแถวและหลายคอลัมน์

In [28]:
df.loc[
    0:2,
    ["respondent_id", "area", "need_score"],
]

   respondent_id        area  need_score
0              1     Bangkok         4.2
1              2  Chiang Mai         3.8
2              3     Bangkok         4.7

ข้อควรระวังคือ slicing ของ `.loc` จะรวม label ปลายทางด้วย

ดังนั้น

```python
df.loc[0:2]
```

จะได้ index `0`, `1` และ `2`

### เลือกทุกแถวและบางคอลัมน์

In [29]:
df.loc[
    :,
    ["area", "need_score"],
]

         area  need_score
0     Bangkok         4.2
1  Chiang Mai         3.8
2     Bangkok         4.7
3   Khon Kaen         2.9
4    Songkhla         3.5

เครื่องหมาย `:` หมายถึงเลือกทุกแถว

## 10. การเลือกข้อมูลด้วย `.iloc`

`.iloc` ใช้เลือกข้อมูลด้วย **ตำแหน่งจำนวนเต็ม** หรือ integer location

รูปแบบทั่วไปคือ

```python
df.iloc[row_position, column_position]
```

ตำแหน่งเริ่มจาก `0` เช่นเดียวกับ index ของ Python

### เลือกแถวแรก

In [30]:
df.iloc[0]

respondent_id            1
area               Bangkok
age                     34
need_score             4.2
status           Completed
Name: 0, dtype: object

### เลือกสามแถวแรก

In [31]:
df.iloc[0:3]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

slicing ของ `.iloc` ไม่รวมตำแหน่งปลายทาง

ดังนั้น `0:3` หมายถึงตำแหน่ง `0`, `1` และ `2`

### เลือกค่าจากแถวแรกและคอลัมน์ที่สอง

In [32]:
df.iloc[0, 1]

'Bangkok'

ใน DataFrame นี้

- แถวตำแหน่ง `0` คือผู้ตอบคนแรก
- คอลัมน์ตำแหน่ง `1` คือ `area`

ผลลัพธ์จึงเป็น `"Bangkok"`

### เลือกหลายแถวและหลายคอลัมน์

In [33]:
df.iloc[
    0:3,
    0:3,
]

   respondent_id        area  age
0              1     Bangkok   34
1              2  Chiang Mai   52
2              3     Bangkok   41

### เปรียบเทียบ `.loc` กับ `.iloc`

| คำสั่ง | เลือกจาก | ปลายทางของ slicing |
|---|---|---|
| `.loc` | label หรือชื่อ | รวมปลายทาง |
| `.iloc` | ตำแหน่งจำนวนเต็ม | ไม่รวมปลายทาง |

แนวทางทั่วไปคือ

- ใช้ `.loc` เมื่อรู้ชื่อคอลัมน์หรือ label
- ใช้ `.iloc` เมื่อต้องการข้อมูลตามตำแหน่ง

## 11. การกรองข้อมูลด้วยเงื่อนไข

เราสามารถสร้างเงื่อนไขกับทั้งคอลัมน์ได้

In [34]:
df["need_score"] >= 4.0

0     True
1    False
2     True
3    False
4    False
Name: need_score, dtype: bool

ผลลัพธ์คือ Boolean Series ที่มีจำนวนค่าเท่ากับจำนวนแถวใน DataFrame

### ใช้ Boolean Series กรอง DataFrame

In [35]:
df[
    df["need_score"] >= 4.0
]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed
2              3  Bangkok   41         4.7   Verified

คำสั่งนี้หมายถึง

> เลือกเฉพาะแถวที่ `need_score` มากกว่าหรือเท่ากับ `4.0`

สามารถเขียนด้วย `.loc` เพื่อให้เห็นการเลือกแถวชัดเจนขึ้น

In [36]:
df.loc[
    df["need_score"] >= 4.0
]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed
2              3  Bangkok   41         4.7   Verified

### กรองข้อมูลข้อความ

In [37]:
df.loc[
    df["area"] == "Bangkok"
]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed
2              3  Bangkok   41         4.7   Verified

In [38]:
df.loc[
    df["status"] == "Completed"
]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
4              5    Songkhla   63         3.5  Completed

Python แยกตัวพิมพ์เล็กและใหญ่

ดังนั้น `"Completed"` และ `"completed"` ถือว่าไม่เท่ากัน

### เลือกค่าจากหลายรายการด้วย `.isin()`

หากต้องการเลือกหลายพื้นที่ สามารถใช้ `.isin()`

In [39]:
target_areas = [
    "Bangkok",
    "Chiang Mai",
]

df.loc[
    df["area"].isin(target_areas)
]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

`.isin()` เหมาะกับการตรวจสอบว่าค่าในคอลัมน์อยู่ใน List ที่กำหนดหรือไม่

วิธีนี้อ่านง่ายกว่าการเขียนเงื่อนไข `|` ซ้ำหลายครั้ง

### เลือกค่าที่ไม่อยู่ในรายการ

In [40]:
df.loc[
    ~df["status"].isin(["Draft"])
]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
4              5    Songkhla   63         3.5  Completed

เครื่องหมาย `~` ใช้กลับค่า Boolean

ดังนั้นตัวอย่างนี้หมายถึง เลือกแถวที่สถานะไม่ใช่ `"Draft"`

## 12. การใช้หลายเงื่อนไข

เมื่อกรองข้อมูลใน pandas ใช้ตัวดำเนินการดังนี้

| Operator | ความหมาย |
|---|---|
| `&` | และ |
| `|` | หรือ |
| `~` | ไม่ใช่ |

แต่ละเงื่อนไขควรอยู่ในวงเล็บ

### เงื่อนไขแบบ AND

เลือกผู้ตอบที่

- คะแนนตั้งแต่ 4.0 ขึ้นไป
- และมีสถานะ `"Completed"`

In [41]:
df.loc[
    (
        df["need_score"] >= 4.0
    )
    & (
        df["status"] == "Completed"
    )
]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed

### เงื่อนไขแบบ OR

เลือกผู้ตอบที่อยู่ใน Bangkok หรือ Chiang Mai

In [42]:
df.loc[
    (
        df["area"] == "Bangkok"
    )
    | (
        df["area"] == "Chiang Mai"
    )
]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

ในกรณีนี้ควรใช้ `.isin()` เพราะสั้นและขยายรายการพื้นที่ได้ง่ายกว่า

In [43]:
df.loc[
    df["area"].isin(
        ["Bangkok", "Chiang Mai"]
    )
]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

### ข้อควรระวัง

ใน pandas ไม่ควรใช้ `and`, `or` และ `not` กับ Series

ตัวอย่างที่ไม่ถูกต้อง

```python
df[
    (df["need_score"] >= 4.0)
    and
    (df["status"] == "Completed")
]
```

ให้ใช้ `&`, `|` และ `~` แทน

## 13. การสร้างคอลัมน์ใหม่

สามารถสร้างคอลัมน์ใหม่ได้ด้วยรูปแบบ

```python
df["new_column"] = expression
```

ค่าในคอลัมน์ใหม่จะถูกคำนวณตามแต่ละแถว

### สร้างคอลัมน์จากการคำนวณ

In [44]:
df["adjusted_need_score"] = (
    df["need_score"] + 0.5
)

df

   respondent_id        area  age  need_score     status  adjusted_need_score
0              1     Bangkok   34         4.2  Completed                  4.7
1              2  Chiang Mai   52         3.8  Completed                  4.3
2              3     Bangkok   41         4.7   Verified                  5.2
3              4   Khon Kaen   29         2.9      Draft                  3.4
4              5    Songkhla   63         3.5  Completed                  4.0

pandas คำนวณกับข้อมูลทั้งคอลัมน์โดยไม่ต้องเขียน Loop ทีละแถว

### สร้างคอลัมน์ Boolean จากเงื่อนไข

In [45]:
df["is_high_need"] = (
    df["need_score"] >= 4.0
)

df

,respondent_id,area,age,need_score,status,adjusted_need_score,is_high_need
0,1,Bangkok,34,4.2,Completed,4.7,True
1,2,Chiang Mai,52,3.8,Completed,4.3,False
2,3,Bangkok,41,4.7,Verified,5.2,True
3,4,Khon Kaen,29,2.9,Draft,3.4,False
4,5,Songkhla,63,3.5,Completed,4.0,False

คอลัมน์ `is_high_need` มีค่า

- `True` เมื่อคะแนนตั้งแต่ 4.0
- `False` เมื่อคะแนนต่ำกว่า 4.0

แนวคิดนี้คล้ายการสร้างคอลัมน์สูตร `TRUE/FALSE` ใน Excel

### สร้างคอลัมน์จากหลายคอลัมน์

In [46]:
df["age_plus_score"] = (
    df["age"]
    + df["need_score"]
)

df

,respondent_id,area,age,need_score,status,adjusted_need_score,is_high_need,age_plus_score
0,1,Bangkok,34,4.2,Completed,4.7,True,38.2
1,2,Chiang Mai,52,3.8,Completed,4.3,False,55.8
2,3,Bangkok,41,4.7,Verified,5.2,True,45.7
3,4,Khon Kaen,29,2.9,Draft,3.4,False,31.9
4,5,Songkhla,63,3.5,Completed,4.0,False,66.5

แม้ตัวอย่างนี้สามารถคำนวณได้ แต่การสร้างคอลัมน์ควรมีความหมายทางธุรกิจหรือการวิเคราะห์ที่ชัดเจน

ไม่ควรนำคอลัมน์มาคำนวณร่วมกันเพียงเพราะมีชนิดข้อมูลเป็นตัวเลข

### แก้ไขค่าคอลัมน์เดิม

การกำหนดค่าให้ชื่อคอลัมน์เดิมจะเขียนทับคอลัมน์นั้น

In [47]:
df["status_standardized"] = (
    df["status"].str.lower()
)

df

,respondent_id,area,age,need_score,status,adjusted_need_score,is_high_need,age_plus_score,status_standardized
0,1,Bangkok,34,4.2,Completed,4.7,True,38.2,completed
1,2,Chiang Mai,52,3.8,Completed,4.3,False,55.8,completed
2,3,Bangkok,41,4.7,Verified,5.2,True,45.7,verified
3,4,Khon Kaen,29,2.9,Draft,3.4,False,31.9,draft
4,5,Songkhla,63,3.5,Completed,4.0,False,66.5,completed

ในตัวอย่างนี้สร้างคอลัมน์ใหม่แทนการเขียนทับ `status` เดิม เพื่อให้เปรียบเทียบผลก่อนและหลังได้

ในงานจริง ควรพิจารณาว่าต้องรักษาข้อมูลต้นฉบับไว้หรือไม่

## 14. การใช้ Function กับ DataFrame

เราสามารถสร้าง Function เพื่อกำหนดกฎ แล้วใช้ `.apply()` กับ Series ได้

ตัวอย่างเกณฑ์

| คะแนน | ระดับ |
|---:|---|
| ตั้งแต่ 4.0 ขึ้นไป | High |
| ตั้งแต่ 3.0 แต่น้อยกว่า 4.0 | Medium |
| น้อยกว่า 3.0 | Low |

In [48]:
def classify_need(score):
    if score >= 4.0:
        return "High"
    elif score >= 3.0:
        return "Medium"
    else:
        return "Low"

ควรทดสอบ Function กับค่าเดียวก่อน

In [49]:
classify_need(4.2)

'High'

จากนั้นใช้ `.apply()` กับคอลัมน์ `need_score`

In [50]:
df["need_level"] = (
    df["need_score"]
    .apply(classify_need)
)

df

,respondent_id,area,age,need_score,status,adjusted_need_score,is_high_need,age_plus_score,status_standardized,need_level
0,1,Bangkok,34,4.2,Completed,4.7,True,38.2,completed,High
1,2,Chiang Mai,52,3.8,Completed,4.3,False,55.8,completed,Medium
2,3,Bangkok,41,4.7,Verified,5.2,True,45.7,verified,High
3,4,Khon Kaen,29,2.9,Draft,3.4,False,31.9,draft,Low
4,5,Songkhla,63,3.5,Completed,4.0,False,66.5,completed,Medium

`.apply()` นำ Function ไปใช้กับค่าทีละค่าใน Series

เหมาะเมื่อ

- มีกฎที่อธิบายด้วย Function ได้ชัดเจน
- Logic มีหลายระดับ
- Function จะถูกนำกลับมาใช้ซ้ำ

สำหรับการคำนวณง่าย ๆ ควรใช้การคำนวณกับทั้งคอลัมน์โดยตรงก่อน เพราะมักสั้นและทำงานได้เร็วกว่า

## 15. การใช้ Loop กับ DataFrame อย่างเหมาะสม

Loop ยังมีประโยชน์เมื่อต้องทำงานกับ

- รายชื่อคอลัมน์
- หลาย DataFrame
- หลายไฟล์
- หลายค่ากำหนด
- ขั้นตอนที่ไม่สามารถเขียนแบบทั้งคอลัมน์ได้ง่าย

### Loop ผ่านรายชื่อคอลัมน์

In [51]:
columns_to_show = [
    "area",
    "age",
    "need_score",
]

for column in columns_to_show:
    print(f"Column: {column}")
    print(df[column])
    print()

Column: area
0       Bangkok
1    Chiang Mai
2       Bangkok
3     Khon Kaen
4      Songkhla
Name: area, dtype: str

Column: age
0    34
1    52
2    41
3    29
4    63
Name: age, dtype: int64

Column: need_score
0    4.2
1    3.8
2    4.7
3    2.9
4    3.5
Name: need_score, dtype: float64

### การวนทีละแถว

pandas มี `.iterrows()` สำหรับอ่านข้อมูลทีละแถว

In [52]:
for index, row in df.iterrows():
    print(
        row["respondent_id"],
        row["area"],
        row["need_level"],
    )

1 Bangkok High
2 Chiang Mai Medium
3 Bangkok High
4 Khon Kaen Low
5 Songkhla Medium

อย่างไรก็ตาม ไม่ควรใช้ `.iterrows()` เป็นวิธีหลักในการคำนวณหรือสร้างคอลัมน์

ในหลายกรณี ควรใช้

- การคำนวณกับ Series
- Boolean selection
- `.loc`
- `.isin()`
- `.apply()`
- คำสั่งสรุปของ pandas

เพราะมักอ่านง่ายกว่าและทำงานได้เร็วกว่า Loop ทีละแถว

## 16. ข้อผิดพลาดที่พบบ่อย

### 16.1 ลืมนำเข้า pandas

## 16. ข้อผิดพลาดที่พบบ่อย

### 16.1 ลืมนำเข้า pandas

In [53]:
# ต้องรันคำสั่งนี้ก่อนใช้ pd

import pandas as pd

### 16.2 ความยาวของ List ใน Dictionary ไม่เท่ากัน

คำสั่งต่อไปนี้จะเกิด `ValueError`

In [54]:
# ตัวอย่างที่ทำให้เกิด ValueError
# เพราะแต่ละ List มีจำนวนสมาชิกไม่เท่ากัน

invalid_data = {
    "respondent_id": [1, 2, 3],
    "area": ["Bangkok", "Chiang Mai"],
}

pd.DataFrame(invalid_data)

ValueError: All arrays must be of the same length

ก่อนสร้าง DataFrame ควรตรวจสอบว่าแต่ละ List มีจำนวนสมาชิกเท่ากัน

### 16.3 เลือกชื่อคอลัมน์ผิด

หากไม่มีชื่อคอลัมน์ที่ระบุจะเกิด `KeyError`

In [55]:
df.columns.tolist()

['respondent_id',
 'area',
 'age',
 'need_score',
 'status',
 'adjusted_need_score',
 'is_high_need',
 'age_plus_score',
 'status_standardized',
 'need_level']

In [56]:
# ตัวอย่างที่ทำให้เกิด KeyError

df["province"]

KeyError: 'province'

ใน DataFrame ตัวอย่างใช้ชื่อ `area` ไม่ใช่ `province`

ควรตรวจชื่อคอลัมน์ด้วย `.columns` ก่อนใช้งาน

### 16.4 สับสนระหว่าง Series กับ DataFrame

In [58]:
area_series = df["area"]
area_dataframe = df[["area"]]

print(type(area_series))
print(type(area_dataframe))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

- วงเล็บเหลี่ยมหนึ่งชั้นกับชื่อคอลัมน์ ได้ Series
- ใช้ List ของชื่อคอลัมน์ ได้ DataFrame

### 16.5 สับสนระหว่าง `.loc` กับ `.iloc`

- `.loc` ใช้ label หรือชื่อ
- `.iloc` ใช้ตำแหน่งจำนวนเต็ม

In [59]:
print(df.loc[0, "area"])
print(df.iloc[0, 1])

Bangkok
Bangkok

ทั้งสองคำสั่งได้ค่าเดียวกันในตัวอย่างนี้ แต่เลือกข้อมูลด้วยหลักการต่างกัน

### 16.6 ลืมวงเล็บในหลายเงื่อนไข

In [60]:
correct_filter = df.loc[
    (
        df["need_score"] >= 4.0
    )
    & (
        df["status"] == "Completed"
    )
]

correct_filter

,respondent_id,area,age,need_score,status,adjusted_need_score,is_high_need,age_plus_score,status_standardized,need_level
0,1,Bangkok,34,4.2,Completed,4.7,True,38.2,completed,High

แต่ละเงื่อนไขควรอยู่ในวงเล็บก่อนเชื่อมด้วย `&` หรือ `|`

### 16.7 ใช้ `and` หรือ `or` กับ Series

In [61]:
# ตัวอย่างที่ไม่ถูกต้อง

df[
    (df["need_score"] >= 4.0)
    and
    (df["status"] == "Completed")
]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

ให้ใช้ `&` หรือ `|` แทน

### 16.8 แก้ไข DataFrame ต้นฉบับโดยไม่ตั้งใจ

เมื่อสร้างคอลัมน์ใหม่ เช่น

```python
df["new_column"] = ...
```

DataFrame `df` จะถูกเปลี่ยนแปลง

หากต้องการทดลองโดยไม่เปลี่ยนต้นฉบับ สามารถสร้างสำเนาก่อน

In [62]:
df_copy = df.copy()

# แบบฝึกหัดท้ายบท

แบบฝึกหัดนี้ใช้ข้อมูลสมมติจากการสำรวจครัวเรือน

ข้อมูลประกอบด้วย

- `respondent_id` — รหัสผู้ตอบ
- `province` — จังหวัด
- `age` — อายุ
- `household_size` — จำนวนสมาชิกในครัวเรือน
- `monthly_income` — รายได้ต่อเดือน
- `debt_amount` — จำนวนหนี้
- `need_score` — คะแนนความต้องการความช่วยเหลือ
- `status` — สถานะแบบสำรวจ

แบบฝึกหัดครอบคลุม Series, DataFrame, การเลือกข้อมูล การกรองข้อมูล การสร้างคอลัมน์ และการใช้ Function

## แบบฝึกหัดที่ 1: สร้างและตรวจสอบ DataFrame

กำหนดข้อมูลดังนี้

```python
survey_data = {
    "respondent_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "province": [
        "Bangkok",
        "Chiang Mai",
        "Khon Kaen",
        "Songkhla",
        "Bangkok",
        "Khon Kaen",
        "Chiang Mai",
        "Songkhla",
    ],
    "age": [34, 52, 41, 29, 63, 47, 38, 55],
    "household_size": [3, 5, 4, 2, 6, 4, 3, 5],
    "monthly_income": [
        28000,
        15000,
        12000,
        22000,
        9000,
        11000,
        30000,
        8000,
    ],
    "debt_amount": [
        50000,
        120000,
        80000,
        30000,
        150000,
        95000,
        20000,
        130000,
    ],
    "need_score": [
        3.5,
        4.2,
        4.7,
        2.8,
        4.9,
        4.1,
        2.5,
        4.6,
    ],
    "status": [
        "Completed",
        "Completed",
        "Verified",
        "Draft",
        "Completed",
        "Verified",
        "Completed",
        "Draft",
    ],
}
```

ให้ทำงานต่อไปนี้

1. สร้าง DataFrame ชื่อ `survey_df`
2. แสดง 5 แถวแรก
3. ตรวจสอบจำนวนแถวและคอลัมน์
4. ตรวจสอบชื่อคอลัมน์
5. ตรวจสอบชนิดข้อมูล

In [50]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 1
>
> ใช้ `pd.DataFrame()` สร้าง DataFrame จาก Dictionary แล้วใช้ `.head()`, `.shape`, `.columns` และ `.dtypes` ตรวจสอบโครงสร้าง

In [63]:
survey_data = {
    "respondent_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "province": [
        "Bangkok",
        "Chiang Mai",
        "Khon Kaen",
        "Songkhla",
        "Bangkok",
        "Khon Kaen",
        "Chiang Mai",
        "Songkhla",
    ],
    "age": [34, 52, 41, 29, 63, 47, 38, 55],
    "household_size": [3, 5, 4, 2, 6, 4, 3, 5],
    "monthly_income": [
        28000,
        15000,
        12000,
        22000,
        9000,
        11000,
        30000,
        8000,
    ],
    "debt_amount": [
        50000,
        120000,
        80000,
        30000,
        150000,
        95000,
        20000,
        130000,
    ],
    "need_score": [
        3.5,
        4.2,
        4.7,
        2.8,
        4.9,
        4.1,
        2.5,
        4.6,
    ],
    "status": [
        "Completed",
        "Completed",
        "Verified",
        "Draft",
        "Completed",
        "Verified",
        "Completed",
        "Draft",
    ],
}

survey_df = pd.DataFrame(survey_data)

print(survey_df.head())
print(survey_df.shape)
print(survey_df.columns.tolist())
print(survey_df.dtypes)

   respondent_id    province  age  household_size  monthly_income  \
0              1     Bangkok   34               3           28000
1              2  Chiang Mai   52               5           15000
2              3   Khon Kaen   41               4           12000
3              4    Songkhla   29               2           22000
4              5     Bangkok   63               6            9000

   debt_amount  need_score     status
0        50000         3.5  Completed
1       120000         4.2  Completed
2        80000         4.7   Verified
3        30000         2.8      Draft
4       150000         4.9  Completed
(8, 8)
['respondent_id', 'province', 'age', 'household_size', 'monthly_income', 'debt_amount', 'need_score', 'status']
respondent_id       int64
province              str
age                 int64
household_size      int64
monthly_income      int64
debt_amount         int64
need_score        float64
status                str
dtype: object

## แบบฝึกหัดที่ 2: สร้างและตรวจสอบ Series

จาก `survey_df`

1. เลือกคอลัมน์ `need_score`
2. เก็บไว้ในตัวแปร `need_score_series`
3. ตรวจสอบชนิดของ object
4. สร้าง Boolean Series ด้วยเงื่อนไข `need_score >= 4.0`
5. อธิบายว่า Boolean Series นี้นำไปใช้ทำอะไรได้

In [51]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 2
>
> `survey_df["need_score"]` ให้ผลลัพธ์เป็น Series
>
> การเปรียบเทียบกับ `4.0` ให้ Boolean Series ซึ่งใช้ระบุว่าแต่ละแถวเข้าเงื่อนไขหรือไม่ และสามารถนำไปกรอง DataFrame ได้

In [64]:
need_score_series = survey_df["need_score"]

print(type(need_score_series))

high_need_condition = (
    need_score_series >= 4.0
)

high_need_condition

<class 'pandas.Series'>

0    False
1     True
2     True
3    False
4     True
5     True
6    False
7     True
Name: need_score, dtype: bool

## แบบฝึกหัดที่ 3: เลือกคอลัมน์ที่จำเป็น

เลือกคอลัมน์ต่อไปนี้จาก `survey_df`

- `respondent_id`
- `province`
- `monthly_income`
- `debt_amount`
- `need_score`

เก็บผลลัพธ์ในตัวแปร `vulnerability_df`

จากนั้นตรวจสอบว่า `vulnerability_df` เป็น Series หรือ DataFrame

In [52]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 3
>
> เนื่องจากเลือกหลายคอลัมน์ ต้องใส่ชื่อคอลัมน์ไว้ใน List ผลลัพธ์จึงเป็น DataFrame

In [65]:
selected_columns = [
    "respondent_id",
    "province",
    "monthly_income",
    "debt_amount",
    "need_score",
]

vulnerability_df = survey_df[
    selected_columns
]

print(vulnerability_df)
print(type(vulnerability_df))

   respondent_id    province  monthly_income  debt_amount  need_score
0              1     Bangkok           28000        50000         3.5
1              2  Chiang Mai           15000       120000         4.2
2              3   Khon Kaen           12000        80000         4.7
3              4    Songkhla           22000        30000         2.8
4              5     Bangkok            9000       150000         4.9
5              6   Khon Kaen           11000        95000         4.1
6              7  Chiang Mai           30000        20000         2.5
7              8    Songkhla            8000       130000         4.6
<class 'pandas.DataFrame'>

## แบบฝึกหัดที่ 4: เลือกข้อมูลด้วย `.loc` และ `.iloc`

ให้ทำงานต่อไปนี้

1. ใช้ `.loc` เลือกข้อมูล index `2`
2. ใช้ `.loc` เลือกค่า `province` ของ index `2`
3. ใช้ `.iloc` เลือก 3 แถวแรก
4. ใช้ `.iloc` เลือกค่าที่แถวตำแหน่ง `0` และคอลัมน์ตำแหน่ง `1`
5. อธิบายความแตกต่างระหว่าง `.loc` และ `.iloc`

In [53]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 4
>
> - `.loc` ใช้ label หรือชื่อคอลัมน์
> - `.iloc` ใช้ตำแหน่งจำนวนเต็ม
> - ค่าแถวตำแหน่ง `0` คอลัมน์ตำแหน่ง `1` คือ `"Bangkok"`

In [66]:
row_index_2 = survey_df.loc[2]

province_index_2 = survey_df.loc[
    2,
    "province",
]

first_three_rows = survey_df.iloc[0:3]

first_row_second_column = (
    survey_df.iloc[0, 1]
)

print(row_index_2)
print(province_index_2)
print(first_three_rows)
print(first_row_second_column)

respondent_id             3
province          Khon Kaen
age                      41
household_size            4
monthly_income        12000
debt_amount           80000
need_score              4.7
status             Verified
Name: 2, dtype: object
Khon Kaen
   respondent_id    province  age  household_size  monthly_income  \
0              1     Bangkok   34               3           28000
1              2  Chiang Mai   52               5           15000
2              3   Khon Kaen   41               4           12000

   debt_amount  need_score     status
0        50000         3.5  Completed
1       120000         4.2  Completed
2        80000         4.7   Verified
Bangkok

## แบบฝึกหัดที่ 5: กรองครัวเรือนที่มีความต้องการสูง

เลือกเฉพาะแถวที่ `need_score` มากกว่าหรือเท่ากับ `4.0`

เก็บผลลัพธ์ในตัวแปร `high_need_df`

จากนั้นแสดงเฉพาะคอลัมน์

- `respondent_id`
- `province`
- `need_score`

In [54]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 5
>
> สร้างเงื่อนไขจากคอลัมน์ `need_score` แล้วใช้ `.loc` เลือกแถวและคอลัมน์ที่ต้องการ

In [67]:
high_need_df = survey_df.loc[
    survey_df["need_score"] >= 4.0,
    [
        "respondent_id",
        "province",
        "need_score",
    ],
]

high_need_df

   respondent_id    province  need_score
1              2  Chiang Mai         4.2
2              3   Khon Kaen         4.7
4              5     Bangkok         4.9
5              6   Khon Kaen         4.1
7              8    Songkhla         4.6

## แบบฝึกหัดที่ 6: กรองข้อมูลด้วยหลายเงื่อนไข

เลือกครัวเรือนที่เข้าเงื่อนไขทั้งหมดดังนี้

- `need_score` มากกว่าหรือเท่ากับ `4.0`
- `monthly_income` น้อยกว่า `15000`
- `status` เป็น `"Completed"` หรือ `"Verified"`

เก็บผลลัพธ์ในตัวแปร `target_households`

In [55]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 6
>
> ใช้ `&` เชื่อมเงื่อนไขที่ต้องเป็นจริงพร้อมกัน และใช้ `.isin()` ตรวจสอบหลายสถานะ

In [68]:
valid_statuses = [
    "Completed",
    "Verified",
]

target_households = survey_df.loc[
    (
        survey_df["need_score"] >= 4.0
    )
    & (
        survey_df["monthly_income"] < 15000
    )
    & (
        survey_df["status"].isin(
            valid_statuses
        )
    )
]

target_households

,respondent_id,province,age,household_size,monthly_income,debt_amount,need_score,status
2,3,Khon Kaen,41,4,12000,80000,4.7,Verified
4,5,Bangkok,63,6,9000,150000,4.9,Completed
5,6,Khon Kaen,47,4,11000,95000,4.1,Verified

## แบบฝึกหัดที่ 7: เลือกข้อมูลหลายจังหวัดด้วย `.isin()`

เลือกเฉพาะข้อมูลจากจังหวัดต่อไปนี้

- Bangkok
- Chiang Mai
- Khon Kaen

เก็บรายชื่อจังหวัดไว้ในตัวแปร `target_provinces`

จากนั้นกรอง `survey_df` และเก็บผลลัพธ์ใน `selected_provinces_df`

In [56]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 7
>
> `.isin()` ตรวจสอบว่าค่าในคอลัมน์ `province` อยู่ใน List `target_provinces` หรือไม่

In [69]:
target_provinces = [
    "Bangkok",
    "Chiang Mai",
    "Khon Kaen",
]

selected_provinces_df = survey_df.loc[
    survey_df["province"].isin(
        target_provinces
    )
]

selected_provinces_df

,respondent_id,province,age,household_size,monthly_income,debt_amount,need_score,status
0,1,Bangkok,34,3,28000,50000,3.5,Completed
1,2,Chiang Mai,52,5,15000,120000,4.2,Completed
2,3,Khon Kaen,41,4,12000,80000,4.7,Verified
4,5,Bangkok,63,6,9000,150000,4.9,Completed
5,6,Khon Kaen,47,4,11000,95000,4.1,Verified
6,7,Chiang Mai,38,3,30000,20000,2.5,Completed

## แบบฝึกหัดที่ 8: สร้างคอลัมน์ใหม่

สร้างคอลัมน์ใหม่ 3 คอลัมน์ใน `survey_df`

### 1. `debt_to_income_ratio`

คำนวณจาก

```python
debt_amount / monthly_income
```

### 2. `is_low_income`

กำหนดให้เป็น `True` เมื่อ `monthly_income` น้อยกว่า `15000`

### 3. `is_high_need`

กำหนดให้เป็น `True` เมื่อ `need_score` มากกว่าหรือเท่ากับ `4.0`

หลังจากสร้างแล้ว ให้แสดงเฉพาะคอลัมน์

- `respondent_id`
- `monthly_income`
- `debt_amount`
- `debt_to_income_ratio`
- `is_low_income`
- `is_high_need`

In [57]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 8
>
> pandas สามารถคำนวณและเปรียบเทียบค่าทั้งคอลัมน์ได้โดยตรง จึงไม่ต้องใช้ Loop ทีละแถว

In [70]:
survey_df["debt_to_income_ratio"] = (
    survey_df["debt_amount"]
    / survey_df["monthly_income"]
)

survey_df["is_low_income"] = (
    survey_df["monthly_income"] < 15000
)

survey_df["is_high_need"] = (
    survey_df["need_score"] >= 4.0
)

survey_df.loc[
    :,
    [
        "respondent_id",
        "monthly_income",
        "debt_amount",
        "debt_to_income_ratio",
        "is_low_income",
        "is_high_need",
    ],
]

,respondent_id,monthly_income,debt_amount,debt_to_income_ratio,is_low_income,is_high_need
0,1,28000,50000,1.785714,False,False
1,2,15000,120000,8.000000,False,True
2,3,12000,80000,6.666667,True,True
3,4,22000,30000,1.363636,False,False
4,5,9000,150000,16.666667,True,True
5,6,11000,95000,8.636364,True,True
6,7,30000,20000,0.666667,False,False
7,8,8000,130000,16.250000,True,True

## แบบฝึกหัดที่ 9: ใช้ Function และ `.apply()`

สร้าง Function ชื่อ `classify_need_level()`

กำหนดเกณฑ์ดังนี้

| คะแนน | ระดับ |
|---:|---|
| ตั้งแต่ 4.5 ขึ้นไป | Very High |
| ตั้งแต่ 4.0 แต่น้อยกว่า 4.5 | High |
| ตั้งแต่ 3.0 แต่น้อยกว่า 4.0 | Medium |
| น้อยกว่า 3.0 | Low |

จากนั้นใช้ `.apply()` สร้างคอลัมน์ใหม่ชื่อ `need_level`

In [58]:
# เขียนคำตอบของคุณใน Cell นี้

> ### เฉลยแบบฝึกหัดที่ 9
>
> เรียงเงื่อนไขจากคะแนนสูงไปต่ำ แล้วใช้ `.apply()` ส่งคะแนนแต่ละค่าเข้า Function

In [71]:
def classify_need_level(score):
    if score >= 4.5:
        return "Very High"
    elif score >= 4.0:
        return "High"
    elif score >= 3.0:
        return "Medium"
    else:
        return "Low"

In [72]:
survey_df["need_level"] = (
    survey_df["need_score"]
    .apply(classify_need_level)
)

survey_df.loc[
    :,
    [
        "respondent_id",
        "province",
        "need_score",
        "need_level",
    ],
]

   respondent_id    province  need_score need_level
0              1     Bangkok         3.5     Medium
1              2  Chiang Mai         4.2       High
2              3   Khon Kaen         4.7  Very High
3              4    Songkhla         2.8        Low
4              5     Bangkok         4.9  Very High
5              6   Khon Kaen         4.1       High
6              7  Chiang Mai         2.5        Low
7              8    Songkhla         4.6  Very High

## แบบฝึกหัดที่ 10: สร้างข้อมูลสำหรับติดตามงาน

เลือกเฉพาะผู้ตอบที่เข้าเงื่อนไขอย่างน้อยหนึ่งข้อ

- `need_level` เป็น `"Very High"`
- หรือ `is_low_income` เป็น `True`

เก็บผลลัพธ์ใน `follow_up_df`

จากนั้น

1. เลือกเฉพาะคอลัมน์  
   `respondent_id`, `province`, `monthly_income`, `need_score`, `need_level`
2. ใช้ Loop ผ่าน `follow_up_df` เพื่อแสดงข้อความในรูปแบบ

```text
Respondent 3 จาก Khon Kaen มี need level ระดับ Very High
```

แบบฝึกหัดนี้ใช้ Loop เพื่อสร้างข้อความสำหรับรายงาน ไม่ใช่เพื่อคำนวณคอลัมน์ใหม่

> ### เฉลยแบบฝึกหัดที่ 10
>
> ใช้ `|` เชื่อมเงื่อนไขที่ต้องการอย่างน้อยหนึ่งข้อ จากนั้นใช้ `.iterrows()` เพื่อสร้างข้อความจากแต่ละแถว
>
> ในกรณีนี้ Loop ใช้เพื่อแสดงข้อความ ไม่ได้ใช้คำนวณคอลัมน์

In [73]:
follow_up_df = survey_df.loc[
    (
        survey_df["need_level"]
        == "Very High"
    )
    | (
        survey_df["is_low_income"]
    ),
    [
        "respondent_id",
        "province",
        "monthly_income",
        "need_score",
        "need_level",
    ],
]

follow_up_df

   respondent_id   province  monthly_income  need_score need_level
2              3  Khon Kaen           12000         4.7  Very High
4              5    Bangkok            9000         4.9  Very High
5              6  Khon Kaen           11000         4.1       High
7              8   Songkhla            8000         4.6  Very High

In [74]:
for index, row in follow_up_df.iterrows():
    print(
        f"Respondent {row['respondent_id']} "
        f"จาก {row['province']} มี need level "
        f"ระดับ {row['need_level']}"
    )

Respondent 3 จาก Khon Kaen มี need level ระดับ Very High
Respondent 5 จาก Bangkok มี need level ระดับ Very High
Respondent 6 จาก Khon Kaen มี need level ระดับ High
Respondent 8 จาก Songkhla มี need level ระดับ Very High