# บทที่ 7: จาก list และ dictionary สู่ pandas Series และ DataFrame 

ในวันที่ 2 เราได้เรียนรู้ data structure พื้นฐานของ Python เช่น 
- `list` 
- `dictionary` 

รวมถึงเครื่องมือพื้นฐานอื่น ๆ เช่น 
- condition 
- `if` 
- loop 
- function 

ในบทนี้ เราจะต่อยอดจากสิ่งเหล่านั้นไปสู่ data structure ที่เหมาะกับงานวิเคราะห์ข้อมูลมากขึ้น ได้แก่ 
- `Series` 
- `DataFrame` 

ซึ่งเป็น data structure หลักของ library ที่ชื่อว่า `pandas` เป้าหมายของบทนี้คือการเข้าใจว่า ทำไม `Series` และ `DataFrame` จึงเหมาะกับงานข้อมูลมากกว่า `list` และ `dictionary` เมื่อข้อมูลเริ่มมีลักษณะเป็นตาราง

## ผลการเรียนรู้ที่คาดหวัง

เมื่อเรียนจบบทนี้ ผู้เรียนจะสามารถ 
1. อธิบายข้อจำกัดของ `list` เมื่อนำมาใช้จัดเก็บข้อมูลหลายชุดที่สัมพันธ์กันได้ 
2. อธิบายข้อจำกัดของ `dictionary` เมื่อนำมาใช้แทนข้อมูลแบบตารางได้ 
3. อธิบายได้ว่า `Series` คืออะไร และแตกต่างจาก `list` อย่างไร 
4. อธิบายได้ว่า `DataFrame` คืออะไร และแตกต่างจาก `dictionary` อย่างไร 
5. เปรียบเทียบ DataFrame กับตารางข้อมูลใน Excel ได้ 
6. สร้าง `Series` จาก `list` ได้ 
7. สร้าง `DataFrame` จาก `dictionary` ได้ 
8. เลือก column เดียวและหลาย column จาก DataFrame ได้ 
9. เลือกข้อมูลด้วย `.loc` และ `.iloc` ได้ 
10. เลือกข้อมูลแบบมีเงื่อนไข หรือ boolean selection ได้ 
11. ประยุกต์ใช้ `if`, loop และ function กับข้อมูลใน DataFrame ได้ในระดับพื้นฐาน

## ลำดับเนื้อหา

บทเรียนนี้ประกอบด้วยหัวข้อต่อไปนี้

1. ทบทวน `list`
2. ข้อจำกัดของ `list` เมื่อข้อมูลเริ่มมีหลาย column
3. จาก `list` สู่ pandas `Series`
4. `Series` ต่างจาก `list` อย่างไร
5. ทบทวน `dictionary`
6. จาก `dictionary` สู่ pandas `DataFrame`
7. DataFrame คืออะไร
8. เปรียบเทียบ DataFrame กับ Excel
9. DataFrame เป็นขั้นกว่าของ dictionary อย่างไร
10. การเลือก column จาก DataFrame
11. การเลือกข้อมูลด้วย `.iloc`
12. การเลือกข้อมูลด้วย `.loc`
13. การเลือกข้อมูลแบบมีเงื่อนไข
14. การใช้หลายเงื่อนไข
15. การสร้าง column ใหม่จากเงื่อนไข
16. การประยุกต์ใช้ `if` และ function กับ DataFrame
17. การประยุกต์ใช้ loop กับ DataFrame
18. แบบฝึกหัดท้ายบท

## 1. ทบทวน list

`list` เป็น data structure ที่ใช้เก็บข้อมูลหลายค่าไว้ในตัวแปรเดียว 

ตัวอย่างเช่น รายชื่อพื้นที่ที่เราต้องการวิเคราะห์

In [2]:
areas = ["Bangkok", "Chiang Mai", "Khon Kaen", "Songkhla"] 
areas

['Bangkok', 'Chiang Mai', 'Khon Kaen', 'Songkhla']

เราสามารถเข้าถึงข้อมูลใน `list` ได้ด้วย index 

หมายเหตุ : อย่าลืมว่า index ของ Python เริ่มจาก 0

In [3]:
areas[0]

'Bangkok'

`list` เหมาะกับข้อมูลหนึ่งชุด เช่น 
- รายชื่อจังหวัด 
- รายชื่อสินค้า 
- รายชื่อผู้เข้าร่วมอบรม 
- คะแนนของผู้ตอบแบบสำรวจ 

แต่เมื่อข้อมูลเริ่มมีหลายเรื่องที่สัมพันธ์กัน `list` อย่างเดียวจะเริ่มจัดการยากขึ้น

## 2. ข้อจำกัดของ list เมื่อข้อมูลเริ่มมีหลาย column 
สมมติว่าเรามีข้อมูลผู้ตอบแบบสำรวจ 5 คน 

แต่ละคนมีข้อมูลหลายอย่าง เช่น 
- รหัสผู้ตอบ 
- พื้นที่ 
- อายุ 
- คะแนนความต้องการความช่วยเหลือ 
- สถานะการสำรวจ 

ถ้าใช้ `list` เราอาจต้องเก็บข้อมูลแยกกันหลายตัวแปร

In [4]:
respondent_ids = [1, 2, 3, 4, 5] 

areas = ["Bangkok", "Chiang Mai", "Bangkok", "Khon Kaen", "Songkhla"] 

ages = [34, 52, 41, 29, 63] 

need_scores = [4.2, 3.8, 4.7, 2.9, 3.5] 

statuses = ["Completed", "Completed", "Verified", "Draft", "Completed"]

ข้อมูลเหล่านี้สัมพันธ์กันด้วยตำแหน่ง index 

เช่น index 0 ของทุก list คือข้อมูลของผู้ตอบคนแรก 
- `respondent_ids[0]` 
- `areas[0]` 
- `ages[0]` 
- `need_scores[0]` 
- `statuses[0]`

In [5]:
print(respondent_ids[0])

1

In [6]:
print(areas[0])

Bangkok

In [7]:
print(ages[0])

34

In [8]:
print(need_scores[0])

4.2

In [9]:
print(statuses[0])

Completed

ปัญหาคือ ถ้าข้อมูลมีหลาย `list` มากขึ้น เราต้องจำเองว่า `list` แต่ละตัวสัมพันธ์กันอย่างไร 

ถ้าลบหรือเรียงข้อมูลผิดเพียง `list` เดียว ข้อมูลของแต่ละคนอาจคลาดเคลื่อนได้ 

นี่คือข้อจำกัดสำคัญของการใช้ `list` เพื่อเก็บข้อมูลที่มีลักษณะเป็นตาราง

## 3. จาก list สู่ pandas Series 

ก่อนใช้ `Series` และ `DataFrame` เราต้อง import library `pandas` 

โดยทั่วไปนิยม import pandas ด้วยชื่อย่อว่า `pd`

In [10]:
import pandas as pd

`Series` คือ data structure หนึ่งมิติของ pandas 

ให้มองว่า `Series` คล้ายกับ `list` ที่มี index และมีความสามารถเพิ่มเติมสำหรับงานข้อมูล

In [11]:
need_scores_series = pd.Series([4.2, 3.8, 4.7, 2.9, 3.5]) 
need_scores_series

0    4.2
1    3.8
2    4.7
3    2.9
4    3.5
dtype: float64

จากผลลัพธ์จะเห็นว่า `Series` มี 2 ส่วนหลัก 
- index อยู่ด้านซ้าย 
- value อยู่ด้านขวา 

ถ้าเราไม่ได้กำหนด index เอง pandas จะสร้าง index เริ่มจาก 0 ให้อัตโนมัติ

## 4. Series ต่างจาก list อย่างไร 
`list` และ `Series` ดูคล้ายกัน เพราะเป็นข้อมูลหนึ่งมิติ 

แต่ `Series` มีความสามารถที่เหมาะกับงานข้อมูลมากกว่า เช่น สามารถคำนวณกับค่าทั้งชุดได้ทันที

In [12]:
need_scores_list = [4.2, 3.8, 4.7, 2.9, 3.5] 
need_scores_list

[4.2, 3.8, 4.7, 2.9, 3.5]

In [13]:
need_scores_series = pd.Series(need_scores_list) 
need_scores_series

0    4.2
1    3.8
2    4.7
3    2.9
4    3.5
dtype: float64

ตัวอย่างเช่น ถ้าต้องการบวกคะแนนทุกค่าเพิ่มอีก 0.5 

ถ้าเป็น `Series` สามารถเขียนได้โดยตรง

In [14]:
need_scores_series + 0.5

0    4.7
1    4.3
2    5.2
3    3.4
4    4.0
dtype: float64

แต่ถ้าเป็น `list` ธรรมดา เรามักต้องใช้ loop

In [15]:
new_scores = [] 
for score in need_scores_list: 
    new_scores.append(score + 0.5) 

new_scores

[4.7, 4.3, 5.2, 3.4, 4.0]

ดังนั้น `Series` จึงเหมาะกว่าเมื่อเราต้องการทำงานกับข้อมูลทั้งชุด เช่น 
- คำนวณกับทุกค่า 
- เปรียบเทียบทุกค่า 
- สร้างเงื่อนไขกับทุกค่า 
- ใช้ต่อเป็น column ใน DataFrame

## 5. การใช้ condition กับ Series 
เราได้เรียนการใช้ condition กับค่าหนึ่งค่า เช่น

In [16]:
score = 4.2

if score >= 4.0: 
    print("High") 
else: 
    print("Normal")

High

แต่เมื่อใช้ `Series` เราสามารถเปรียบเทียบค่าทั้งชุดได้ในคำสั่งเดียว

In [17]:
need_scores_series >= 4.0

0     True
1    False
2     True
3    False
4    False
dtype: bool

ผลลัพธ์ที่ได้คือ `Series` ของค่า `True` และ `False` 

ค่านี้บอกว่าแต่ละแถวเข้าเงื่อนไขหรือไม่ 

แนวคิดนี้จะสำคัญมากเมื่อนำไปใช้กรองข้อมูลใน DataFrame

## 6. ทบทวน dictionary 
`dictionary` ใช้เก็บข้อมูลแบบ key-value 

ตัวอย่างเช่น ข้อมูลของผู้ตอบแบบสำรวจหนึ่งคน

In [18]:
respondent = { 
    "respondent_id": 1, 
    "area": "Bangkok", 
    "age": 34, 
    "need_score": 4.2, 
    "status": "Completed" } 
respondent

{'respondent_id': 1,
 'area': 'Bangkok',
 'age': 34,
 'need_score': 4.2,
 'status': 'Completed'}

เราสามารถเข้าถึงข้อมูลใน dictionary ด้วย key

In [19]:
respondent["area"]

'Bangkok'

ถ้ามีข้อมูลหลายคน เราอาจใช้ dictionary ที่ value เป็น list 

ลักษณะนี้เริ่มคล้ายกับตารางข้อมูล

In [20]:
survey_data = { 
    "respondent_id": [1, 2, 3, 4, 5], 
    "area": ["Bangkok", "Chiang Mai", "Bangkok", "Khon Kaen", "Songkhla"], 
    "age": [34, 52, 41, 29, 63], 
    "need_score": [4.2, 3.8, 4.7, 2.9, 3.5], 
    "status": ["Completed", "Completed", "Verified", "Draft", "Completed"] } 
survey_data

{'respondent_id': [1, 2, 3, 4, 5],
 'area': ['Bangkok', 'Chiang Mai', 'Bangkok', 'Khon Kaen', 'Songkhla'],
 'age': [34, 52, 41, 29, 63],
 'need_score': [4.2, 3.8, 4.7, 2.9, 3.5],
 'status': ['Completed', 'Completed', 'Verified', 'Draft', 'Completed']}

dictionary แบบนี้มีโครงสร้างที่ดีขึ้นกว่า list หลายตัว เพราะมีชื่อ field หรือชื่อ column ชัดเจน 

แต่ถ้าต้องการเลือกแถว กรองข้อมูล หรือคำนวณกับ column หลาย ๆ ตัว dictionary ยังไม่สะดวกเท่า DataFrame

## 7. จาก dictionary สู่ pandas DataFrame 
เราสามารถแปลง dictionary ให้เป็น DataFrame ได้ด้วย `pd.DataFrame()`

In [21]:
df = pd.DataFrame(survey_data) 
df

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
3              4   Khon Kaen   29         2.9      Draft
4              5    Songkhla   63         3.5  Completed

ในตัวอย่างนี้ 
- key ของ dictionary กลายเป็นชื่อ column 
- list ที่อยู่ในแต่ละ key กลายเป็นข้อมูลใน column 
- แต่ละตำแหน่งของ list กลายเป็นข้อมูลแต่ละ row 

ตอนนี้ข้อมูลของเราอยู่ในรูปแบบตารางแล้ว

## 8. DataFrame คืออะไร 
`DataFrame` คือ data structure แบบ 2 มิติของ pandas 

ให้มองว่า DataFrame คล้ายกับตารางใน Excel 

DataFrame ประกอบด้วย 
- row หรือแถว 
- column หรือคอลัมน์ 
- index หรือป้ายกำกับของแถว 
- value หรือค่าข้อมูลในแต่ละช่อง

## 9. เปรียบเทียบ DataFrame กับ Excel 
| แนวคิด | Excel | pandas DataFrame | 
|---|---|---| 
| ตารางข้อมูล | Worksheet หรือ Table | DataFrame | 
| แถว | Row | Row | 
| คอลัมน์ | Column | Column | 
| หัวตาราง | Header | Column name | 
| เลขแถว | Row number | Index | 
| ช่องข้อมูล | Cell | Value | 
| เลือกคอลัมน์ | คลิกหัวคอลัมน์ | `df["column_name"]` | 
| เลือกแถว | คลิกเลขแถว | `.loc` หรือ `.iloc` | 
| กรองข้อมูล | Filter | Boolean selection | 

DataFrame ไม่ได้มาแทน Excel ทั้งหมด แต่ช่วยให้งานข้อมูลที่ต้องทำซ้ำ ตรวจสอบย้อนหลัง หรือจัดการข้อมูลจำนวนมาก ทำได้เป็นระบบมากขึ้น

## 10. DataFrame เป็นขั้นกว่าของ dictionary อย่างไร 
dictionary ช่วยให้เราเก็บข้อมูลเป็นกลุ่มได้ 

แต่ DataFrame เพิ่มความสามารถที่เหมาะกับงานวิเคราะห์ข้อมูลมากขึ้น เช่น 
- เลือก column ได้ง่าย 
- เลือก row ได้ง่าย 
- เลือกข้อมูลจากตำแหน่งหรือชื่อได้ 
- กรองข้อมูลด้วยเงื่อนไขได้ 
- คำนวณกับข้อมูลทั้ง column ได้ 
- สร้าง column ใหม่ได้ 
- ใช้ function กับข้อมูลได้ 
- ใช้ต่อยอดไปสู่การนำเข้าไฟล์ การตรวจสอบข้อมูล และการทำความสะอาดข้อมูลได้

## 11. องค์ประกอบพื้นฐานของ DataFrame 
ลองดู DataFrame ที่เราสร้างขึ้นอีกครั้ง

In [22]:
df

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
3              4   Khon Kaen   29         2.9      Draft
4              5    Songkhla   63         3.5  Completed

ใน DataFrame นี้ 
- แต่ละ row แทนผู้ตอบแบบสำรวจ 1 คน 
- แต่ละ column แทนข้อมูล 1 ประเภท 
- index อยู่ด้านซ้ายสุด 
- value คือค่าข้อมูลในแต่ละช่อง 

ตัวอย่างเช่น row แรกคือข้อมูลของผู้ตอบหมายเลข 1

## 12. การเลือก column เดียวจาก DataFrame

การเลือก column เดียวใช้รูปแบบ

```python
df["column_name"]
```

ผลลัพธ์ที่ได้จะเป็น Series

In [23]:
df["area"]

0       Bangkok
1    Chiang Mai
2       Bangkok
3     Khon Kaen
4      Songkhla
Name: area, dtype: str

In [24]:
type(df["area"])

pandas.Series

เมื่อเลือก column เดียว ผลลัพธ์คือ `Series` 

ดังนั้น `Series` อาจมองได้ว่าเป็น column หนึ่ง column ที่ถูกดึงออกมาจาก DataFrame

## 13. การเลือกหลาย column จาก DataFrame

ถ้าต้องการเลือกหลาย column ให้ใส่ชื่อ column เป็น list

รูปแบบคือ

```python
df[["column_1", "column_2"]]
```

ผลลัพธ์ที่ได้จะเป็น DataFrame

In [25]:
df[["area", "need_score"]]

         area  need_score
0     Bangkok         4.2
1  Chiang Mai         3.8
2     Bangkok         4.7
3   Khon Kaen         2.9
4    Songkhla         3.5

In [26]:
type(df[["area", "need_score"]])

pandas.DataFrame

สรุปความแตกต่างสำคัญ

- เลือก column เดียว ได้ `Series`
- เลือกหลาย column ได้ `DataFrame`

เรื่องนี้สำคัญมาก เพราะคำสั่งบางอย่างใช้กับ `Series` และ `DataFrame` แตกต่างกัน

## 14. การเลือกข้อมูลด้วย iloc `.iloc` 

ใช้เลือกข้อมูลจากตำแหน่งของ row และ column 

คำว่า `iloc` ให้จำว่าเกี่ยวกับ integer location หรือตำแหน่งที่เป็นตัวเลข เหมาะเมื่อเราต้องการเลือกข้อมูลตามลำดับตำแหน่ง

In [27]:
df

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
3              4   Khon Kaen   29         2.9      Draft
4              5    Songkhla   63         3.5  Completed

เลือก row แรกของ DataFrame

In [28]:
df.iloc[0]

respondent_id            1
area               Bangkok
age                     34
need_score             4.2
status           Completed
Name: 0, dtype: object

เลือก row ที่ 1 ถึง row ที่ 3 ตามตำแหน่ง 

หมายเหตุ: อย่าลืมว่าการ slice ใน Python จะไม่รวมตำแหน่งท้ายสุด

In [29]:
df.iloc[0:3]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

เลือกค่าที่อยู่ row แรก และ column ที่สอง 

ในที่นี้ row แรกคือตำแหน่ง 0 และ column ที่สองคือตำแหน่ง 1

In [30]:
df.iloc[0, 1]

'Bangkok'

เลือกหลาย row และหลาย column ด้วย `.iloc` 

ตัวอย่างนี้เลือก 3 row แรก และ 2 column แรก

In [31]:
df.iloc[0:3, 0:2]

   respondent_id        area
0              1     Bangkok
1              2  Chiang Mai
2              3     Bangkok

## 15. การเลือกข้อมูลด้วย loc 
`.loc` ใช้เลือกข้อมูลจาก label หรือชื่อ 

โดยทั่วไปมักใช้กับ 
- ชื่อ index 
- ชื่อ column 

ใน DataFrame ที่ยังไม่ได้ตั้ง index เอง index จะเป็นตัวเลข 0, 1, 2, ...

In [32]:
df

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
3              4   Khon Kaen   29         2.9      Draft
4              5    Songkhla   63         3.5  Completed

เลือก row ที่มี index เป็น 0

In [33]:
df.loc[0]

respondent_id            1
area               Bangkok
age                     34
need_score             4.2
status           Completed
Name: 0, dtype: object

เลือกค่าจาก index 0 และ column `area`

In [34]:
df.loc[0, "area"]

'Bangkok'

เลือกทุก row แต่เลือกเฉพาะ column `area` และ `need_score`

In [35]:
df.loc[:, ["area", "need_score"]]

         area  need_score
0     Bangkok         4.2
1  Chiang Mai         3.8
2     Bangkok         4.7
3   Khon Kaen         2.9
4    Songkhla         3.5

## 16. ความแตกต่างระหว่าง loc และ iloc 
| คำสั่ง | ใช้เลือกจาก | ตัวอย่าง | 
|---|---|---| 
| `.iloc` | ตำแหน่งของ row/column | row ที่ 0, column ที่ 1 | 
| `.loc` | label หรือชื่อ | index 0, column `"area"` | 

จำง่าย ๆ คือ 
- `.iloc` ใช้ตำแหน่งที่เป็นตัวเลข (indicator location) 
- `.loc` ใช้ชื่อหรือ label

## 17. การเลือกข้อมูลแบบมีเงื่อนไข 
จากวันที่ 1 เราเคยเขียน condition กับค่าหนึ่งค่า เช่น

In [36]:
score = 4.2 

score >= 4.0

True

เมื่อนำแนวคิดนี้มาใช้กับ DataFrame เราสามารถเขียน condition กับทั้ง column ได้

In [37]:
df["need_score"] >= 4.0

0     True
1    False
2     True
3    False
4    False
Name: need_score, dtype: bool

ผลลัพธ์ที่ได้คือชุดของค่า `True` และ `False` 

เราสามารถนำผลลัพธ์นี้ไปใช้กรอง DataFrame ได้

In [38]:
df[df["need_score"] >= 4.0]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed
2              3  Bangkok   41         4.7   Verified

ตัวอย่างนี้หมายความว่า 

เลือกเฉพาะ row ที่ column `need_score` มีค่ามากกว่าหรือเท่ากับ 4.0 

แนวคิดนี้คล้ายกับการ Filter ใน Excel แต่เขียนเป็น code

## 18. การเลือกข้อมูลด้วยเงื่อนไขข้อความ 
เราสามารถกรองข้อมูลจาก column ที่เป็นข้อความได้เช่นกัน 

ตัวอย่างเช่น เลือกเฉพาะผู้ตอบที่อยู่ในพื้นที่ Bangkok

In [39]:
df[df["area"] == "Bangkok"]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed
2              3  Bangkok   41         4.7   Verified

เลือกเฉพาะผู้ตอบที่มีสถานะ Completed

In [40]:
df[df["status"] == "Completed"]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
4              5    Songkhla   63         3.5  Completed

## 19. การใช้หลายเงื่อนไข 
ถ้ามีมากกว่าหนึ่งเงื่อนไข สามารถใช้ operator ต่อไปนี้ 
- `&` หมายถึง และ 
- `|` หมายถึง หรือ 
- `~` หมายถึง ไม่ใช่ 

ข้อสำคัญคือ แต่ละเงื่อนไขควรอยู่ในวงเล็บ

ตัวอย่าง: เลือกผู้ตอบที่มีคะแนนตั้งแต่ 4.0 ขึ้นไป และมีสถานะ Completed

In [41]:
df[(df["need_score"] >= 4.0) & (df["status"] == "Completed")]

   respondent_id     area  age  need_score     status
0              1  Bangkok   34         4.2  Completed

ตัวอย่าง: เลือกผู้ตอบที่อยู่ใน Bangkok หรือ Chiang Mai

In [42]:
df[(df["area"] == "Bangkok") | (df["area"] == "Chiang Mai")]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified

ตัวอย่าง: เลือกผู้ตอบที่ไม่ได้มีสถานะ Draft

In [43]:
df[~(df["status"] == "Draft")]

   respondent_id        area  age  need_score     status
0              1     Bangkok   34         4.2  Completed
1              2  Chiang Mai   52         3.8  Completed
2              3     Bangkok   41         4.7   Verified
4              5    Songkhla   63         3.5  Completed

## 20. การสร้าง column ใหม่จากเงื่อนไข 
เราสามารถสร้าง column ใหม่จากเงื่อนไขได้ 

ตัวอย่างเช่น สร้าง column ชื่อ `is_high_need` 

โดยกำหนดว่า 
- ถ้า `need_score` มากกว่าหรือเท่ากับ 4.0 ให้เป็น `True` 
- ถ้าน้อยกว่า 4.0 ให้เป็น `False`

In [44]:
df["is_high_need"] = df["need_score"] >= 4.0 
df

   respondent_id        area  age  need_score     status  is_high_need
0              1     Bangkok   34         4.2  Completed          True
1              2  Chiang Mai   52         3.8  Completed         False
2              3     Bangkok   41         4.7   Verified          True
3              4   Khon Kaen   29         2.9      Draft         False
4              5    Songkhla   63         3.5  Completed         False

แนวคิดนี้คล้ายกับการสร้าง column ใหม่ใน Excel แล้วใส่สูตรที่ให้ผลลัพธ์เป็น TRUE/FALSE

## 21. การประยุกต์ใช้ if และ function กับ DataFrame 
จากการเรียนเรื่อง function เราสามารถสร้าง function เพื่อจัดกลุ่มคะแนนได้ 

ตัวอย่างเช่น 
- คะแนนตั้งแต่ 4.0 ขึ้นไป = High 
- คะแนนตั้งแต่ 3.0 ถึงน้อยกว่า 4.0 = Medium 
- คะแนนน้อยกว่า 3.0 = Low

In [45]:
def classify_need(score): 
    if score >= 4.0: 
        return "High" 
    elif score >= 3.0: 
        return "Medium" 
    else: 
        return "Low"

ทดลองใช้ function กับค่าหนึ่งค่าก่อน

In [46]:
classify_need(4.2)

'High'

เมื่อต้องการนำ function ไปใช้กับทั้ง column สามารถใช้ `.apply()` 

ในที่นี้เราจะนำ function `classify_need()` ไปใช้กับ column `need_score`

In [47]:
df["need_level"] = df["need_score"].apply(classify_need) 
df

,respondent_id,area,age,need_score,status,is_high_need,need_level
0,1,Bangkok,34,4.2,Completed,True,High
1,2,Chiang Mai,52,3.8,Completed,False,Medium
2,3,Bangkok,41,4.7,Verified,True,High
3,4,Khon Kaen,29,2.9,Draft,False,Low
4,5,Songkhla,63,3.5,Completed,False,Medium

จุดสำคัญคือ เรานำความรู้เรื่อง `if` และ function จากวันที่ 1 มาใช้กับข้อมูลใน DataFrame 

สิ่งนี้ทำให้เราสามารถสร้างกฎหรือ logic สำหรับจัดกลุ่มข้อมูลได้อย่างเป็นระบบ

## 22. การประยุกต์ใช้ loop กับ DataFrame 
loop ยังสามารถใช้ร่วมกับ DataFrame ได้ 

ตัวอย่างแรก คือ loop ผ่านรายชื่อ column ที่ต้องการแสดง

In [48]:
columns_to_show = ["area", "age", "need_score"] 

for column in columns_to_show: 
    print("Column:", column) 
    print(df[column]) 
    print()

Column: area
0       Bangkok
1    Chiang Mai
2       Bangkok
3     Khon Kaen
4      Songkhla
Name: area, dtype: str

Column: age
0    34
1    52
2    41
3    29
4    63
Name: age, dtype: int64

Column: need_score
0    4.2
1    3.8
2    4.7
3    2.9
4    3.5
Name: need_score, dtype: float64

ตัวอย่างต่อไป คือ loop ผ่านแต่ละ row ด้วย `.iterrows()`

วิธีนี้ช่วยให้เห็นว่าแต่ละ row ใน DataFrame สามารถถูกอ่านออกมาทีละแถวได้

In [49]:
for index, row in df.iterrows(): 
    print("Respondent:", row["respondent_id"]) 
    print("Area:", row["area"]) 
    print("Need score:", row["need_score"]) 
    print("Need level:", row["need_level"]) 
    print("---")

Respondent: 1
Area: Bangkok
Need score: 4.2
Need level: High
---
Respondent: 2
Area: Chiang Mai
Need score: 3.8
Need level: Medium
---
Respondent: 3
Area: Bangkok
Need score: 4.7
Need level: High
---
Respondent: 4
Area: Khon Kaen
Need score: 2.9
Need level: Low
---
Respondent: 5
Area: Songkhla
Need score: 3.5
Need level: Medium
---

อย่างไรก็ตาม ใน pandas เราไม่จำเป็นต้องใช้ loop เสมอไป 

หลายกรณี pandas สามารถทำงานกับทั้ง column ได้โดยตรง ซึ่งมักจะสั้นกว่า อ่านง่ายกว่า และเหมาะกับงานข้อมูลมากกว่า 

ตัวอย่างเช่น การสร้าง column `is_high_need` ก่อนหน้านี้ ไม่จำเป็นต้องเขียน loop เอง

# แบบฝึกหัดท้ายบท

ในแบบฝึกหัดนี้ เราจะใช้ข้อมูลสมมติจากการสำรวจครัวเรือนในพื้นที่ต่าง ๆ ข้อมูลประกอบด้วย 
- `respondent_id` รหัสผู้ตอบแบบสำรวจ 
- `province` จังหวัด 
- `age` อายุของผู้ตอบ 
- `household_size` จำนวนสมาชิกในครัวเรือน 
- `monthly_income` รายได้ต่อเดือนของครัวเรือน 
- `debt_amount` จำนวนหนี้สิน 
- `need_score` คะแนนความต้องการความช่วยเหลือ 
- `status` สถานะของแบบสำรวจ

## แบบฝึกหัดที่ 1: สร้าง DataFrame จากข้อมูลแบบสำรวจ 
ให้สร้าง DataFrame ชื่อ `survey_df` จาก dictionary ต่อไปนี้ 

```python 
survey_data = { 
    "respondent_id": [1, 2, 3, 4, 5, 6, 7, 8], 
    "province": ["Bangkok", "Chiang Mai", "Khon Kaen", "Songkhla", "Bangkok", "Khon Kaen", "Chiang Mai", "Songkhla"], "age": [34, 52, 41, 29, 63, 47, 38, 55], 
    "household_size": [3, 5, 4, 2, 6, 4, 3, 5], 
    "monthly_income": [28000, 15000, 12000, 22000, 9000, 11000, 30000, 8000], 
    "debt_amount": [50000, 120000, 80000, 30000, 150000, 95000, 20000, 130000], 
    "need_score": [3.5, 4.2, 4.7, 2.8, 4.9, 4.1, 2.5, 4.6], 
    "status": ["Completed", "Completed", "Verified", "Draft", "Completed", "Verified", "Completed", "Draft"] }
```

จากนั้นแสดงผล `survey_df`

In [50]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 2: สร้าง Series จาก column 
จาก `survey_df` ให้เลือก column `need_score` แล้วเก็บไว้ในตัวแปรชื่อ `need_score_series` 

จากนั้นให้เขียน code เพื่อตอบคำถามต่อไปนี้ 
1. `need_score_series` เป็น object ชนิดใด 
2. เมื่อนำ `need_score_series >= 4.0` จะได้ผลลัพธ์อย่างไร 
3. ผลลัพธ์ที่ได้สามารถนำไปใช้แก้ปัญหาอะไรได้บ้าง

In [51]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 3: เลือกข้อมูลที่จำเป็นสำหรับการวิเคราะห์ 
หน่วยงานต้องการดูข้อมูลเฉพาะ column ที่เกี่ยวข้องกับการประเมินความเปราะบางของครัวเรือน 

ให้เลือกเฉพาะ column ต่อไปนี้จาก `survey_df` 
- `respondent_id` 
- `province` 
- `monthly_income` 
- `debt_amount` 
- `need_score` 

แล้วเก็บไว้ในตัวแปรชื่อ `vulnerability_df`

In [52]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 4: เลือกข้อมูลด้วย iloc 
เจ้าหน้าที่ต้องการตรวจสอบข้อมูล 3 แถวแรกของแบบสำรวจตามลำดับตำแหน่งของข้อมูล 

ให้ใช้ `.iloc` เพื่อเลือกข้อมูล 3 แถวแรกจาก `survey_df` 

จากนั้นให้เลือกค่าที่อยู่ใน 
- row ตำแหน่งที่ 0 
- column ตำแหน่งที่ 1 

และอธิบายว่าค่านั้นคือข้อมูลอะไร

In [53]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 5: เลือกข้อมูลด้วย loc 
ให้ใช้ `.loc` เพื่อตอบคำถามต่อไปนี้ 
1. เลือกข้อมูลของ respondent ที่อยู่ใน index 2 
2. เลือกค่า `province` ของ respondent ที่อยู่ใน index 2 
3. เลือกทุก row แต่แสดงเฉพาะ column `respondent_id`, `province` และ `need_score`

In [54]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 6: ค้นหาครัวเรือนที่ควรได้รับการติดตาม 
หน่วยงานต้องการค้นหาครัวเรือนที่มีคะแนนความต้องการความช่วยเหลือสูง 

ให้เลือกเฉพาะ row ที่มี `need_score` มากกว่าหรือเท่ากับ 4.0 

แล้วเก็บผลลัพธ์ไว้ในตัวแปรชื่อ `high_need_df`

In [55]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 7: ใช้หลายเงื่อนไขเพื่อคัดกรองกลุ่มเป้าหมาย 
หน่วยงานต้องการคัดกรองครัวเรือนที่มีความเปราะบางสูง โดยใช้เงื่อนไขดังนี้ 
- `need_score` มากกว่าหรือเท่ากับ 4.0 
- และ `monthly_income` น้อยกว่า 15000 

ให้เลือกข้อมูลที่เข้าเงื่อนไขทั้งสองข้อจาก `survey_df` 

แล้วเก็บผลลัพธ์ไว้ในตัวแปรชื่อ `target_households`

In [56]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 8: สร้าง column ใหม่จากการคำนวณและเงื่อนไข

ให้สร้าง column ใหม่ 2 column ใน `survey_df`

### 1. `debt_to_income_ratio`

คำนวณจาก

```python
debt_amount / monthly_income
```

### 2. `is_low_income`

กำหนดให้

ถ้า monthly_income น้อยกว่า 15000 ให้เป็น True
ถ้า monthly_income มากกว่าหรือเท่ากับ 15000 ให้เป็น False

หลังจากสร้าง column แล้ว ให้แสดงผล `survey_df`

In [57]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 9: ใช้ function และ apply เพื่อจัดกลุ่มระดับความต้องการ 
ให้สร้าง function ชื่อ `classify_need_level()` เพื่อจัดกลุ่ม `need_score` ตามเงื่อนไขต่อไปนี้ 
- ถ้า `need_score` มากกว่าหรือเท่ากับ 4.5 ให้ return `"Very High"` 
- ถ้า `need_score` มากกว่าหรือเท่ากับ 4.0 แต่น้อยกว่า 4.5 ให้ return `"High"` 
- ถ้า `need_score` มากกว่าหรือเท่ากับ 3.0 แต่น้อยกว่า 4.0 ให้ return `"Medium"` 
- ถ้า `need_score` น้อยกว่า 3.0 ให้ return `"Low"` 

จากนั้นใช้ `.apply()` เพื่อสร้าง column ใหม่ชื่อ `need_level`

In [58]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 10: ใช้ loop เพื่อสร้างข้อความสรุปสำหรับติดตามงาน

ให้ใช้ loop ผ่านแต่ละ row ของ `survey_df` แล้วพิมพ์ข้อความสรุปสำหรับเจ้าหน้าที่ติดตามงาน

รูปแบบข้อความที่ต้องการคือ

```text
Respondent 1 จาก Bangkok มี need level ระดับ Medium.
Respondent 2 จาก Chiang Mai มี need level ระดับ High.
```

ให้ใช้ข้อมูลจาก column ต่อไปนี้

`respondent_id`

`province`

`need_level`