# บทที่ 9: การตรวจสอบคุณภาพข้อมูลเบื้องต้น

หลังจากนำเข้าข้อมูลแล้ว ขั้นตอนถัดไปคือการตรวจสอบว่า DataFrame ที่ได้มีคุณภาพเพียงพอสำหรับการวิเคราะห์หรือไม่

จุดสำคัญของบทนี้คือ

>อ่านข้อมูลเข้ามาแล้ว ต้องตรวจสอบก่อนว่า “ข้อมูลน่าเชื่อถือพอสำหรับการวิเคราะห์หรือไม่”

## ผลการเรียนรู้ที่คาดหวัง 
เมื่อเรียนจบบทนี้ ผู้เรียนจะสามารถ 
1. อธิบายความสำคัญของการตรวจสอบข้อมูลหลังนำเข้าได้ 
2. ใช้ `head()`, `tail()` และ `sample()` เพื่อดูตัวอย่างข้อมูลได้ 
3. ใช้ `shape`, `columns` และ `index` เพื่อตรวจสอบโครงสร้างของ DataFrame ได้ 
4. ใช้ `dtypes` และ `info()` เพื่อตรวจสอบชนิดข้อมูลและจำนวนค่าที่ไม่ว่างได้ 
5. อธิบายความหมายของค่าสถิติพื้นฐาน เช่น `count`, `mean`, `std`, `min`, `median`, `percentile` และ `max` ได้ 
6. ใช้ `describe()` เพื่อดูค่าสถิติเบื้องต้นของข้อมูลตัวเลขได้ 
7. ใช้ `isna()`, `isna().sum()` และ `isna().mean()` เพื่อตรวจสอบค่าว่างได้ 
8. ใช้ `duplicated()` และ `duplicated().sum()` เพื่อตรวจสอบข้อมูลซ้ำได้ 
9. ใช้ `value_counts()`, `unique()` และ `nunique()` เพื่อตรวจสอบข้อมูลเชิงหมวดหมู่ได้ 
10. ตรวจสอบค่าผิดปกติอย่างง่าย เช่น อายุผิดช่วง หรือวันที่ผิดปกติได้ 
11. สรุปประเด็นด้านคุณภาพข้อมูลที่ควรส่งต่อไปยังขั้นตอน data cleaning ได้ 
12. ออกแบบ function สำหรับตรวจสอบข้อมูลเบื้องต้นในแบบฝึกหัดท้ายบทได้

## ลำดับเนื้อหา 
บทเรียนนี้ประกอบด้วยหัวข้อต่อไปนี้ 
1. เตรียม pandas และนำเข้าข้อมูลตัวอย่าง 
2. ทบทวนแนวคิด EDA และ Data Quality Check 
3. ดูตัวอย่างข้อมูลด้วย `head()`, `tail()` และ `sample()` 
4. ตรวจสอบขนาดข้อมูลด้วย `shape` 
5. ตรวจสอบชื่อ column ด้วย `columns` 
6. ตรวจสอบชนิดข้อมูลด้วย `dtypes` 
7. ดูภาพรวม DataFrame ด้วย `info()` 
8. อธิบายค่าสถิติพื้นฐานสำหรับการตรวจสอบข้อมูล 
9. สรุปข้อมูลตัวเลขด้วย `describe()` 
10. ตรวจสอบช่วงค่าของข้อมูลตัวเลข 
11. ตรวจสอบค่าว่างด้วย `isna()` 
12. ตรวจสอบสัดส่วนค่าว่าง 
13. ตรวจสอบข้อมูลซ้ำด้วย `duplicated()` 
14. ตรวจสอบข้อมูลเชิงหมวดหมู่ด้วย `value_counts()`, `unique()` และ `nunique()` 
15. ตรวจสอบข้อมูลวันที่ 
16. สร้างตารางสรุปคุณภาพข้อมูลเบื้องต้น 
17. สร้าง quality checklist 
18. แบบฝึกหัดท้ายบท

## 1. เตรียม pandas 
เริ่มจาก import pandas ด้วยชื่อย่อ `pd`

In [1]:
import pandas as pd

## 2. กำหนด path ของไฟล์

ในบทนี้เราจะใช้ไฟล์ CSV ตัวอย่างชื่อ

```python
"msdhs_ops_mso_logbook.csv"
```

เราจะเก็บชื่อไฟล์ไว้ในตัวแปร csv_file

In [2]:
csv_file = "msdhs_ops_mso_logbook.csv"

## 3. นำเข้าข้อมูลตัวอย่าง 
เนื้อหาในบทนี้เน้นเรื่องการตรวจสอบข้อมูล เราจะอ่านไฟล์ด้วย `parameter` ที่เหมาะสม

เราจะเลือกเฉพาะ column ที่ใช้ฝึกตรวจสอบคุณภาพข้อมูล เช่น 
- วันที่ 
- รหัส 
- จังหวัด 
- อายุ 
- เพศ 
- ระดับการศึกษา 
- อาชีพ 
- ประเภทกลุ่มเป้าหมาย

In [3]:
mso_usecols = [ 
    "วันที่แก้ไขข้อมูลล่าสุด", 
    "รหัสครัวเรือน", 
    "รหัสประจำบ้าน", 
    "วันที่สร้างครัวเรือน", 
    "จังหวัด", 
    "อายุ", 
    "เพศ", 
    "ระดับการศึกษา", 
    "อาชีพหลัก", 
    "ประเภทกลุ่มเป้าหมาย", 
    "รหัส cm", 
    "หน่วยงานของ cm" 
] 

mso_dtype = { 
    "รหัสครัวเรือน": "string", 
    "รหัสประจำบ้าน": "string", 
    "รหัส cm": "string" } 
    
mso_df = pd.read_csv( 
    csv_file, 
    encoding="utf-8-sig", 
    usecols=mso_usecols, 
    dtype=mso_dtype, 
    parse_dates=["วันที่แก้ไขข้อมูลล่าสุด", "วันที่สร้างครัวเรือน"] 
) 

mso_df

,วันที่แก้ไขข้อมูลล่าสุด,รหัสครัวเรือน,รหัสประจำบ้าน,วันที่สร้างครัวเรือน,อายุ,เพศ,จังหวัด,ระดับการศึกษา,อาชีพหลัก,ประเภทกลุ่มเป้าหมาย,รหัส cm,หน่วยงานของ cm
0,2023-06-19 13:40:56.585,648ff7d6b64d06b6b0dc7f02,<NA>,2023-06-19 13:38:14.881,3,หญิง,อุดรธานี,ไม่ได้เรียนหนังสือ,เกษตรกรรม (พืช ปศุสัตว์ ประมง),เด็กเล็ก,cm410011,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
1,2022-07-17 18:56:10.147,62d3f7a6d6f101550054198b,70040223124,2022-07-17 18:51:02.889,55,หญิง,ราชบุรี,ไม่ได้เรียนหนังสือ,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm700018,ศูนย์คุ้มครองคนไร้ที่พึ่งราชบุรี
2,2024-01-25 13:34:46.941,62a05c9df5674ecdd3805787,<NA>,2022-08-06 15:23:57.850,33,หญิง,หนองคาย,มัธยมศึกษาตอนต้น,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm430010,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
3,2024-03-22 14:12:39.290,62908e378fa67bf5ad7d5555,<NA>,2022-05-27 15:39:19.197,5,หญิง,อุบลราชธานี,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm340009,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
4,2023-03-15 09:27:11.763,6319b26ca3a37508384e36fc,<NA>,2022-08-09 16:14:20.652,3,ชาย,นครราชสีมา,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm300020,ศูนย์บริการคนพิการ จังหวัดนครราชสีมา
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-29 14:33:32.178,688878eaa933a405b21cc136,<NA>,2025-07-29 14:31:54.610,59,NaN,ชัยภูมิ,NaN,เกษตรกรรม (พืช ปศุสัตว์ ประมง),วัยผู้ใหญ่/วัยแรงงาน,cm360060,ศูนย์คุ้มครองคนไร้ที่พึ่ง จ.ชัยภูมิ
96,2023-03-17 19:08:15.489,628b008c8fa67bf5ad7d221b,<NA>,2022-05-23 10:33:32.270,79,NaN,มหาสารคาม,NaN,NaN,ผู้สูงอายุ,cm440005,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
97,2023-05-01 09:19:26.395,63b6325b2617b2b7aa04dc0b,25120251099,2023-05-01 09:13:47.520,51,หญิง,สระแก้ว,ประถมศึกษา,รับจ้างทั่วไป,วัยผู้ใหญ่/วัยแรงงาน,cm270001,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
98,2025-01-04 14:05:25.955,63e1d0d92617b2b7aa06096d,40160104483,2023-07-02 11:17:29.369,81,ชาย,ขอนแก่น,ไม่ได้เรียนหนังสือ,NaN,ผู้สูงอายุ,cm400016,ศูนย์เรียนรู้การพัฒนาสตรีและครอบครัวรัตนาภา จั...
99,2025-03-18 15:17:33.047,67d92537a933a405b21c2e77,<NA>,2025-03-18 14:48:07.735,70,หญิง,นครราชสีมา,ประถมศึกษา,เกษตรกรรม (พืช ปศุสัตว์ ประมง),ผู้สูงอายุ,cm300037,บ้านพักเด็กและครอบครัวจังหวัดนครราชสีมา

## 4. ทำไมต้องตรวจสอบข้อมูลหลังนำเข้า
หลังจากอ่านไฟล์สำเร็จ เราควรตรวจสอบข้อมูลก่อนนำไปวิเคราะห์ 

ตัวอย่างปัญหาที่อาจพบหลังนำเข้าไฟล์ ได้แก่
- pandas อ่านชนิดข้อมูลไม่ตรงกับความหมายจริง 
- วันที่ยังถูกอ่านเป็นข้อความ 
- มีค่าว่างใน column สำคัญ 
- มีข้อมูลซ้ำ 
- มีค่าอายุผิดปกติ เช่น ติดลบ หรือมากเกินไป 
- ข้อมูลหมวดหมู่สะกดไม่สอดคล้องกัน 
- column ที่ควรเป็นรหัสถูกอ่านเป็นตัวเลข 
- บาง column มีค่าว่างมากเกินไปจนไม่เหมาะกับการวิเคราะห์

ดังนั้นการตรวจสอบข้อมูลเบื้องต้นจึงเป็นขั้นตอนที่ช่วยให้เรารู้จักข้อมูลก่อนจะเริ่มทำการวิเคราะห์

## 5. EDA คืออะไร 
EDA ย่อมาจาก Exploratory Data Analysis 

EDA หมายถึง การสำรวจข้อมูลเบื้องต้นเพื่อทำความเข้าใจว่า
- DataFrame มีหน้าตาอย่างไร 
- ข้อมูลมีขนาดเท่าไร 
- column แต่ละตัวหมายถึงอะไร 
- ข้อมูลแต่ละ column เป็นตัวเลข ข้อความ วันที่ หรือรหัส 
- มีค่าว่างหรือไม่ 
- มีค่าผิดปกติหรือไม่ 
- ข้อมูลพร้อมสำหรับการวิเคราะห์หรือไม่

EDA จะเน้นการ “ตรวจพบปัญหา” ก่อนที่จะนำข้อมูลไปใช้

## 6. ดูข้อมูลแถวแรกด้วย `head()`
คำสั่ง `head()` ใช้ดูแถวแรก ๆ ของ DataFrame 

โดย default จะแสดง 5 แถวแรก 

เหมาะสำหรับตรวจอย่างรวดเร็วว่า
- ข้อมูลถูกอ่านเข้ามาเป็นตารางหรือไม่ 
- ชื่อ column ถูกต้องหรือไม่ 
- ค่าภาษาไทยแสดงผลปกติหรือไม่ 
- ตัวอย่างข้อมูลดูสมเหตุสมผลหรือไม่

In [4]:
mso_df.head()

,วันที่แก้ไขข้อมูลล่าสุด,รหัสครัวเรือน,รหัสประจำบ้าน,วันที่สร้างครัวเรือน,อายุ,เพศ,จังหวัด,ระดับการศึกษา,อาชีพหลัก,ประเภทกลุ่มเป้าหมาย,รหัส cm,หน่วยงานของ cm
0,2023-06-19 13:40:56.585,648ff7d6b64d06b6b0dc7f02,<NA>,2023-06-19 13:38:14.881,3,หญิง,อุดรธานี,ไม่ได้เรียนหนังสือ,เกษตรกรรม (พืช ปศุสัตว์ ประมง),เด็กเล็ก,cm410011,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
1,2022-07-17 18:56:10.147,62d3f7a6d6f101550054198b,70040223124,2022-07-17 18:51:02.889,55,หญิง,ราชบุรี,ไม่ได้เรียนหนังสือ,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm700018,ศูนย์คุ้มครองคนไร้ที่พึ่งราชบุรี
2,2024-01-25 13:34:46.941,62a05c9df5674ecdd3805787,<NA>,2022-08-06 15:23:57.850,33,หญิง,หนองคาย,มัธยมศึกษาตอนต้น,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm430010,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
3,2024-03-22 14:12:39.290,62908e378fa67bf5ad7d5555,<NA>,2022-05-27 15:39:19.197,5,หญิง,อุบลราชธานี,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm340009,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
4,2023-03-15 09:27:11.763,6319b26ca3a37508384e36fc,<NA>,2022-08-09 16:14:20.652,3,ชาย,นครราชสีมา,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm300020,ศูนย์บริการคนพิการ จังหวัดนครราชสีมา

In [5]:
mso_df.head(10)

,วันที่แก้ไขข้อมูลล่าสุด,รหัสครัวเรือน,รหัสประจำบ้าน,วันที่สร้างครัวเรือน,อายุ,เพศ,จังหวัด,ระดับการศึกษา,อาชีพหลัก,ประเภทกลุ่มเป้าหมาย,รหัส cm,หน่วยงานของ cm
0,2023-06-19 13:40:56.585,648ff7d6b64d06b6b0dc7f02,<NA>,2023-06-19 13:38:14.881,3,หญิง,อุดรธานี,ไม่ได้เรียนหนังสือ,เกษตรกรรม (พืช ปศุสัตว์ ประมง),เด็กเล็ก,cm410011,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
1,2022-07-17 18:56:10.147,62d3f7a6d6f101550054198b,70040223124,2022-07-17 18:51:02.889,55,หญิง,ราชบุรี,ไม่ได้เรียนหนังสือ,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm700018,ศูนย์คุ้มครองคนไร้ที่พึ่งราชบุรี
2,2024-01-25 13:34:46.941,62a05c9df5674ecdd3805787,<NA>,2022-08-06 15:23:57.850,33,หญิง,หนองคาย,มัธยมศึกษาตอนต้น,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm430010,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
3,2024-03-22 14:12:39.290,62908e378fa67bf5ad7d5555,<NA>,2022-05-27 15:39:19.197,5,หญิง,อุบลราชธานี,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm340009,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
4,2023-03-15 09:27:11.763,6319b26ca3a37508384e36fc,<NA>,2022-08-09 16:14:20.652,3,ชาย,นครราชสีมา,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm300020,ศูนย์บริการคนพิการ จังหวัดนครราชสีมา
5,2023-03-16 13:23:07.617,63ad11f0049951d53b429c13,<NA>,2022-12-29 11:05:04.736,39,ชาย,ประจวบคีรีขันธ์,มัธยมศึกษาตอนต้น,ธุรกิจส่วนตัว/ค้าขาย/เจ้าของกิจการ,วัยผู้ใหญ่/วัยแรงงาน,cm770005,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
6,2022-12-22 10:35:26.057,63a3d037cdf0fb5ddc8ba1f9,<NA>,2022-12-22 10:34:15.185,4,หญิง,อุดรธานี,ไม่ได้เรียนหนังสือ,NaN,เด็กเล็ก,cm410006,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
7,2023-01-02 11:34:02.089,63d9eb642617b2b7aa05ea6c,<NA>,2023-01-02 11:32:36.354,68,NaN,นครศรีธรรมราช,NaN,ธุรกิจส่วนตัว/ค้าขาย/เจ้าของกิจการ,ผู้สูงอายุ,cm800045,ศูนย์คุ้มครองคนไร้ที่พึ่ง จ.นครศรีธรรมราช
8,2022-09-22 14:23:42.121,632c086a720e4eb0fded2524,25120211445,2022-09-22 14:02:02.435,90,หญิง,สระแก้ว,ประถมศึกษา,NaN,ผู้สูงอายุ,cm270003,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
9,2022-12-23 10:02:55.712,63a519a7cdf0fb5ddc8bb44a,<NA>,2022-12-23 09:59:51.518,6,หญิง,บุรีรัมย์,ไม่ได้เรียนหนังสือ,NaN,เด็ก,cm310013,บ้านพักเด็กและครอบครัวจังหวัดบุรีรัมย์

## 7. ดูข้อมูลท้ายตารางด้วย `tail()` 
คำสั่ง `tail()` ใช้ดูแถวท้ายสุดของ DataFrame 

เหมาะสำหรับตรวจว่าข้อมูลท้ายไฟล์ถูกอ่านเข้ามาปกติหรือไม่ โดยเฉพาะไฟล์ที่มีจำนวนแถวมาก

In [6]:
mso_df.tail()

,วันที่แก้ไขข้อมูลล่าสุด,รหัสครัวเรือน,รหัสประจำบ้าน,วันที่สร้างครัวเรือน,อายุ,เพศ,จังหวัด,ระดับการศึกษา,อาชีพหลัก,ประเภทกลุ่มเป้าหมาย,รหัส cm,หน่วยงานของ cm
95,2025-07-29 14:33:32.178,688878eaa933a405b21cc136,<NA>,2025-07-29 14:31:54.610,59,NaN,ชัยภูมิ,NaN,เกษตรกรรม (พืช ปศุสัตว์ ประมง),วัยผู้ใหญ่/วัยแรงงาน,cm360060,ศูนย์คุ้มครองคนไร้ที่พึ่ง จ.ชัยภูมิ
96,2023-03-17 19:08:15.489,628b008c8fa67bf5ad7d221b,<NA>,2022-05-23 10:33:32.270,79,NaN,มหาสารคาม,NaN,NaN,ผู้สูงอายุ,cm440005,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
97,2023-05-01 09:19:26.395,63b6325b2617b2b7aa04dc0b,25120251099,2023-05-01 09:13:47.520,51,หญิง,สระแก้ว,ประถมศึกษา,รับจ้างทั่วไป,วัยผู้ใหญ่/วัยแรงงาน,cm270001,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
98,2025-01-04 14:05:25.955,63e1d0d92617b2b7aa06096d,40160104483,2023-07-02 11:17:29.369,81,ชาย,ขอนแก่น,ไม่ได้เรียนหนังสือ,NaN,ผู้สูงอายุ,cm400016,ศูนย์เรียนรู้การพัฒนาสตรีและครอบครัวรัตนาภา จั...
99,2025-03-18 15:17:33.047,67d92537a933a405b21c2e77,<NA>,2025-03-18 14:48:07.735,70,หญิง,นครราชสีมา,ประถมศึกษา,เกษตรกรรม (พืช ปศุสัตว์ ประมง),ผู้สูงอายุ,cm300037,บ้านพักเด็กและครอบครัวจังหวัดนครราชสีมา

## 8. ดูตัวอย่างข้อมูลแบบสุ่มด้วย `sample()` 
บางครั้งการดูเฉพาะแถวแรกหรือแถวท้ายอาจไม่เพียงพอ เพราะข้อมูลช่วงต้นไฟล์อาจมีรูปแบบไม่เหมือนข้อมูลส่วนอื่น 

คำสั่ง `sample()` ใช้สุ่มตัวอย่างแถวจาก DataFrame

In [7]:
mso_df.sample(5, random_state=42)

,วันที่แก้ไขข้อมูลล่าสุด,รหัสครัวเรือน,รหัสประจำบ้าน,วันที่สร้างครัวเรือน,อายุ,เพศ,จังหวัด,ระดับการศึกษา,อาชีพหลัก,ประเภทกลุ่มเป้าหมาย,รหัส cm,หน่วยงานของ cm
83,2023-09-05 16:01:43.789,6284a65d8fa67bf5ad7d0949,<NA>,2022-05-18 14:55:09.017,37,NaN,เพชรบุรี,NaN,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm760001,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
53,2024-02-04 11:36:52.215,6476aad3611fdbad2925b62f,<NA>,2023-05-31 09:02:59.706,35,หญิง,สมุทรสงคราม,ประถมศึกษา,NaN,วัยผู้ใหญ่/วัยแรงงาน,cm750009,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
70,2023-09-02 14:54:48.248,6386a834ed6d46a6baea7954,<NA>,2022-11-30 07:47:48.806,30,หญิง,อุดรธานี,มัธยมศึกษาตอนต้น,รับจ้างทั่วไป,วัยผู้ใหญ่/วัยแรงงาน,cm410008,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...
45,2023-08-23 13:23:18.052,64e5a537b64d06b6b0ddeee6,<NA>,2023-08-23 13:20:39.596,64,หญิง,ชุมพร,ประถมศึกษา,รับจ้างทั่วไป,ผู้สูงอายุ,cm860009,ศูนย์บริการคนพิการ จังหวัด ชุมพร
44,2023-08-07 13:03:43.301,64a8fbc9b64d06b6b0dcf3f1,<NA>,2023-08-07 13:01:45.221,35,หญิง,ศรีสะเกษ,ประถมศึกษา,เกษตรกรรม (พืช ปศุสัตว์ ประมง),วัยผู้ใหญ่/วัยแรงงาน,cm330005,สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวั...

การใช้ `random_state` ช่วยให้ผลการสุ่มเหมือนเดิมทุกครั้งที่รัน code 

เหมาะกับการสอน การทำรายงาน หรือการทำงานที่ต้องการผลลัพธ์ซ้ำได้

## 9. ตรวจสอบขนาดข้อมูลด้วย `shape`

คำสั่ง `shape` ใช้ดูจำนวนแถวและจำนวนคอลัมน์ของ DataFrame 

ผลลัพธ์อยู่ในรูปแบบ

```python 
(number_of_rows, number_of_columns)
```

เช่น

(1000, 12)

หมายความว่าข้อมูลมี 1,000 แถว และ 12 คอลัมน์

In [8]:
mso_df.shape

(100, 12)

In [9]:
number_of_rows = mso_df.shape[0] 
number_of_columns = mso_df.shape[1] 

print("จำนวนแถว:", number_of_rows) 
print("จำนวนคอลัมน์:", number_of_columns)

จำนวนแถว: 100
จำนวนคอลัมน์: 12

## 10. ตรวจสอบชื่อ column ด้วย `columns` 
คำสั่ง `columns` ใช้ดูรายชื่อ column ทั้งหมดใน DataFrame

In [10]:
mso_df.columns

Index(['วันที่แก้ไขข้อมูลล่าสุด', 'รหัสครัวเรือน', 'รหัสประจำบ้าน',
       'วันที่สร้างครัวเรือน', 'อายุ', 'เพศ', 'จังหวัด', 'ระดับการศึกษา',
       'อาชีพหลัก', 'ประเภทกลุ่มเป้าหมาย', 'รหัส cm', 'หน่วยงานของ cm'],
      dtype='str')

In [11]:
list(mso_df.columns)

['วันที่แก้ไขข้อมูลล่าสุด',
 'รหัสครัวเรือน',
 'รหัสประจำบ้าน',
 'วันที่สร้างครัวเรือน',
 'อายุ',
 'เพศ',
 'จังหวัด',
 'ระดับการศึกษา',
 'อาชีพหลัก',
 'ประเภทกลุ่มเป้าหมาย',
 'รหัส cm',
 'หน่วยงานของ cm']

การตรวจชื่อ column มีประโยชน์มาก เพราะช่วยให้เรารู้ว่า 
- column ถูกอ่านเข้ามาครบหรือไม่ 
- ชื่อ column มีช่องว่างหรืออักขระแปลกหรือไม่ 
- ชื่อ column ตรงกับที่เราต้องใช้ใน code หรือไม่

## 11. ตรวจสอบ index 
index คือป้ายกำกับของแต่ละ row 

ถ้าไม่ได้กำหนดเอง pandas จะสร้าง index เป็นตัวเลขเริ่มจาก 0

In [12]:
mso_df.index

RangeIndex(start=0, stop=100, step=1)

## 12. ตรวจสอบชนิดข้อมูลด้วย `dtypes` 

คำสั่ง `dtypes` ใช้ดูว่าแต่ละ column ถูกอ่านเป็นข้อมูลชนิดใด

In [13]:
mso_df.dtypes

วันที่แก้ไขข้อมูลล่าสุด    datetime64[us]
รหัสครัวเรือน                      string
รหัสประจำบ้าน                      string
วันที่สร้างครัวเรือน       datetime64[us]
อายุ                                int64
เพศ                                   str
จังหวัด                               str
ระดับการศึกษา                         str
อาชีพหลัก                             str
ประเภทกลุ่มเป้าหมาย                   str
รหัส cm                            string
หน่วยงานของ cm                        str
dtype: object

ชนิดข้อมูลที่พบบ่อยใน pandas ได้แก่ 

| dtype | ความหมาย | ตัวอย่าง | 
|---|---|---| 
| `object` | ข้อความ หรือข้อมูลผสม | จังหวัด, เพศ, อาชีพ | 
| `string` | ข้อความแบบ pandas string | รหัสครัวเรือน, รหัสประจำบ้าน | 
| `int64` | จำนวนเต็ม | จำนวนสมาชิก, จำนวนรายการ | 
| `float64` | ตัวเลขทศนิยม หรือ column ตัวเลขที่มีค่าว่าง | อายุ, รายได้, คะแนน | 
| `datetime64[ns]` | วันที่และเวลา | วันที่สร้างข้อมูล | 
| `bool` | จริง/เท็จ | ผ่าน/ไม่ผ่าน, ใช่/ไม่ใช่ | 

สิ่งที่ต้องระวังคือ 
- column ที่เป็นรหัสควรเป็น string ไม่ใช่ตัวเลข 
- column วันที่ควรถูกอ่านเป็น datetime หากต้องใช้คำนวณหรือกรองช่วงเวลา 
- column ตัวเลขที่มีค่าว่างอาจถูกอ่านเป็น `float64`

## 13. ดูภาพรวมด้วย `info()` 
คำสั่ง `info()` ใช้ดูภาพรวมของ DataFrame เช่น 
- จำนวนแถว 
- จำนวน column 
- ชื่อ column 
- จำนวนค่าที่ไม่เป็นค่าว่าง 
- ชนิดข้อมูล 
- ขนาดหน่วยความจำโดยประมาณ

In [14]:
mso_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   วันที่แก้ไขข้อมูลล่าสุด  100 non-null    datetime64[us]
 1   รหัสครัวเรือน            100 non-null    string
 2   รหัสประจำบ้าน            24 non-null     string
 3   วันที่สร้างครัวเรือน     100 non-null    datetime64[us]
 4   อายุ                     100 non-null    int64
 5   เพศ                      77 non-null     str
 6   จังหวัด                  100 non-null    str
 7   ระดับการศึกษา            77 non-null     str
 8   อาชีพหลัก                39 non-null     str
 9   ประเภทกลุ่มเป้าหมาย      100 non-null    str
 10  รหัส cm                  100 non-null    string
 11  หน่วยงานของ cm           100 non-null    str
dtypes: datetime64[us](2), int64(1), str(6), string(3)
memory usage: 9.5 KB

`info()` เป็นหนึ่งในคำสั่งแรก ๆ ที่ควรใช้หลังจากนำเข้าข้อมูล 

เพราะช่วยให้เห็นปัญหาเบื้องต้นได้เร็ว เช่น 
- column ที่มีค่าว่าง 
- column ที่ชนิดข้อมูลไม่ตรง 
- จำนวน column และชื่อ column ทั้งหมด

## 14. เข้าใจค่าสถิติพื้นฐานก่อนใช้ describe()

ค่าสถิติพื้นฐานช่วยให้เรารู้จักข้อมูลตัวเลขอย่างรวดเร็ว 

สำหรับงานตรวจสอบคุณภาพข้อมูล เราดูค่าสถิติเพื่อจับสัญญาณเบื้องต้น เช่น
- ข้อมูลมีจำนวนมากพอหรือไม่ 
- มีค่าว่างหรือไม่ 
- ค่าต่ำสุดและสูงสุดสมเหตุสมผลหรือไม่ 
- ค่าเฉลี่ยดูผิดปกติหรือไม่ 
- ข้อมูลกระจายตัวมากหรือน้อย 
- มีค่าบางค่าที่อาจเป็น outlier หรือไม่

ใน pandas เรามักเริ่มจากคำสั่ง `describe()`

## 15. ความหมายของค่าสถิติที่พบบ่อย 
เมื่อใช้ `describe()` กับ column ตัวเลข pandas จะแสดงค่าสถิติต่อไปนี้ 
| ค่าสถิติ | ความหมายแบบง่าย | ใช้ตรวจคุณภาพข้อมูลอย่างไร | 
|---|---|---| 
| `count` | จำนวนค่าที่ไม่ว่าง | ถ้าน้อยกว่าจำนวนแถว แปลว่ามีค่าว่าง | 
| `mean` | ค่าเฉลี่ย | ใช้ดูค่ากลางโดยรวม แต่ไวต่อค่าผิดปกติ | 
| `std` | ส่วนเบี่ยงเบนมาตรฐาน | ใช้ดูว่าข้อมูลกระจายมากหรือน้อย | 
| `min` | ค่าน้อยที่สุด | ใช้จับค่าที่ต่ำผิดปกติ เช่น อายุ -1 | 
| `25%` | ค่าที่ต่ำกว่า 25% ของข้อมูล | ใช้ดูช่วงล่างของข้อมูล | 
| `50%` | ค่ามัธยฐาน หรือ median | ค่ากลางของข้อมูลเมื่อเรียงจากน้อยไปมาก | 
| `75%` | ค่าที่ต่ำกว่า 75% ของข้อมูล | ใช้ดูช่วงบนของข้อมูล | 
| `max` | ค่าสูงที่สุด | ใช้จับค่าที่สูงผิดปกติ เช่น อายุ 999 | 

เบื้องต้นให้จำว่า `min` และ `max` มีประโยชน์มากในการตรวจหาค่าที่ผิดปกติ 

ส่วน `count` ช่วยบอกว่ามีค่าว่างหรือไม่

## 16. ค่าเฉลี่ยกับค่ามัธยฐานต่างกันอย่างไร 

### ค่าเฉลี่ย หรือ mean 

ค่าเฉลี่ยคือผลรวมของข้อมูล หารด้วยจำนวนข้อมูล 

ตัวอย่างเช่น อายุของคน 5 คนคือ 

```python 
[20, 21, 22, 23, 80]
```

ค่าเฉลี่ยจะถูกดึงให้สูงขึ้นจากค่า 80

### ค่ามัธยฐาน หรือ median

ค่ามัธยฐานคือค่าที่อยู่ตรงกลางเมื่อเรียงข้อมูลจากน้อยไปมาก

ในตัวอย่างเดียวกัน ค่ามัธยฐานคือ 22

ดังนั้น median มักทนต่อค่าผิดปกติได้ดีกว่า mean

ในการตรวจคุณภาพข้อมูล ถ้า mean และ median ต่างกันมาก 

อาจเป็นสัญญาณว่าข้อมูลมีค่าที่สูงหรือต่ำผิดปกติ

In [15]:
example_ages = pd.Series([20, 21, 22, 23, 80]) 

print("mean:", example_ages.mean()) 
print("median:", example_ages.median())

mean: 33.2
median: 22.0

## 17. ส่วนเบี่ยงเบนมาตรฐาน หรือ std คืออะไร 
`std` ย่อมาจาก standard deviation หรือส่วนเบี่ยงเบนมาตรฐาน 

อธิบายแบบง่ายคือ 

> std บอกว่าข้อมูลกระจายห่างจากค่าเฉลี่ยมากน้อยแค่ไหน 

- ถ้า std น้อย แปลว่าค่าต่าง ๆ ใกล้เคียงกัน 
- ถ้า std มาก แปลว่าค่าต่าง ๆ กระจายกว้าง หรืออาจมีค่าผิดปกติอยู่ 

เบื้องต้นเราไม่จำเป็นต้องคำนวณ std แต่ควรรู้ว่า std ใช้ช่วยดูการกระจายตัวของข้อมูล

In [16]:
ages_close = pd.Series([30, 31, 32, 33, 34])
ages_spread = pd.Series([10, 20, 30, 40, 100])

print("std ของข้อมูลที่ใกล้กัน:", ages_close.std())
print("std ของข้อมูลที่กระจายมาก:", ages_spread.std())

std ของข้อมูลที่ใกล้กัน: 1.5811388300841898
std ของข้อมูลที่กระจายมาก: 35.35533905932738

## 18. Percentile คืออะไร 
Percentile คือค่าที่บอกตำแหน่งของข้อมูลเมื่อเรียงจากน้อยไปมาก 

ในผลลัพธ์ของ `describe()` มักเห็น 
- `25%` 
- `50%` 
- `75%` 

ตัวอย่างเช่น 
- `25%` หมายถึง 25% ของข้อมูลมีค่าน้อยกว่าหรือเท่ากับค่านี้ 
- `50%` คือค่ากลาง หรือ median 
- `75%` หมายถึง 75% ของข้อมูลมีค่าน้อยกว่าหรือเท่ากับค่านี้ 

ในการตรวจคุณภาพข้อมูล percentile ช่วยให้เราเข้าใจว่าข้อมูลส่วนใหญ่กระจุกอยู่ช่วงไหน

## 19. สรุปข้อมูลตัวเลขด้วย `describe()`

 คำสั่ง `describe()` ใช้ดูค่าสถิติเบื้องต้นของ column ที่เป็นตัวเลข

In [17]:
mso_df.describe()

          วันที่แก้ไขข้อมูลล่าสุด        วันที่สร้างครัวเรือน        อายุ
count                         100                         100  100.000000
mean   2023-09-24 19:42:21.373390  2023-03-23 05:44:38.681930   42.200000
min    2022-02-08 08:55:15.688000  2022-01-06 15:21:51.132000    1.000000
25%    2023-02-27 04:55:33.963750  2022-08-17 10:34:13.151750   26.000000
50%    2023-08-13 14:51:07.477000  2022-12-23 22:54:09.762500   44.500000
75%    2024-03-16 22:49:22.254250  2023-08-30 12:40:05.888000   59.000000
max    2025-11-03 14:02:41.077000  2025-07-29 14:31:54.610000  103.000000
std                           NaN                         NaN   25.063153

ในไฟล์ตัวอย่างนี้ column ตัวเลขที่สำคัญคือ `อายุ` 

เราจะใช้ column นี้เป็นตัวอย่างในการตรวจสอบคุณภาพข้อมูลตัวเลข

In [18]:
mso_df["อายุ"].describe()

count    100.000000
mean      42.200000
std       25.063153
min        1.000000
25%       26.000000
50%       44.500000
75%       59.000000
max      103.000000
Name: อายุ, dtype: float64

จากผลลัพธ์ของ `describe()` ให้สังเกตเป็นพิเศษที่ 
- `count`: มีจำนวนค่าที่ไม่ว่างเท่ากับจำนวนแถวทั้งหมดหรือไม่ 
- `min`: มีอายุต่ำผิดปกติหรือไม่ 
- `max`: มีอายุสูงผิดปกติหรือไม่ 
- `mean` และ `50%`: ต่างกันมากหรือไม่ 

ถ้าพบค่าที่ดูผิดปกติ เราไม่ควรแก้ไขในทันที แต่ควรบันทึกไว้

เพื่อใช้ประกอบการออกแบบแนวทางในการจัดการข้อมุลต่อไป

## 20. ตรวจสอบช่วงค่าของอายุ 
ในข้อมูลบุคคล column `อายุ` ควรอยู่ในช่วงที่สมเหตุสมผล 

เช่น ไม่ควรติดลบ และไม่ควรสูงมากผิดปกติ 

ในตัวอย่างนี้ เราจะกำหนดช่วงที่ควรตรวจสอบเป็น

```python 
อายุ < 0 หรือ อายุ > 120
```

In [19]:
unusual_age_df = mso_df[(mso_df["อายุ"] < 0) | (mso_df["อายุ"] > 120)] 
unusual_age_df

Empty DataFrame
Columns: [วันที่แก้ไขข้อมูลล่าสุด, รหัสครัวเรือน, รหัสประจำบ้าน, วันที่สร้างครัวเรือน, อายุ, เพศ, จังหวัด, ระดับการศึกษา, อาชีพหลัก, ประเภทกลุ่มเป้าหมาย, รหัส cm, หน่วยงานของ cm]
Index: []

In [20]:
unusual_age_count = unusual_age_df.shape[0] 
print("จำนวนรายการที่อายุผิดปกติ:", unusual_age_count)

จำนวนรายการที่อายุผิดปกติ: 0

## 21. ตรวจสอบค่าว่างด้วย `isna()` 
คำสั่ง `isna()` ใช้ตรวจว่าแต่ละ cell เป็นค่าว่างหรือไม่ 

ผลลัพธ์จะเป็น `True` หรือ `False`

In [21]:
mso_df.isna()

,วันที่แก้ไขข้อมูลล่าสุด,รหัสครัวเรือน,รหัสประจำบ้าน,วันที่สร้างครัวเรือน,อายุ,เพศ,จังหวัด,ระดับการศึกษา,อาชีพหลัก,ประเภทกลุ่มเป้าหมาย,รหัส cm,หน่วยงานของ cm
0,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,True,False,False,False,False,False,True,False,False,False
3,False,False,True,False,False,False,False,False,True,False,False,False
4,False,False,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,True,False,False,True,False,True,False,False,False,False
96,False,False,True,False,False,True,False,True,True,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,True,False,False,False
99,False,False,True,False,False,False,False,False,False,False,False,False

แต่การดูทั้งตารางแบบนี้อาจอ่านยาก 

โดยทั่วไป เรามักใช้ร่วมกับ `.sum()` เพื่อดูจำนวนค่าว่างของแต่ละ column

In [22]:
mso_df.isna().sum()

วันที่แก้ไขข้อมูลล่าสุด     0
รหัสครัวเรือน               0
รหัสประจำบ้าน              76
วันที่สร้างครัวเรือน        0
อายุ                        0
เพศ                        23
จังหวัด                     0
ระดับการศึกษา              23
อาชีพหลัก                  61
ประเภทกลุ่มเป้าหมาย         0
รหัส cm                     0
หน่วยงานของ cm              0
dtype: int64

## 22. จำนวนค่าว่างกับเปอร์เซ็นต์ค่าว่างต่างกันอย่างไร

การดูจำนวนค่าว่างอย่างเดียวอาจยังไม่พอ 

ตัวอย่างเช่น 
- ค่าว่าง 100 แถว จากข้อมูล 1,000 แถว = 10% 
- ค่าว่าง 100 แถว จากข้อมูล 1,000,000 แถว = 0.01% 

ดังนั้นเราควรดูทั้ง 
- จำนวนค่าว่าง 
- เปอร์เซ็นต์ค่าว่าง 

เพื่อประเมินว่าปัญหานั้นรุนแรงแค่ไหน

In [23]:
missing_count = mso_df.isna().sum() 
missing_percent = mso_df.isna().mean() * 100 

missing_percent

วันที่แก้ไขข้อมูลล่าสุด     0.0
รหัสครัวเรือน               0.0
รหัสประจำบ้าน              76.0
วันที่สร้างครัวเรือน        0.0
อายุ                        0.0
เพศ                        23.0
จังหวัด                     0.0
ระดับการศึกษา              23.0
อาชีพหลัก                  61.0
ประเภทกลุ่มเป้าหมาย         0.0
รหัส cm                     0.0
หน่วยงานของ cm              0.0
dtype: float64

## 23. สร้างตารางสรุปค่าว่าง 
เพื่อให้อ่านง่ายขึ้น เราสามารถสร้าง DataFrame สรุปค่าว่างได้

In [24]:
missing_summary = pd.DataFrame({ 
    "column": mso_df.columns, 
    "missing_count": mso_df.isna().sum().values, 
    "missing_percent": (mso_df.isna().mean() * 100).round(2).values 
}) 

missing_summary

                     column  missing_count  missing_percent
0   วันที่แก้ไขข้อมูลล่าสุด              0              0.0
1             รหัสครัวเรือน              0              0.0
2             รหัสประจำบ้าน             76             76.0
3      วันที่สร้างครัวเรือน              0              0.0
4                      อายุ              0              0.0
5                       เพศ             23             23.0
6                   จังหวัด              0              0.0
7             ระดับการศึกษา             23             23.0
8                 อาชีพหลัก             61             61.0
9       ประเภทกลุ่มเป้าหมาย              0              0.0
10                  รหัส cm              0              0.0
11           หน่วยงานของ cm              0              0.0

In [25]:
missing_summary.sort_values("missing_percent", ascending=False)

                     column  missing_count  missing_percent
2             รหัสประจำบ้าน             76             76.0
8                 อาชีพหลัก             61             61.0
5                       เพศ             23             23.0
7             ระดับการศึกษา             23             23.0
3      วันที่สร้างครัวเรือน              0              0.0
1             รหัสครัวเรือน              0              0.0
0   วันที่แก้ไขข้อมูลล่าสุด              0              0.0
4                      อายุ              0              0.0
6                   จังหวัด              0              0.0
9       ประเภทกลุ่มเป้าหมาย              0              0.0
10                  รหัส cm              0              0.0
11           หน่วยงานของ cm              0              0.0

จำนวนของค่าว่างมีผลต่อการใช้งานข้อมูลนั้นๆ เช่น 
- ควรเติมค่าหรือไม่ 
- ควรลบ row หรือไม่ 
- ควรลบ column หรือไม่ 
- ค่าว่างมีความหมายเชิงธุรกิจหรือไม่

## 24. ตรวจสอบข้อมูลซ้ำด้วย `duplicated()` 
คำสั่ง `duplicated()` ใช้ตรวจสอบว่าแต่ละ row ซ้ำกับ row ก่อนหน้าหรือไม่

In [26]:
mso_df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [27]:
mso_df.duplicated().sum()

np.int64(0)

## 25. ตรวจสอบข้อมูลซ้ำจากรหัสสำคัญ 
ในหลายกรณี เราไม่ได้ต้องการตรวจว่าทั้ง row ซ้ำกันทุก column 

แต่อาจต้องการตรวจว่ามีรหัสซ้ำหรือไม่ เช่น `รหัสครัวเรือน`

In [28]:
mso_df["รหัสครัวเรือน"].duplicated().sum()

np.int64(0)

In [29]:
duplicated_household_df = mso_df[mso_df["รหัสครัวเรือน"].duplicated(keep=False)] 
duplicated_household_df

Empty DataFrame
Columns: [วันที่แก้ไขข้อมูลล่าสุด, รหัสครัวเรือน, รหัสประจำบ้าน, วันที่สร้างครัวเรือน, อายุ, เพศ, จังหวัด, ระดับการศึกษา, อาชีพหลัก, ประเภทกลุ่มเป้าหมาย, รหัส cm, หน่วยงานของ cm]
Index: []

การพบรหัสซ้ำไม่ได้แปลว่าข้อมูลผิดเสมอไป 

ต้องตีความตามบริบท เช่น 
- หนึ่งครัวเรือนอาจมีสมาชิกหลายคน 
- หนึ่งรหัสอาจมีหลาย record จากการอัปเดตหลายครั้ง 
- หรืออาจเป็นข้อมูลซ้ำที่ต้องแก้ไขจริง 

ดังนั้นการตรวจซ้ำเป็นเพียงการระบุประเด็นที่ต้องตรวจต่อ

## 26. ข้อมูลเชิงหมวดหมู่คืออะไร 
ข้อมูลเชิงหมวดหมู่ คือข้อมูลที่แบ่งเป็นกลุ่มหรือประเภท 

ตัวอย่างในไฟล์นี้ เช่น 
- `จังหวัด` 
- `เพศ` 
- `ระดับการศึกษา` 
- `อาชีพหลัก` 
- `ประเภทกลุ่มเป้าหมาย` 

ข้อมูลประเภทนี้ไม่ควรดูด้วยค่าเฉลี่ย แต่ควรดูว่าแต่ละกลุ่มมีจำนวนเท่าไร 

และมีค่าที่สะกดหรือจัดกลุ่มผิดปกติหรือไม่

## 27. ตรวจสอบค่าที่เป็นไปได้ด้วย `value_counts()`

`value_counts()` ใช้นับจำนวนข้อมูลในแต่ละ category

In [30]:
mso_df["จังหวัด"].value_counts()

จังหวัด
นครศรีธรรมราช      8
อุดรธานี           7
เชียงใหม่          5
หนองคาย            4
นครราชสีมา         4
บุรีรัมย์          4
ขอนแก่น            4
นครนายก            4
อุทัยธานี          4
สระแก้ว            3
นครพนม             3
สุราษฎร์ธานี       3
ชุมพร              3
ราชบุรี            2
ปราจีนบุรี         2
เชียงราย           2
ตาก                2
สงขลา              2
เพชรบุรี           2
มหาสารคาม          2
กาญจนบุรี          2
ชัยภูมิ            2
อุบลราชธานี        1
ประจวบคีรีขันธ์    1
ยโสธร              1
นครปฐม             1
สุพรรณบุรี         1
ระนอง              1
เพชรบูรณ์          1
นราธิวาส           1
สิงห์บุรี          1
พิษณุโลก           1
กาฬสินธุ์          1
ศรีสะเกษ           1
ลพบุรี             1
ระยอง              1
จันทบุรี           1
พังงา              1
สมุทรสงคราม        1
บึงกาฬ             1
ชลบุรี             1
มุกดาหาร           1
กระบี่             1
เลย                1
สระบุรี            1
พระนครศรีอยุธยา    1
ยะลา               1
แพร่               1
Name: count, dtype: int64

In [31]:
mso_df["เพศ"].value_counts()

เพศ
หญิง    45
ชาย     32
Name: count, dtype: int64

In [32]:
mso_df["ระดับการศึกษา"].value_counts()

ระดับการศึกษา
ประถมศึกษา                42
ไม่ได้เรียนหนังสือ        24
มัธยมศึกษาตอนต้น           7
มัธยมศึกษาตอนปลาย/ปวช.     4
Name: count, dtype: int64

## 28. ใช้ `dropna=False` เพื่อรวมค่าว่างในการนับ 

โดย default `value_counts()` จะไม่นับค่าว่าง 

ถ้าต้องการนับค่าว่างด้วย ให้ใช้ `dropna=False`

In [33]:
mso_df["อาชีพหลัก"].value_counts(dropna=False)

อาชีพหลัก
NaN                                   61
รับจ้างทั่วไป                         26
เกษตรกรรม (พืช ปศุสัตว์ ประมง)        10
ธุรกิจส่วนตัว/ค้าขาย/เจ้าของกิจการ     2
อื่นๆ                                  1
Name: count, dtype: int64

## 29. ตรวจสอบจำนวนค่าที่ไม่ซ้ำด้วย `nunique()` 
คำสั่ง `nunique()` ใช้ดูว่าแต่ละ column มีจำนวนค่าที่ไม่ซ้ำกี่ค่า 

เหมาะสำหรับตอบคำถาม เช่น 
- มีข้อมูลกี่จังหวัด 
- มีประเภทกลุ่มเป้าหมายกี่ประเภท 
- มีระดับการศึกษากี่กลุ่ม

In [34]:
mso_df["จังหวัด"].nunique()

48

In [35]:
mso_df["ประเภทกลุ่มเป้าหมาย"].nunique()

5

## 30. ตรวจสอบค่าทั้งหมดด้วย `unique()` 
คำสั่ง `unique()` ใช้ดูค่าที่ไม่ซ้ำทั้งหมดใน column 

เหมาะกับ column ที่มีจำนวน category ไม่มาก

In [36]:
mso_df["เพศ"].unique()

<StringArray>
['หญิง', 'ชาย', nan]
Length: 3, dtype: str

In [37]:
mso_df["ประเภทกลุ่มเป้าหมาย"].unique()

<StringArray>
['เด็กเล็ก', 'วัยผู้ใหญ่/วัยแรงงาน', 'ผู้สูงอายุ', 'เด็ก', 'เด็กโต/วัยรุ่น']
Length: 5, dtype: str

หากพบค่าที่สะกดไม่เหมือนกัน 

แต่มีความหมายเดียวกัน เช่น 
- `"ชาย"` - `"ช."` 
- `"Male"` 

หรือ 
- `"ไม่ระบุ"` 
- `"-"` 
- ค่าว่าง 

นั่นคือประเด็นที่ต้องบันทึกไว้

เพื่อใช้ประกอบการออกแบบแนวทางในการจัดการข้อมูลต่อไป

## 31. ตรวจสอบ column วันที่ 
column วันที่ควรถูกตรวจสอบว่า 
- ถูกอ่านเป็น datetime หรือไม่ 
- วันที่ต่ำสุดและสูงสุดอยู่ในช่วงที่คาดหวังหรือไม่ 
- มีวันที่ผิดปกติหรือไม่

In [38]:
mso_df["วันที่สร้างครัวเรือน"].min()

Timestamp('2022-01-06 15:21:51.132000')

In [39]:
mso_df["วันที่สร้างครัวเรือน"].max()

Timestamp('2025-07-29 14:31:54.610000')

In [40]:
mso_df["วันที่แก้ไขข้อมูลล่าสุด"].min()

Timestamp('2022-02-08 08:55:15.688000')

In [41]:
mso_df["วันที่แก้ไขข้อมูลล่าสุด"].max()

Timestamp('2025-11-03 14:02:41.077000')

การตรวจช่วงวันที่ช่วยให้เรารู้ว่า 
- ข้อมูลอยู่ในช่วงเวลาที่คาดหวังหรือไม่ 
- มีวันที่เก่าหรือใหม่ผิดปกติหรือไม่ 
- มีข้อมูลที่น่าจะถูกบันทึกผิดหรือไม่

## 32. สร้างตารางสรุปคุณภาพข้อมูลเบื้องต้น 
ในการทำงานจริง เราอาจต้องสร้างตารางสรุปคุณภาพข้อมูล 

เพื่อส่งต่อให้ทีมตัดสินใจว่า column ใดควรใช้หรือควรตรวจสอบต่อ 

ตารางนี้ควรมีข้อมูล เช่น 
- ชื่อ column 
- dtype 
- จำนวนค่าว่าง 
- เปอร์เซ็นต์ค่าว่าง 
- จำนวนค่าที่ไม่ซ้ำ

In [42]:
data_quality_summary = pd.DataFrame({ 
    "column": mso_df.columns, 
    "dtype": mso_df.dtypes.astype(str).values, 
    "missing_count": mso_df.isna().sum().values, 
    "missing_percent": (mso_df.isna().mean() * 100).round(2).values, 
    "unique_count": mso_df.nunique(dropna=True).values }) 
    
data_quality_summary

,column,dtype,missing_count,missing_percent,unique_count
0,วันที่แก้ไขข้อมูลล่าสุด,datetime64[us],0,0.0,100
1,รหัสครัวเรือน,string,0,0.0,100
2,รหัสประจำบ้าน,string,76,76.0,24
3,วันที่สร้างครัวเรือน,datetime64[us],0,0.0,100
4,อายุ,int64,0,0.0,59
5,เพศ,str,23,23.0,2
6,จังหวัด,str,0,0.0,48
7,ระดับการศึกษา,str,23,23.0,4
8,อาชีพหลัก,str,61,61.0,4
9,ประเภทกลุ่มเป้าหมาย,str,0,0.0,5
10,รหัส cm,string,0,0.0,94
11,หน่วยงานของ cm,str,0,0.0,74

In [43]:
data_quality_summary.sort_values("missing_percent", ascending=False)

,column,dtype,missing_count,missing_percent,unique_count
2,รหัสประจำบ้าน,string,76,76.0,24
8,อาชีพหลัก,str,61,61.0,4
5,เพศ,str,23,23.0,2
7,ระดับการศึกษา,str,23,23.0,4
3,วันที่สร้างครัวเรือน,datetime64[us],0,0.0,100
1,รหัสครัวเรือน,string,0,0.0,100
0,วันที่แก้ไขข้อมูลล่าสุด,datetime64[us],0,0.0,100
4,อายุ,int64,0,0.0,59
6,จังหวัด,str,0,0.0,48
9,ประเภทกลุ่มเป้าหมาย,str,0,0.0,5
10,รหัส cm,string,0,0.0,94
11,หน่วยงานของ cm,str,0,0.0,74

ตารางนี้ช่วยให้เราเห็นภาพรวมว่า 
- column ใดมีค่าว่างมาก 
- column ใดมีจำนวนค่าที่ไม่ซ้ำสูง 
- column ใดอาจเป็นรหัส 
- column ใดควรตรวจสอบชนิดข้อมูลต่อ

## 33. Data Quality Checklist 
หลังจากตรวจสอบข้อมูลเบื้องต้น 

เราควรสรุปเป็น checklist เพื่อใช้ตัดสินใจว่าข้อมูลพร้อมสำหรับขั้นตอนถัดไปหรือไม่ 

ตัวอย่าง checklist 
| สิ่งที่ต้องตรวจ | คำถามที่ต้องตอบ | 
|---|---| 
| ขนาดข้อมูล | ข้อมูลมีกี่แถว กี่คอลัมน์ | 
| ชื่อ column | column ถูกอ่านครบหรือไม่ | 
| dtype | ชนิดข้อมูลถูกต้องหรือไม่ | 
| missing values | มีค่าว่างใน column สำคัญหรือไม่ | 
| duplicate rows | มี row ซ้ำหรือไม่ | 
| duplicate IDs | มีรหัสซ้ำหรือไม่ และซ้ำเพราะอะไร | 
| numeric range | อายุอยู่ในช่วงสมเหตุสมผลหรือไม่ | 
| categorical values | category สะกดสอดคล้องกันหรือไม่ | 
| date range | วันที่อยู่ในช่วงที่คาดหวังหรือไม่ |

# แบบฝึกหัดท้ายบท 
แบบฝึกหัดท้ายบทนี้จำลองสถานการณ์การตรวจสอบข้อมูลหลังนำเข้าไฟล์

แบบฝึกหัดนี้จะใช้ DataFrame `mso_df` เป็นข้อมูลหลัก

## แบบฝึกหัดที่ 1: สร้าง function สรุปโครงสร้างข้อมูลหลังนำเข้า
หัวหน้าทีมต้องการ function ที่ใช้ดูภาพรวมของ DataFrame หลังจากนำเข้าข้อมูล 

เพื่อให้ทีมสามารถใช้ตรวจไฟล์ใหม่ได้ทุกครั้ง

### ข้อกำหนด
ให้สร้าง function ชื่อ `summarize_dataframe_structure()` โดยมี parameter ดังนี้ 

```python 
def summarize_dataframe_structure(df): 
    ...
```

function นี้ต้องทำงานดังนี้
1. แสดงจำนวนแถวและจำนวนคอลัมน์
2. แสดงรายชื่อ column ทั้งหมด
3. แสดงชนิดข้อมูลของแต่ละ column
4. แสดงตัวอย่างข้อมูล 5 แถวแรก
5. แสดงตัวอย่างข้อมูลแบบสุ่ม 5 แถว โดยใช้ `random_state=42`

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `mso_df`

In [44]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 2: สร้าง function สำหรับตรวจสอบค่าว่าง
ทีมต้องการ function ที่สามารถรับ DataFrame ใดก็ได้ 

แล้วสร้างตารางสรุปค่าว่าง เพื่อใช้พิจารณาว่า column ใดควรตรวจสอบต่อ

### ข้อกำหนด
ให้สร้าง function ชื่อ `create_missing_summary()` โดยมี parameter ดังนี้ 

```python 
def create_missing_summary(df): 
    ...
```

function นี้ต้อง return DataFrame ที่มี column ต่อไปนี้
- column
- missing_count
- missing_percent

โดยเรียงลำดับจาก `missing_percent` มากไปน้อย

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `mso_df` และเก็บผลลัพธ์ไว้ในตัวแปรชื่อ `mso_missing_summary`

In [45]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 3: สร้าง function สำหรับตรวจค่าผิดปกติของ column ตัวเลข
ทีมต้องการตรวจสอบ column ตัวเลข เช่น `อายุ` ว่ามีค่าที่อยู่นอกช่วงสมเหตุสมผลหรือไม่ 

เนื่องจากในอนาคตอาจต้องตรวจ column ตัวเลขอื่น เช่น รายได้ จำนวนสมาชิก หรือคะแนน 

จึงควรสร้าง function ที่รับชื่อ column และช่วงค่าที่ต้องการตรวจได้

### ข้อกำหนด
ให้สร้าง function ชื่อ `check_numeric_range()` โดยมี parameter ดังนี้ 

```python 
def check_numeric_range(df, column, min_value, max_value): 
    ...
```

function นี้ต้องทำงานดังนี้
1. รับ DataFrame จาก df
2. รับชื่อ column ที่ต้องการตรวจจาก column
3. รับค่าต่ำสุดที่ยอมรับได้จาก min_value
4. รับค่าสูงสุดที่ยอมรับได้จาก max_value
5. ถ้า column ไม่มีอยู่ใน DataFrame ให้พิมพ์ข้อความ

>Column not found: <column name>

และ return DataFrame ว่าง

6. ถ้า column มีอยู่จริง ให้เลือก row ที่มีค่าน้อยกว่า min_value หรือมากกว่า max_value
7. return DataFrame ของ row ที่ผิดช่วง

หลังจากสร้าง function แล้ว ให้เรียกใช้เพื่อตรวจ column อายุ โดยกำหนดช่วงที่ยอมรับได้เป็น 0 ถึง 120

`unusual_age_df = check_numeric_range(mso_df, "อายุ", 0, 120)`

In [46]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 4: สร้าง function สำหรับตรวจสอบ category หลาย column
ทีมต้องการตรวจสอบค่าที่เป็นไปได้ของ column เชิงหมวดหมู่หลายตัว เช่น จังหวัด เพศ ระดับการศึกษา อาชีพ

และประเภทกลุ่มเป้าหมาย เนื่องจากต้องทำงานนี้ซ้ำกับหลาย dataset จึงควรเขียนเป็น function

### ข้อกำหนด
ให้สร้าง function ชื่อ `check_categories()` โดยมี parameter ดังนี้ 

```python 
def check_categories(df, columns): 
    ...
```

function นี้ต้องทำงานดังนี้
1. รับ DataFrame จาก df
2. รับ list ของ column ที่ต้องการตรวจจาก columns
3. ใช้ loop ผ่านแต่ละ column
4. ถ้า column นั้นมีอยู่จริงใน DataFrame ให้แสดง value_counts(dropna=False)
5. ถ้า column นั้นไม่มีอยู่ใน DataFrame ให้พิมพ์ข้อความ

>Column not found: <column name>

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ column ต่อไปนี้

```python
category_columns = [ 
    "จังหวัด", 
    "เพศ", 
    "ระดับการศึกษา", 
    "อาชีพหลัก", 
    "ประเภทกลุ่มเป้าหมาย" 
]
```

In [47]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 5: สร้าง function สรุปคุณภาพข้อมูลเบื้องต้น
ทีมต้องการ function กลางสำหรับตรวจสอบคุณภาพข้อมูลเบื้องต้นของ DataFrame ใดก็ได้ 

ก่อนส่งต่อไปทำ data cleaning function นี้ควรสรุปข้อมูลในระดับ column 

เพื่อให้เห็นว่าแต่ละ column มีปัญหาอะไรบ้าง

### ข้อกำหนด
ให้สร้าง function ชื่อ `create_data_quality_report()` โดยมี parameter ดังนี้ 

```python 
def create_data_quality_report(df): 
    ...
```

function นี้ต้อง return DataFrame ที่มี column ต่อไปนี้
- column
- dtype
- missing_count
- missing_percent
- unique_count

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `mso_df` และเก็บผลลัพธ์ไว้ในตัวแปรชื่อ `mso_quality_report`

จากนั้นเรียงลำดับผลลัพธ์จาก `missing_percent` มากไปน้อย

In [ ]:
# เขียนคำตอบของคุณใน Cell นี้