# บทที่ 10: การพัฒนาคุณภาพข้อมูลสำหรับใช้ในการวิเคราะห์
การพัฒนาคุณภาพข้อมูลไม่ได้หมายถึงการแก้ข้อมูลแบบสุ่ม 

แต่หมายถึงการปรับข้อมูลอย่างมีหลักการ เพื่อให้ข้อมูล 
- อ่านง่ายขึ้น 
- ใช้งานต่อได้สะดวกขึ้น 
- มีชนิดข้อมูลเหมาะสม 
- ลดปัญหาค่าว่างที่ไม่จำเป็น 
- ลดข้อมูลซ้ำ 
- มี category ที่สอดคล้องกัน 
- มีตัวแปรใหม่ที่ช่วยตอบคำถามเชิงวิเคราะห์ 
- พร้อมส่งต่อไปทำการวิเคราะห์ สรุปผล หรือสร้าง dashboard

## ผลการเรียนรู้ที่คาดหวัง 
เมื่อเรียนจบบทนี้ ผู้เรียนจะสามารถ 
1. อธิบายความแตกต่างระหว่างการตรวจสอบข้อมูลกับการพัฒนาคุณภาพข้อมูลได้ 
2. สร้างสำเนาข้อมูลก่อนปรับปรุงข้อมูลได้ 
3. เปลี่ยนชื่อ column ให้สื่อความหมายและใช้งานง่ายขึ้นได้ 
4. ตรวจและปรับชนิดข้อมูลให้เหมาะสมได้ 
5. จัดการค่าว่างด้วยวิธีพื้นฐาน เช่น เติมค่า ลบ row หรือสร้าง flag ได้ 
6. ตรวจและจัดการข้อมูลซ้ำตาม key ที่เหมาะสมได้ 
7. ปรับข้อความใน column เชิงหมวดหมู่ เช่น ตัดช่องว่างและจัดรูปแบบให้สอดคล้องกันได้ 
8. สร้าง column ใหม่เพื่อช่วยวิเคราะห์ เช่น รายได้รวม หนี้รวม รายได้สุทธิ และ flag ความเปราะบาง 
9. เลือก column สำหรับสร้าง dataset สุดท้ายที่พร้อมใช้วิเคราะห์ได้ 
10. ออกแบบ function สำหรับทำ data quality improvement workflow ที่ใช้ซ้ำได้ในแบบฝึกหัดท้ายบท

## ลำดับเนื้อหา 
บทเรียนนี้ประกอบด้วยหัวข้อต่อไปนี้ 
1. เตรียมข้อมูลตั้งต้นจาก Excel 
2. สร้างสำเนาข้อมูลก่อนปรับปรุง 
3. ตรวจสอบข้อมูลก่อนปรับปรุง 
4. เปลี่ยนชื่อ column ให้ใช้งานง่าย 
5. ปรับชนิดข้อมูลของ column รหัสและวันที่ 
6. จัดการค่าว่างใน column เชิงหมวดหมู่ 
7. จัดการค่าว่างใน column ตัวเลข 
8. ปรับข้อความใน column เชิงหมวดหมู่ 
9. ตรวจและจัดการข้อมูลซ้ำ 
10. สร้าง column ใหม่สำหรับการวิเคราะห์ 
11. สร้าง flag เพื่อช่วยแยกกลุ่มข้อมูล 
12. จัดกลุ่มข้อมูลเพื่อใช้วิเคราะห์ 
13. เลือก dataset สุดท้ายสำหรับวิเคราะห์ 
14. สรุปแนวคิดการพัฒนาคุณภาพข้อมูล 
15. แบบฝึกหัดท้ายบท

## 1. เตรียม pandas 
เริ่มจาก import pandas ด้วยชื่อย่อ `pd`

In [5]:
import pandas as pd

## 2. เตรียมข้อมูลตั้งต้นสำหรับบทนี้ 
ในบทนี้เราจะใช้ข้อมูลจากไฟล์ 

```python 
"moac_opsmoac_fragile_farmer.xlsx" 
``` 

โดยจะเตรียม DataFrame ชื่อ `farmer_raw_df`

In [6]:
excel_file = "moac_opsmoac_fragile_farmer.xlsx" 

target_sheets = [ 
    "v_cpd_fragile", 
    "v_dld_fragile", 
    "v_doae_fragile" 
] 

farmer_usecols = [ 
    "department_code", 
    "department", 
    "pid", 
    "province_code", 
    "province", 
    "amphur", 
    "tambon", 
    "is_farmer", 
    "farmer_type", 
    "main_occupation", 
    "income_in", 
    "income_out", 
    "debts_in", 
    "debts_out", 
    "updated_at" 
] 

farmer_dtype = { 
    "pid": "string", 
    "province_code": "string" 
} 

farmer_df_list = [] 

for sheet in target_sheets: 
    temp_df = pd.read_excel( 
        excel_file, 
        sheet_name=sheet, 
        usecols=farmer_usecols, 
        dtype=farmer_dtype 
    ) 
    
    temp_df["source_sheet"] = sheet 
    
    farmer_df_list.append(temp_df) 
    
farmer_raw_df = pd.concat(farmer_df_list, ignore_index=True) 

farmer_raw_df

,department_code,department,pid,province_code,province,amphur,tambon,is_farmer,farmer_type,main_occupation,income_in,income_out,debts_in,debts_out,updated_at,source_sheet
0,cpd,กรมส่งเสริมสหกรณ์,60e3f4907b85b690287f68a641b01b3d8392fbc28398f5...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
1,cpd,กรมส่งเสริมสหกรณ์,1ac1b0b4ad588a2c883621160bc0bbb5ca122dd42743b7...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
2,cpd,กรมส่งเสริมสหกรณ์,55e7b240314a3b5087b8ee4c376b52f229edda0d64761d...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
3,cpd,กรมส่งเสริมสหกรณ์,62a25e21b1ee1604c8cd4b812d81cf66854dd49cd25c6c...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
4,cpd,กรมส่งเสริมสหกรณ์,4eb76a041e7389e4ae9d22ecefd36a5ac999f4c5ea5ebe...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,doae,กรมส่งเสริมการเกษตร,b437149cc5b6a79f8866914fd84b644196ed99ba4f3d62...,96,NaN,NaN,NaN,1,เกษตรกรด้านพืช,ประกอบการเกษตร,200000.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
91,doae,กรมส่งเสริมการเกษตร,b1ce3ba83cfcfc5c21414fe2c496a37b635f56cb4de98c...,61,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,0.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
92,doae,กรมส่งเสริมการเกษตร,5bdabb8ac705d3ba6fab31c9f7f1a48c37455ac548d72a...,53,NaN,NaN,NaN,1,เกษตรกรด้านพืช,ประกอบการเกษตร,200000.0,0.0,100000.0,0.0,20250825.0,v_doae_fragile
93,doae,กรมส่งเสริมการเกษตร,d066b479f17041cb1297e115b3ed0c8e8b724769855a97...,12,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,60000.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
94,doae,กรมส่งเสริมการเกษตร,943e8b5363c5f7578cb95e4a59168db323b41393578589...,54,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,0.0,0.0,0.0,0.0,20250825.0,v_doae_fragile

หลังจากรัน cell ด้านบน เราจะได้ `farmer_raw_df` 

คำว่า `raw` หมายถึงข้อมูลตั้งต้นที่เพิ่งนำเข้ามา ยังไม่ได้ผ่านการปรับปรุงคุณภาพข้อมูล

In [7]:
farmer_raw_df.shape

(95, 16)

## 3. สร้างสำเนาข้อมูลก่อนปรับปรุง 
ก่อนทำความสะอาดหรือพัฒนาคุณภาพข้อมูล ควรสร้าง DataFrame ใหม่จากข้อมูลตั้งต้น 

วิธีนี้ช่วยให้เรายังเก็บข้อมูลเดิมไว้เปรียบเทียบได้

In [8]:
farmer_clean_df = farmer_raw_df.copy() 
farmer_clean_df

,department_code,department,pid,province_code,province,amphur,tambon,is_farmer,farmer_type,main_occupation,income_in,income_out,debts_in,debts_out,updated_at,source_sheet
0,cpd,กรมส่งเสริมสหกรณ์,60e3f4907b85b690287f68a641b01b3d8392fbc28398f5...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
1,cpd,กรมส่งเสริมสหกรณ์,1ac1b0b4ad588a2c883621160bc0bbb5ca122dd42743b7...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
2,cpd,กรมส่งเสริมสหกรณ์,55e7b240314a3b5087b8ee4c376b52f229edda0d64761d...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
3,cpd,กรมส่งเสริมสหกรณ์,62a25e21b1ee1604c8cd4b812d81cf66854dd49cd25c6c...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
4,cpd,กรมส่งเสริมสหกรณ์,4eb76a041e7389e4ae9d22ecefd36a5ac999f4c5ea5ebe...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,doae,กรมส่งเสริมการเกษตร,b437149cc5b6a79f8866914fd84b644196ed99ba4f3d62...,96,NaN,NaN,NaN,1,เกษตรกรด้านพืช,ประกอบการเกษตร,200000.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
91,doae,กรมส่งเสริมการเกษตร,b1ce3ba83cfcfc5c21414fe2c496a37b635f56cb4de98c...,61,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,0.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
92,doae,กรมส่งเสริมการเกษตร,5bdabb8ac705d3ba6fab31c9f7f1a48c37455ac548d72a...,53,NaN,NaN,NaN,1,เกษตรกรด้านพืช,ประกอบการเกษตร,200000.0,0.0,100000.0,0.0,20250825.0,v_doae_fragile
93,doae,กรมส่งเสริมการเกษตร,d066b479f17041cb1297e115b3ed0c8e8b724769855a97...,12,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,60000.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
94,doae,กรมส่งเสริมการเกษตร,943e8b5363c5f7578cb95e4a59168db323b41393578589...,54,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,0.0,0.0,0.0,0.0,20250825.0,v_doae_fragile

## 4. สร้างสำเนาข้อมูลก่อน cleaning 
หลักปฏิบัติที่ดีคือไม่ควรแก้ไข DataFrame ต้นฉบับโดยตรง 

เราจะสร้างสำเนาชื่อ `clean_df`

In [9]:
farmer_clean_df = farmer_raw_df.copy() 

farmer_clean_df

,department_code,department,pid,province_code,province,amphur,tambon,is_farmer,farmer_type,main_occupation,income_in,income_out,debts_in,debts_out,updated_at,source_sheet
0,cpd,กรมส่งเสริมสหกรณ์,60e3f4907b85b690287f68a641b01b3d8392fbc28398f5...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
1,cpd,กรมส่งเสริมสหกรณ์,1ac1b0b4ad588a2c883621160bc0bbb5ca122dd42743b7...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
2,cpd,กรมส่งเสริมสหกรณ์,55e7b240314a3b5087b8ee4c376b52f229edda0d64761d...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
3,cpd,กรมส่งเสริมสหกรณ์,62a25e21b1ee1604c8cd4b812d81cf66854dd49cd25c6c...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
4,cpd,กรมส่งเสริมสหกรณ์,4eb76a041e7389e4ae9d22ecefd36a5ac999f4c5ea5ebe...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,doae,กรมส่งเสริมการเกษตร,b437149cc5b6a79f8866914fd84b644196ed99ba4f3d62...,96,NaN,NaN,NaN,1,เกษตรกรด้านพืช,ประกอบการเกษตร,200000.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
91,doae,กรมส่งเสริมการเกษตร,b1ce3ba83cfcfc5c21414fe2c496a37b635f56cb4de98c...,61,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,0.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
92,doae,กรมส่งเสริมการเกษตร,5bdabb8ac705d3ba6fab31c9f7f1a48c37455ac548d72a...,53,NaN,NaN,NaN,1,เกษตรกรด้านพืช,ประกอบการเกษตร,200000.0,0.0,100000.0,0.0,20250825.0,v_doae_fragile
93,doae,กรมส่งเสริมการเกษตร,d066b479f17041cb1297e115b3ed0c8e8b724769855a97...,12,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,60000.0,0.0,0.0,0.0,20250825.0,v_doae_fragile
94,doae,กรมส่งเสริมการเกษตร,943e8b5363c5f7578cb95e4a59168db323b41393578589...,54,NaN,NaN,NaN,1,เกษตรกรด้านพืช,NaN,0.0,0.0,0.0,0.0,20250825.0,v_doae_fragile

แนวคิดนี้สำคัญมากในการทำงานจริง 

เราไม่ควรแก้ข้อมูลต้นฉบับโดยตรง หากยังไม่แน่ใจว่า logic ที่ใช้ถูกต้องหรือไม่ 

รูปแบบที่ดีคือ

```python 
raw_df = ข้อมูลตั้งต้น clean_df = raw_df.copy() 
``` 

แล้วจึงปรับปรุงข้อมูลใน `clean_df`

## 4. ตรวจสอบข้อมูลก่อนปรับปรุง 
ก่อนพัฒนาคุณภาพข้อมูล ควรตรวจภาพรวมของข้อมูลอีกครั้ง

In [10]:
farmer_clean_df.head()

,department_code,department,pid,province_code,province,amphur,tambon,is_farmer,farmer_type,main_occupation,income_in,income_out,debts_in,debts_out,updated_at,source_sheet
0,cpd,กรมส่งเสริมสหกรณ์,60e3f4907b85b690287f68a641b01b3d8392fbc28398f5...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
1,cpd,กรมส่งเสริมสหกรณ์,1ac1b0b4ad588a2c883621160bc0bbb5ca122dd42743b7...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
2,cpd,กรมส่งเสริมสหกรณ์,55e7b240314a3b5087b8ee4c376b52f229edda0d64761d...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
3,cpd,กรมส่งเสริมสหกรณ์,62a25e21b1ee1604c8cd4b812d81cf66854dd49cd25c6c...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
4,cpd,กรมส่งเสริมสหกรณ์,4eb76a041e7389e4ae9d22ecefd36a5ac999f4c5ea5ebe...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile

In [11]:
farmer_clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_code  95 non-null     str
 1   department       95 non-null     str
 2   pid              95 non-null     string
 3   province_code    67 non-null     string
 4   province         10 non-null     object
 5   amphur           10 non-null     object
 6   tambon           10 non-null     object
 7   is_farmer        95 non-null     int64
 8   farmer_type      95 non-null     str
 9   main_occupation  21 non-null     object
 10  income_in        64 non-null     float64
 11  income_out       64 non-null     float64
 12  debts_in         64 non-null     float64
 13  debts_out        64 non-null     float64
 14  updated_at       80 non-null     float64
 15  source_sheet     95 non-null     str
dtypes: float64(5), int64(1), object(4), str(4), string(2)
memory usage: 12.0+ KB

In [12]:
farmer_clean_df.isna().sum()

department_code     0
department          0
pid                 0
province_code      28
province           85
amphur             85
tambon             85
is_farmer           0
farmer_type         0
main_occupation    74
income_in          31
income_out         31
debts_in           31
debts_out          31
updated_at         15
source_sheet        0
dtype: int64

In [13]:
farmer_clean_df.describe()

,is_farmer,income_in,income_out,debts_in,debts_out,updated_at
count,95.0,64.000000,64.000000,64.000000,64.000000,8.000000e+01
mean,1.0,58787.500000,29378.125000,19015.625000,20750.000000,2.025064e+07
std,0.0,72234.150785,54336.916238,30511.248089,53591.932584,1.193210e+03
min,1.0,0.000000,0.000000,0.000000,0.000000,2.024021e+07
25%,1.0,0.000000,0.000000,0.000000,0.000000,2.025082e+07
50%,1.0,31200.000000,10000.000000,0.000000,0.000000,2.025082e+07
75%,1.0,92500.000000,30000.000000,22500.000000,12000.000000,2.025082e+07
max,1.0,300000.000000,310800.000000,120000.000000,300000.000000,2.025082e+07

## 5. เปลี่ยนชื่อ column ให้ใช้งานง่ายขึ้น
ชื่อ column ที่ดีควร 
- สั้นพอสมควร 
- สื่อความหมาย 
- ใช้รูปแบบสม่ำเสมอ 
- ง่ายต่อการพิมพ์ใน code 

ในตัวอย่างนี้ เราจะเปลี่ยนบางชื่อให้สื่อความหมายชัดขึ้น และทำให้ใช้งานต่อได้สะดวกขึ้น

In [14]:
rename_columns = { 
    "pid": "person_id", 
    "amphur": "district", 
    "tambon": "subdistrict", 
    "income_in": "income_agriculture", 
    "income_out": "income_non_agriculture", 
    "debts_in": "debt_agriculture", 
    "debts_out": "debt_non_agriculture" 
}

farmer_clean_df = farmer_clean_df.rename(columns=rename_columns) 

farmer_clean_df.head()

,department_code,department,person_id,province_code,province,district,subdistrict,is_farmer,farmer_type,main_occupation,income_agriculture,income_non_agriculture,debt_agriculture,debt_non_agriculture,updated_at,source_sheet
0,cpd,กรมส่งเสริมสหกรณ์,60e3f4907b85b690287f68a641b01b3d8392fbc28398f5...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
1,cpd,กรมส่งเสริมสหกรณ์,1ac1b0b4ad588a2c883621160bc0bbb5ca122dd42743b7...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
2,cpd,กรมส่งเสริมสหกรณ์,55e7b240314a3b5087b8ee4c376b52f229edda0d64761d...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
3,cpd,กรมส่งเสริมสหกรณ์,62a25e21b1ee1604c8cd4b812d81cf66854dd49cd25c6c...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile
4,cpd,กรมส่งเสริมสหกรณ์,4eb76a041e7389e4ae9d22ecefd36a5ac999f4c5ea5ebe...,<NA>,NaN,NaN,NaN,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,NaN,NaN,NaN,NaN,NaN,NaN,v_cpd_fragile

หลังเปลี่ยนชื่อ column แล้ว ควรตรวจสอบรายชื่อ column อีกครั้ง

In [15]:
list(farmer_clean_df.columns)

['department_code',
 'department',
 'person_id',
 'province_code',
 'province',
 'district',
 'subdistrict',
 'is_farmer',
 'farmer_type',
 'main_occupation',
 'income_agriculture',
 'income_non_agriculture',
 'debt_agriculture',
 'debt_non_agriculture',
 'updated_at',
 'source_sheet']

การเปลี่ยนชื่อ column ไม่ได้เปลี่ยนค่าข้อมูลภายใน cell 

แต่ช่วยให้ code อ่านง่ายขึ้น และลดความสับสนเมื่อนำข้อมูลไปใช้ต่อ

## 6. ตรวจสอบชนิดข้อมูลหลังเปลี่ยนชื่อ column 
หลังจากเปลี่ยนชื่อ column แล้ว ควรตรวจสอบ dtype อีกครั้ง

In [16]:
farmer_clean_df.dtypes

department_code               str
department                    str
person_id                  string
province_code              string
province                   object
district                   object
subdistrict                object
is_farmer                   int64
farmer_type                   str
main_occupation            object
income_agriculture        float64
income_non_agriculture    float64
debt_agriculture          float64
debt_non_agriculture      float64
updated_at                float64
source_sheet                  str
dtype: object

column ที่เป็นรหัส เช่น 
- `person_id` 
- `province_code` 
- `department_code` 

ควรเป็น string เพราะรหัสไม่ใช่ตัวเลขสำหรับคำนวณ 

หากยังไม่ใช่ string สามารถแปลงด้วย `.astype("string")`

In [17]:
farmer_clean_df["person_id"] = farmer_clean_df["person_id"].astype("string") 
farmer_clean_df["province_code"] = farmer_clean_df["province_code"].astype("string") 
farmer_clean_df["department_code"] = farmer_clean_df["department_code"].astype("string") 

farmer_clean_df.dtypes

department_code            string
department                    str
person_id                  string
province_code              string
province                   object
district                   object
subdistrict                object
is_farmer                   int64
farmer_type                   str
main_occupation            object
income_agriculture        float64
income_non_agriculture    float64
debt_agriculture          float64
debt_non_agriculture      float64
updated_at                float64
source_sheet                  str
dtype: object

สำหรับ column วันที่ เช่น `updated_at` ควรแปลงเป็น datetime เพื่อให้สามารถกรองช่วงเวลา หรือหาวันที่ต่ำสุด/สูงสุดได้

In [18]:
farmer_clean_df["updated_at"] = pd.to_datetime( 
    farmer_clean_df["updated_at"], 
    errors="coerce" ) 

farmer_clean_df["updated_at"].min(), farmer_clean_df["updated_at"].max()

(Timestamp('1970-01-01 00:00:00.020240212'),
 Timestamp('1970-01-01 00:00:00.020250825'))

การใช้ `errors="coerce"` หมายความว่า หากค่าใดแปลงเป็นวันที่ไม่ได้ pandas จะเปลี่ยนค่านั้นเป็น `NaT` 

`NaT` คือค่าว่างสำหรับข้อมูลประเภทวันที่

## 7. ตรวจสอบค่าว่างอีกครั้ง 
ก่อนจัดการค่าว่าง เราควรดูจำนวนค่าว่างของแต่ละ column

In [19]:
farmer_clean_df.isna().sum()

department_code            0
department                 0
person_id                  0
province_code             28
province                  85
district                  85
subdistrict               85
is_farmer                  0
farmer_type                0
main_occupation           74
income_agriculture        31
income_non_agriculture    31
debt_agriculture          31
debt_non_agriculture      31
updated_at                15
source_sheet               0
dtype: int64

## 8. เติมค่าว่างในข้อมูลเชิงหมวดหมู่ 
column เชิงหมวดหมู่ เช่น 
- `farmer_type` 
- `main_occupation` 
- `province` 
- `district` 
- `subdistrict` 

หากมีค่าว่าง อาจเติมด้วยคำว่า `"Unknown"` เพื่อบอกว่าไม่มีข้อมูลหรือไม่ทราบค่า 

วิธีนี้เหมาะเมื่อเรายังไม่ต้องการลบ row แต่ต้องการให้ category ชัดเจนขึ้น

In [20]:
category_columns = [ 
    "farmer_type", 
    "main_occupation", 
    "province", 
    "district", 
    "subdistrict" 
] 

for column in category_columns: 
    farmer_clean_df[column] = farmer_clean_df[column].fillna("Unknown")

ตรวจสอบค่าว่างใน column เหล่านี้อีกครั้ง

In [21]:
farmer_clean_df[category_columns].isna().sum()

farmer_type        0
main_occupation    0
province           0
district           0
subdistrict        0
dtype: int64

การเติมค่าว่างในข้อมูลเชิงหมวดหมู่ด้วย `"Unknown"` มีข้อดีคือ 
- ไม่ทำให้ row หายไป 
- ทำให้ค่าว่างกลายเป็น category ที่ตรวจนับได้ 
- เหมาะเมื่อยังไม่รู้ว่าค่าว่างควรถูกตีความอย่างไร 

อย่างไรก็ตาม ในงานจริงควรตรวจสอบกับเจ้าของข้อมูลว่าค่าว่างหมายถึงอะไร

## 9. จัดการค่าว่างใน column ตัวเลข 
column รายได้และหนี้สินเป็นข้อมูลตัวเลข 

ในบางกรณี ค่าว่างอาจหมายถึงไม่มีข้อมูล ไม่ใช่ศูนย์ 

แต่สำหรับการฝึกในบทนี้ เราจะกำหนดสมมติฐานว่า 
> ถ้าไม่มีข้อมูลรายได้หรือหนี้สิน ให้เติมเป็น 0 เพื่อให้สามารถคำนวณตัวแปรรวมได้ 

ในการทำงานจริง ควรยืนยันสมมติฐานนี้กับเจ้าของข้อมูลก่อนเสมอ

In [22]:
numeric_columns = [ 
    "income_agriculture", 
    "income_non_agriculture", 
    "debt_agriculture", 
    "debt_non_agriculture" 
] 

for column in numeric_columns: 
    farmer_clean_df[column] = farmer_clean_df[column].fillna(0)

ตรวจสอบค่าว่างของ column ตัวเลขอีกครั้ง

In [23]:
farmer_clean_df[numeric_columns].isna().sum()

income_agriculture        0
income_non_agriculture    0
debt_agriculture          0
debt_non_agriculture      0
dtype: int64

หลังเติมค่าว่างแล้ว ควรตรวจสอบค่าสถิติพื้นฐานอีกครั้ง

In [24]:
farmer_clean_df[numeric_columns].describe()

,income_agriculture,income_non_agriculture,debt_agriculture,debt_non_agriculture
count,95.000000,95.000000,95.000000,95.000000
mean,39604.210526,19791.578947,12810.526316,13978.947368
std,65305.735820,46589.213579,26537.927390,44950.795545
min,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000
75%,56000.000000,20000.000000,11000.000000,0.000000
max,300000.000000,310800.000000,120000.000000,300000.000000

## 10. ปรับข้อความให้สม่ำเสมอ
ข้อมูลข้อความมักมีปัญหา เช่น 
- มีช่องว่างด้านหน้า 
- มีช่องว่างด้านหลัง 
- ใช้ตัวพิมพ์เล็ก/ใหญ่ไม่สม่ำเสมอ 
- สะกดไม่เหมือนกัน 

สำหรับข้อมูลข้อความ เราสามารถใช้ `.str.strip()` เพื่อตัดช่องว่างหน้าและหลังข้อความ

In [25]:
text_columns = [ 
    "department", 
    "province", 
    "district", 
    "subdistrict", 
    "farmer_type", 
    "main_occupation", 
    "source_sheet" 
] 

for column in text_columns: 
    farmer_clean_df[column] = farmer_clean_df[column].astype("string").str.strip()

ตรวจสอบค่าที่เป็นไปได้ของ `farmer_type`

In [26]:
farmer_clean_df["farmer_type"].value_counts(dropna=False)

farmer_type
เกษตรกรด้านพืช                               70
เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร    15
เกษตรกรผู้เลี้ยงสัตว์                        10
Name: count, dtype: Int64

ตรวจสอบค่าที่เป็นไปได้ของ `main_occupation`

In [27]:
farmer_clean_df["main_occupation"].value_counts(dropna=False)

main_occupation
Unknown           74
ประกอบการเกษตร    20
รับจ้างทั่วไป      1
Name: count, dtype: Int64

การปรับข้อความเป็นขั้นตอนเล็ก ๆ ที่สำคัญมาก 

เพราะข้อมูลที่ดูเหมือนเป็นค่าเดียวกัน อาจถูกนับแยกกันเพียงเพราะมีช่องว่าง เช่น 
- `"Farmer"` 
- `"Farmer "` 
- `" Farmer"` 

การใช้ `.str.strip()` ช่วยลดปัญหานี้ได้

## 11. ตรวจสอบข้อมูลซ้ำ 
เริ่มจากตรวจว่ามี row ที่ซ้ำกันทุก column หรือไม่

In [28]:
farmer_clean_df.duplicated().sum()

np.int64(0)

ถ้าต้องการลบ row ที่ซ้ำกันทุก column สามารถใช้ `drop_duplicates()` 

ในตัวอย่างนี้ เราจะสร้าง DataFrame ใหม่หลังลบ row ซ้ำ

In [29]:
farmer_clean_df = farmer_clean_df.drop_duplicates() 
farmer_clean_df.shape

(95, 16)

ในงานจริง บางครั้งเราอาจต้องตรวจซ้ำจาก key เช่น `person_id` 

แต่ต้องระวังว่า person เดียวกันอาจปรากฏในหลายหน่วยงานหรือหลาย sheet ได้ 

ดังนั้นการลบข้อมูลซ้ำตาม key ต้องเข้าใจบริบทของข้อมูลก่อน

In [30]:
farmer_clean_df["person_id"].duplicated().sum()

np.int64(0)

ดูตัวอย่างข้อมูลที่ `person_id` ซ้ำ

In [31]:
duplicated_person_df = farmer_clean_df[ farmer_clean_df["person_id"].duplicated(keep=False) ] 
duplicated_person_df

Empty DataFrame
Columns: [department_code, department, person_id, province_code, province, district, subdistrict, is_farmer, farmer_type, main_occupation, income_agriculture, income_non_agriculture, debt_agriculture, debt_non_agriculture, updated_at, source_sheet]
Index: []

ในตัวอย่างนี้เราไม่พบข้อมูล `person_id` ซ้ำ

อย่างไรก็ดีเราไม่ควรจะลบข้อมูลซ้ำ

เพราะต้องตีความก่อนว่า 
- คนเดียวกันอาจได้รับข้อมูลจากหลายหน่วยงานหรือไม่ 
- ข้อมูลซ้ำจริงหรือเป็นข้อมูลคนละประเภท 
- ควรเก็บ record ล่าสุด หรือรวมข้อมูลจากหลาย record

การทำ data cleaning นั้นต้องใช้ทั้ง code และความเข้าใจบริบทของข้อมูล

## 12. สร้าง column ใหม่สำหรับวิเคราะห์
หลังจากเติมค่าว่างใน column ตัวเลขแล้ว เราสามารถสร้าง column ใหม่เพื่อช่วยวิเคราะห์ได้ 

รายได้รวมอาจคำนวณจาก 

```python 
income_agriculture + income_non_agriculture 
```

In [32]:
farmer_clean_df["total_income"] = ( 
    farmer_clean_df["income_agriculture"] 
    + farmer_clean_df["income_non_agriculture"] 
) 

farmer_clean_df[["income_agriculture", "income_non_agriculture", "total_income"]].head()

   income_agriculture  income_non_agriculture  total_income
0                 0.0                     0.0           0.0
1                 0.0                     0.0           0.0
2                 0.0                     0.0           0.0
3                 0.0                     0.0           0.0
4                 0.0                     0.0           0.0

## 13. สร้าง column หนี้รวม 
หนี้รวมอาจคำนวณจาก

```python 
debt_agriculture + debt_non_agriculture 
```

In [33]:
farmer_clean_df["total_debt"] = ( 
    farmer_clean_df["debt_agriculture"] 
    + farmer_clean_df["debt_non_agriculture"] 
) 

farmer_clean_df[["debt_agriculture", "debt_non_agriculture", "total_debt"]].head()

   debt_agriculture  debt_non_agriculture  total_debt
0               0.0                   0.0         0.0
1               0.0                   0.0         0.0
2               0.0                   0.0         0.0
3               0.0                   0.0         0.0
4               0.0                   0.0         0.0

## 14. สร้าง column รายได้สุทธิ 
ในตัวอย่างนี้ เราจะสร้างตัวแปรอย่างง่ายชื่อ `net_income` 

```python 
total_income - total_debt 
``` 

ตัวแปรนี้ไม่ได้แทนฐานะทางเศรษฐกิจทั้งหมด แต่ช่วยให้ฝึกแนวคิดการสร้างตัวแปรใหม่เพื่อใช้วิเคราะห์

In [34]:
farmer_clean_df["net_income"] = ( 
    farmer_clean_df["total_income"] 
    - farmer_clean_df["total_debt"] 
) 

farmer_clean_df[["total_income", "total_debt", "net_income"]].head()

   total_income  total_debt  net_income
0           0.0         0.0         0.0
1           0.0         0.0         0.0
2           0.0         0.0         0.0
3           0.0         0.0         0.0
4           0.0         0.0         0.0

## 15. สร้าง flag สำหรับกลุ่มที่มีหนี้มากกว่ารายได้ 
เราสามารถสร้าง column boolean เพื่อบอกว่า row ใดมีหนี้รวมมากกว่ารายได้รวม

In [35]:
farmer_clean_df["debt_more_than_income"] = ( 
    farmer_clean_df["total_debt"] > farmer_clean_df["total_income"] 
) 

farmer_clean_df[["total_income", "total_debt", "debt_more_than_income"]].head()

   total_income  total_debt  debt_more_than_income
0           0.0         0.0                  False
1           0.0         0.0                  False
2           0.0         0.0                  False
3           0.0         0.0                  False
4           0.0         0.0                  False

boolean column เช่น `debt_more_than_income` มีประโยชน์สำหรับการกรองข้อมูลและสรุปจำนวนกลุ่มเป้าหมายในขั้นตอนวิเคราะห์

## 16. จัดกลุ่มข้อมูลเพื่อใช้วิเคราะห์
เราสามารถใช้ function และ `.apply()` เพื่อจัดกลุ่มข้อมูลจากเงื่อนไข 

ตัวอย่างนี้จะจัดกลุ่ม `total_debt` เป็น 
- `"No debt"` ถ้าหนี้รวมเท่ากับ 0 
- `"Low debt"` ถ้าหนี้รวมมากกว่า 0 แต่ไม่เกิน 50,000 
- `"Medium debt"` ถ้าหนี้รวมมากกว่า 50,000 แต่ไม่เกิน 200,000 
- `"High debt"` ถ้าหนี้รวมมากกว่า 200,000

In [36]:
def classify_debt_level(total_debt): 
    if total_debt == 0: 
        return "No debt" 
    elif total_debt <= 50000: 
        return "Low debt" 
    elif total_debt <= 200000: 
        return "Medium debt" 
    else: 
        return "High debt"

In [37]:
farmer_clean_df["debt_level"] = farmer_clean_df["total_debt"].apply(classify_debt_level) 
farmer_clean_df[["total_debt", "debt_level"]].head()

   total_debt debt_level
0         0.0    No debt
1         0.0    No debt
2         0.0    No debt
3         0.0    No debt
4         0.0    No debt

ตรวจสอบจำนวนข้อมูลในแต่ละกลุ่มหนี้

In [38]:
farmer_clean_df["debt_level"].value_counts(dropna=False)

debt_level
No debt        63
Medium debt    18
Low debt       12
High debt       2
Name: count, dtype: int64

การจัดกลุ่มแบบนี้เป็นตัวอย่างของการพัฒนาข้อมูลให้พร้อมวิเคราะห์ 

เพราะแทนที่จะดูตัวเลขข้อมูลดิบอย่างเดียว เราสร้าง category ที่ช่วยให้สรุปข้อมูลได้ง่ายขึ้น

## 17. เลือก column สำหรับ dataset สุดท้าย 
หลังจากปรับปรุงข้อมูลแล้ว เราอาจเลือกเฉพาะ column ที่ต้องการใช้วิเคราะห์ต่อ

In [39]:
analysis_columns = [ 
    "department_code", 
    "department", 
    "person_id", 
    "province_code", 
    "province", 
    "district", 
    "subdistrict", 
    "is_farmer", 
    "farmer_type", 
    "main_occupation", 
    "income_agriculture", 
    "income_non_agriculture", 
    "debt_agriculture", 
    "debt_non_agriculture", 
    "total_income", 
    "total_debt", 
    "net_income", 
    "debt_more_than_income", 
    "debt_level", 
    "updated_at", 
    "source_sheet" 
] 

farmer_analysis_df = farmer_clean_df[analysis_columns].copy() 
farmer_analysis_df.head()

,department_code,department,person_id,province_code,province,district,subdistrict,is_farmer,farmer_type,main_occupation,...,income_non_agriculture,debt_agriculture,debt_non_agriculture,total_income,total_debt,net_income,debt_more_than_income,debt_level,updated_at,source_sheet
0,cpd,กรมส่งเสริมสหกรณ์,60e3f4907b85b690287f68a641b01b3d8392fbc28398f5...,<NA>,Unknown,Unknown,Unknown,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,Unknown,...,0.0,0.0,0.0,0.0,0.0,0.0,False,No debt,NaT,v_cpd_fragile
1,cpd,กรมส่งเสริมสหกรณ์,1ac1b0b4ad588a2c883621160bc0bbb5ca122dd42743b7...,<NA>,Unknown,Unknown,Unknown,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,Unknown,...,0.0,0.0,0.0,0.0,0.0,0.0,False,No debt,NaT,v_cpd_fragile
2,cpd,กรมส่งเสริมสหกรณ์,55e7b240314a3b5087b8ee4c376b52f229edda0d64761d...,<NA>,Unknown,Unknown,Unknown,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,Unknown,...,0.0,0.0,0.0,0.0,0.0,0.0,False,No debt,NaT,v_cpd_fragile
3,cpd,กรมส่งเสริมสหกรณ์,62a25e21b1ee1604c8cd4b812d81cf66854dd49cd25c6c...,<NA>,Unknown,Unknown,Unknown,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,Unknown,...,0.0,0.0,0.0,0.0,0.0,0.0,False,No debt,NaT,v_cpd_fragile
4,cpd,กรมส่งเสริมสหกรณ์,4eb76a041e7389e4ae9d22ecefd36a5ac999f4c5ea5ebe...,<NA>,Unknown,Unknown,Unknown,1,เกษตรกรผู้เป็นสมาชิกสหกรณ์และกลุุมเกษตรกร,Unknown,...,0.0,0.0,0.0,0.0,0.0,0.0,False,No debt,NaT,v_cpd_fragile

## 18. ตรวจสอบ dataset สุดท้าย 
ก่อนส่งต่อ dataset ไปวิเคราะห์ ควรตรวจสอบอีกครั้ง

In [40]:
farmer_analysis_df.shape

(95, 21)

In [41]:
farmer_analysis_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   department_code         95 non-null     string
 1   department              95 non-null     string
 2   person_id               95 non-null     string
 3   province_code           67 non-null     string
 4   province                95 non-null     string
 5   district                95 non-null     string
 6   subdistrict             95 non-null     string
 7   is_farmer               95 non-null     int64
 8   farmer_type             95 non-null     string
 9   main_occupation         95 non-null     string
 10  income_agriculture      95 non-null     float64
 11  income_non_agriculture  95 non-null     float64
 12  debt_agriculture        95 non-null     float64
 13  debt_non_agriculture    95 non-null     float64
 14  total_income            95 non-null     float64
 15  total_debt              95 non-null     float64
 16  net_income              95 non-null     float64
 17  debt_more_than_income   95 non-null     bool
 18  debt_level              95 non-null     str
 19  updated_at              80 non-null     datetime64[ns]
 20  source_sheet            95 non-null     string
dtypes: bool(1), datetime64[ns](1), float64(7), int64(1), str(1), string(10)
memory usage: 15.1 KB

In [42]:
farmer_analysis_df.isna().sum()

department_code            0
department                 0
person_id                  0
province_code             28
province                   0
district                   0
subdistrict                0
is_farmer                  0
farmer_type                0
main_occupation            0
income_agriculture         0
income_non_agriculture     0
debt_agriculture           0
debt_non_agriculture       0
total_income               0
total_debt                 0
net_income                 0
debt_more_than_income      0
debt_level                 0
updated_at                15
source_sheet               0
dtype: int64

In [43]:
farmer_analysis_df.describe()

,is_farmer,income_agriculture,income_non_agriculture,debt_agriculture,debt_non_agriculture,total_income,total_debt,net_income,updated_at
count,95.0,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,80
mean,1.0,39604.210526,19791.578947,12810.526316,13978.947368,59395.789474,26789.473684,32606.315789,1970-01-01 00:00:00.020250636
min,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-200000.000000,1970-01-01 00:00:00.020240212
25%,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1970-01-01 00:00:00.020250825
50%,1.0,0.000000,0.000000,0.000000,0.000000,10000.000000,0.000000,0.000000,1970-01-01 00:00:00.020250825
75%,1.0,56000.000000,20000.000000,11000.000000,0.000000,100000.000000,27500.000000,50000.000000,1970-01-01 00:00:00.020250825
max,1.0,300000.000000,310800.000000,120000.000000,300000.000000,400000.000000,306000.000000,343200.000000,1970-01-01 00:00:00.020250825
std,0.0,65305.735820,46589.213579,26537.927390,44950.795545,84566.353044,55040.003776,79532.514173,NaN

## 19. เปรียบเทียบก่อนและหลังปรับปรุงข้อมูล 
เราสามารถเปรียบเทียบขนาดข้อมูลก่อนและหลังการปรับปรุงได้

In [44]:
print("Raw data shape:", farmer_raw_df.shape) 
print("Clean data shape:", farmer_analysis_df.shape)

Raw data shape: (95, 16)
Clean data shape: (95, 21)

สร้างตารางสรุปจำนวนค่าว่างของ dataset สุดท้าย

In [45]:
final_missing_summary = pd.DataFrame({ 
    "column": farmer_analysis_df.columns, 
    "missing_count": farmer_analysis_df.isna().sum().values, 
    "missing_percent": (farmer_analysis_df.isna().mean() * 100).round(2).values }
) 

final_missing_summary.sort_values("missing_percent", ascending=False)

                    column  missing_count  missing_percent
3            province_code             28            29.47
19              updated_at             15            15.79
0          department_code              0             0.00
2                person_id              0             0.00
1               department              0             0.00
4                 province              0             0.00
5                 district              0             0.00
7                is_farmer              0             0.00
6              subdistrict              0             0.00
9          main_occupation              0             0.00
10      income_agriculture              0             0.00
11  income_non_agriculture              0             0.00
8              farmer_type              0             0.00
12        debt_agriculture              0             0.00
13    debt_non_agriculture              0             0.00
15              total_debt              0             0.00
14            total_income              0             0.00
16              net_income              0             0.00
17   debt_more_than_income              0             0.00
18              debt_level              0             0.00
20            source_sheet              0             0.00

## 20. Data Quality Improvement Checklist 
เมื่อพัฒนาคุณภาพข้อมูล ควรตรวจสอบว่าเราได้ทำสิ่งต่อไปนี้หรือยัง 
| สิ่งที่ต้องทำ | ตัวอย่างในบทนี้ | 
|---|---| 
| เก็บข้อมูลดิบไว้ | `farmer_raw_df` | 
| สร้างสำเนาก่อนแก้ไข | `farmer_clean_df = farmer_raw_df.copy()` | 
| ตั้งชื่อ column ให้อ่านง่าย | `rename()` | 
| ปรับ dtype | `astype()`, `pd.to_datetime()` | 
| จัดการค่าว่าง | `fillna()` | 
| ตรวจข้อมูลซ้ำ | `duplicated()`, `drop_duplicates()` | 
| ปรับข้อความ | `.str.strip()` | 
| สร้างตัวแปรใหม่ | `total_income`, `total_debt`, `net_income` | 
| สร้าง flag | `debt_more_than_income` | 
| จัดกลุ่มข้อมูล | `debt_level` | 
| สร้าง dataset สุดท้าย | `farmer_analysis_df` |

## 21. ข้อควรระวังในการพัฒนาคุณภาพข้อมูล 
การพัฒนาคุณภาพข้อมูลควรมีเหตุผลรองรับเสมอ 

ตัวอย่างข้อควรระวัง 
- ไม่ควรลบข้อมูลเพียงเพราะมีค่าว่าง โดยไม่เข้าใจว่าค่าว่างหมายถึงอะไร 
- ไม่ควรเติมค่าว่างเป็น 0 หากไม่แน่ใจว่าค่าว่างหมายถึงไม่มีค่า 
- ไม่ควรลบข้อมูลซ้ำตามรหัส หากรหัสนั้นอาจปรากฏได้หลายครั้งตามบริบท 
- ไม่ควรเปลี่ยน category โดยไม่ตรวจสอบความหมายกับเจ้าของข้อมูล 
- ควรเก็บข้อมูลดิบไว้เสมอ เพื่อให้ตรวจสอบย้อนกลับได้

# แบบฝึกหัดท้ายบท
แบบฝึกหัดท้ายบทนี้จำลองสถานการณ์การพัฒนาคุณภาพข้อมูลในงานจริง 

ให้ใช้ DataFrame `farmer_raw_df` ที่เตรียมไว้แล้วเป็นข้อมูลตั้งต้น

## แบบฝึกหัดที่ 1: สร้าง function สำหรับปรับชื่อ column และ dtype
ทีมมี `farmer_raw_df` ที่เตรียมมาจากไฟล์ Excel แล้ว 

ขั้นตอนแรกของการพัฒนาคุณภาพข้อมูลคือทำให้ชื่อ column และ dtype 

อยู่ในรูปแบบมาตรฐานเดียวกันทุกครั้ง

### ข้อกำหนด
ให้สร้าง function ชื่อ `standardize_farmer_columns()` โดยมี parameter ดังนี้ 

```python 
def standardize_farmer_columns(df): 
    ... 
```

function นี้ต้องทำงานดังนี้ 
1. สร้างสำเนา DataFrame ด้วย `.copy()` 
2. เปลี่ยนชื่อ column ดังนี้ 
- `pid` เป็น `person_id` 
- `amphur` เป็น `district` 
- `tambon` เป็น `subdistrict` 
- `income_in` เป็น `income_agriculture` 
- `income_out` เป็น `income_non_agriculture` 
- `debts_in` เป็น `debt_agriculture` 
- `debts_out` เป็น `debt_non_agriculture` 
3. แปลง column รหัสต่อไปนี้เป็น string 
- `person_id` 
- `province_code` 
- `department_code` 
4. แปลง `updated_at` เป็น datetime โดยใช้ `pd.to_datetime(errors="coerce")` 
5. return DataFrame ที่ปรับแล้ว หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `farmer_raw_df`

```python 
farmer_step1_df = standardize_farmer_columns(farmer_raw_df) 
```

In [46]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 2: สร้าง function สำหรับจัดการค่าว่างและข้อความ
หลังจากปรับชื่อ column แล้ว ทีมต้องการจัดการค่าว่างและข้อความให้สม่ำเสมอ 

ขั้นตอนนี้ต้องทำซ้ำได้ เพราะเมื่อมีข้อมูลรอบใหม่เข้ามา จะต้องใช้ logic เดิมอีกครั้ง

### ข้อกำหนด
ให้สร้าง function ชื่อ `clean_farmer_missing_and_text()` โดยมี parameter ดังนี้ 

```python 
def clean_farmer_missing_and_text(df): 
    ... 
```

function นี้ต้องทำงานดังนี้ 
1. สร้างสำเนา DataFrame ด้วย `.copy()` 
2. เติมค่าว่างใน column เชิงหมวดหมู่ด้วย `"Unknown"` 
3. เติมค่าว่างใน column ตัวเลขรายได้และหนี้สินด้วย `0` 
4. ใช้ loop และ `.str.strip()` เพื่อตัดช่องว่างหน้าและหลังใน column ข้อความ 
5. return DataFrame ที่ปรับแล้ว 

#### column เชิงหมวดหมู่ที่แนะนำ 

```python 
[ 
    "farmer_type", 
    "main_occupation", 
    "province", 
    "district", 
    "subdistrict" 
] 
```

#### column ตัวเลขที่แนะนำ 

```python 
[ 
    "income_agriculture", 
    "income_non_agriculture", 
    "debt_agriculture", 
    "debt_non_agriculture" 
] 
``` 

#### column ข้อความที่แนะนำ 

```python 
[ 
    "department", 
    "province", 
    "district", 
    "subdistrict", 
    "farmer_type", 
    "main_occupation", 
    "source_sheet" 
] 
``` 

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `farmer_step1_df` 

```python 
farmer_step2_df = clean_farmer_missing_and_text(farmer_step1_df) 
```

In [47]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 3: สร้าง function สำหรับจัดการข้อมูลซ้ำ 

ทีมต้องการลบ row ที่ซ้ำกันทุก column 

แต่ยังไม่ต้องลบข้อมูลซ้ำตาม `person_id` 

เพราะคนหนึ่งคนอาจปรากฏได้ในหลาย sheet หรือหลายหน่วยงาน 

### ข้อกำหนด 
ให้สร้าง function ชื่อ `remove_exact_duplicates()` 

โดยมี parameter ดังนี้ 

```python 
def remove_exact_duplicates(df): 
    ... 
```

function นี้ต้องทำงานดังนี้ 
1. สร้างสำเนา DataFrame ด้วย `.copy()` 
2. นับจำนวน row ที่ซ้ำกันทุก column ก่อนลบ 
3. ลบ row ที่ซ้ำกันทุก column ด้วย `drop_duplicates()` 
4. พิมพ์จำนวน row ที่ถูกลบ 
5. return DataFrame หลังลบข้อมูลซ้ำ ฃ

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `farmer_step2_df`

```python 
farmer_step3_df = remove_exact_duplicates(farmer_step2_df) 
```

In [48]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 4: สร้าง function สำหรับสร้างตัวแปรวิเคราะห์
ทีมต้องการสร้างตัวแปรใหม่จากข้อมูลรายได้และหนี้สิน เพื่อใช้วิเคราะห์ความเปราะบางเบื้องต้น

### ข้อกำหนด
ให้สร้าง function ชื่อ `create_farmer_analysis_features()` 

โดยมี parameter ดังนี้ 

```python 
def create_farmer_analysis_features(df): 
    ... 
```

function นี้ต้องทำงานดังนี้ 
1. สร้างสำเนา DataFrame ด้วย `.copy()` 
2. สร้าง `total_income` 
3. สร้าง `total_debt` 
4. สร้าง `net_income` 
5. สร้าง `debt_more_than_income` 
6. สร้าง `debt_level` จากเงื่อนไข 
- `No debt` ถ้า `total_debt == 0` 
- `Low debt` ถ้า `total_debt <= 50000` 
- `Medium debt` ถ้า `total_debt <= 200000` 
- `High debt` ถ้ามากกว่า 200000 
7. return DataFrame ที่มี column ใหม่แล้ว 

หลังจากสร้าง function แล้ว ให้เรียกใช้กับ `farmer_step3_df`

```python 
farmer_step4_df = create_farmer_analysis_features(farmer_step3_df) 
```

In [49]:
# เขียนคำตอบของคุณใน Cell นี้

## แบบฝึกหัดที่ 5: สร้าง data quality improvement pipeline
หลังจากสร้าง function ย่อยแล้ว ทีมต้องการ function หลักที่เรียกใช้ทุกขั้นตอน 

เพื่อสร้าง dataset พร้อมวิเคราะห์จาก `farmer_raw_df`

### ข้อกำหนด
ให้สร้าง function ชื่อ `prepare_farmer_analysis_dataset()` โดยมี parameter ดังนี้

```python 
def prepare_farmer_analysis_dataset(raw_df): 
    ... 
```

function นี้ต้องทำงานดังนี้ 
1. เรียกใช้ `standardize_farmer_columns()` 
2. เรียกใช้ `clean_farmer_missing_and_text()` 
3. เรียกใช้ `remove_exact_duplicates()`
4. เรียกใช้ `create_farmer_analysis_features()` 
5. เลือกเฉพาะ column สุดท้ายสำหรับวิเคราะห์ 
6. return DataFrame สุดท้าย

column สุดท้ายสำหรับวิเคราะห์ คือ

```python 
analysis_columns = [ 
    "department_code", 
    "department", 
    "person_id", 
    "province_code", 
    "province", 
    "district", 
    "subdistrict", 
    "is_farmer", 
    "farmer_type", 
    "main_occupation", 
    "income_agriculture", 
    "income_non_agriculture", 
    "debt_agriculture", 
    "debt_non_agriculture", 
    "total_income", 
    "total_debt", 
    "net_income", 
    "debt_more_than_income", 
    "debt_level", 
    "updated_at", 
    "source_sheet" 
] 
```

หลังจากสร้าง function แล้ว ให้เรียกใช้ดังนี้ 

```python 
farmer_analysis_df = prepare_farmer_analysis_dataset(farmer_raw_df) 
```

In [51]:
# เขียนคำตอบของคุณใน Markdown Cell นี้