# บทที่ 1: Python สำหรับงานข้อมูล

ในบทนี้ เราจะทำความเข้าใจว่า **Python มีบทบาทอย่างไรในงานข้อมูล** และช่วยเปลี่ยนงานที่เคยทำด้วย Excel ให้เป็นกระบวนการที่ชัดเจน ตรวจสอบได้ และทำซ้ำได้อย่างไร

บทนี้ยังไม่เน้นการจดจำไวยากรณ์ของ Python แต่เน้นให้ผู้เรียนเห็นภาพรวมของการนำ Python มาใช้กับงาน เช่น

- นำเข้าข้อมูล
- ตรวจสอบข้อมูล
- ทำความสะอาดข้อมูล
- แปลงและสรุปข้อมูล
- ส่งออกผลลัพธ์
- ทำขั้นตอนเดิมซ้ำกับข้อมูลชุดใหม่

Python ไม่จำเป็นต้องแทนที่ Excel ในทุกงาน แต่สามารถใช้เสริม Excel เมื่องานมีข้อมูลจำนวนมาก มีหลายไฟล์ หรือต้องทำขั้นตอนเดิมซ้ำเป็นประจำ

## ผลการเรียนรู้ที่คาดหวัง

เมื่อเรียนจบบทนี้ ผู้เรียนจะสามารถ

1. อธิบายบทบาทของ Python ในงานข้อมูลได้
2. เลือกใช้ Excel และ Python ให้เหมาะกับลักษณะงานได้
3. อธิบาย workflow พื้นฐานของงานข้อมูลด้วย Python ได้
4. อธิบายประโยชน์ของการสร้างกระบวนการที่ตรวจสอบและทำซ้ำได้

## ลำดับเนื้อหา

บทเรียนนี้ประกอบด้วยหัวข้อต่อไปนี้

1. ทำไมคนทำงานข้อมูลจึงใช้ Python
2. Excel และ Python เหมาะกับงานแบบใด
3. Workflow พื้นฐานของงานข้อมูลด้วย Python
4. Reproducibility: การทำงานที่ตรวจสอบและทำซ้ำได้
5. Python ในบทบาทต่าง ๆ ของงานข้อมูล
6. Python libraries ที่ใช้ในงานข้อมูล
7. ตัวอย่างจากงาน Excel สู่ Python workflow
8. แบบฝึกหัดท้ายบท

## 1. ทำไมคนทำงานข้อมูลจึงใช้ Python

Python เป็นเครื่องมือที่ได้รับความนิยมในงานข้อมูล เพราะมีจุดเด่นดังนี้

- รูปแบบคำสั่งอ่านค่อนข้างง่าย
- มีเครื่องมือสำหรับจัดการและวิเคราะห์ข้อมูลจำนวนมาก
- ใช้ทำงานซ้ำตามขั้นตอนเดิมได้
- ทำงานกับไฟล์หลายประเภทได้
- เชื่อมต่อกับฐานข้อมูลและ API ได้
- ใช้ได้ตั้งแต่งานวิเคราะห์ข้อมูลไปจนถึง Machine Learning
- สามารถพัฒนาเป็นกระบวนการอัตโนมัติได้

สำหรับผู้ที่คุ้นเคยกับ Excel อยู่แล้ว Python ไม่จำเป็นต้องเข้ามาแทน Excel ทั้งหมด แต่เหมาะกับงานที่ Excel เริ่มจัดการได้ยากหรือมีขั้นตอนซ้ำจำนวนมาก

### ตัวอย่างสถานการณ์ที่ Python ช่วยได้ดี

สมมติว่าเราได้รับไฟล์ข้อมูลรายเดือนจากหลายพื้นที่ และต้องทำขั้นตอนต่อไปนี้

1. เปิดไฟล์จากทุกพื้นที่
2. รวมข้อมูลให้อยู่ในตารางเดียวกัน
3. ตรวจสอบข้อมูลที่ไม่ครบถ้วน
4. ลบข้อมูลซ้ำ
5. สร้างคอลัมน์คำนวณ
6. สรุปข้อมูลตามจังหวัดหรือประเภทผู้รับบริการ
7. ส่งออกเป็นรายงานใหม่

หากทำด้วย Excel เราอาจต้องเปิดหลายไฟล์ คัดลอกข้อมูล วางสูตร สร้าง PivotTable และบันทึกรายงานใหม่ทุกเดือน

หากใช้ Python เราสามารถเขียนขั้นตอนไว้ครั้งเดียว แล้วนำกลับมาใช้กับข้อมูลของเดือนถัดไปได้

## 2. Excel และ Python เหมาะกับงานแบบใด

Excel และ Python ต่างเป็นเครื่องมือที่มีประโยชน์ แต่เหมาะกับลักษณะงานต่างกัน

Excel เหมาะกับงานที่ต้องเปิดดู แก้ไข หรือตรวจสอบข้อมูลด้วยสายตาอย่างรวดเร็ว

Python เหมาะกับงานที่มีหลายขั้นตอน ต้องทำซ้ำ ใช้ข้อมูลจำนวนมาก หรือต้องการบันทึกขั้นตอนอย่างชัดเจน

### เปรียบเทียบ Excel กับ Python ในงานข้อมูล

| ประเด็น | Excel | Python |
|---|---|---|
| การเปิดดูข้อมูลอย่างรวดเร็ว | สะดวกมาก | ดูได้ผ่านตารางหรือคำสั่ง |
| การแก้ไขข้อมูลด้วยมือ | ทำได้สะดวก | ไม่ใช่จุดเด่นหลัก |
| การทำงานซ้ำทุกเดือน | อาจต้องคัดลอกและทำขั้นตอนเดิม | รัน workflow เดิมกับข้อมูลใหม่ |
| การตรวจสอบย้อนหลัง | ตรวจจากสูตรและไฟล์ | ตรวจจากโค้ดตามลำดับ |
| การทำงานกับหลายไฟล์ | เริ่มซับซ้อนเมื่อไฟล์มีจำนวนมาก | เหมาะกับการประมวลผลหลายไฟล์ |
| การทำงานกับข้อมูลจำนวนมาก | มีข้อจำกัดตามขนาดและเครื่อง | รองรับและต่อยอดได้มากกว่า |
| การเชื่อมต่อฐานข้อมูลหรือ API | ทำได้ในบางกรณี | ทำได้ยืดหยุ่น |
| Machine Learning | ไม่ใช่จุดเด่นหลัก | มีเครื่องมือรองรับโดยตรง |

### ไม่จำเป็นต้องเลือกเพียงเครื่องมือเดียว

ในการทำงานจริง เราสามารถใช้ Excel และ Python ร่วมกันได้ เช่น

1. ใช้ Python รวมและทำความสะอาดข้อมูล
2. ส่งออกผลลัพธ์เป็นไฟล์ Excel
3. ใช้ Excel ตรวจสอบข้อมูลหรือจัดรูปแบบรายงาน
4. นำขั้นตอนที่ต้องทำซ้ำกลับไปทำใน Python

สิ่งสำคัญจึงไม่ใช่ว่าเครื่องมือใดดีกว่าเสมอไป แต่คือการเลือกเครื่องมือให้เหมาะกับงาน

## 3. Workflow พื้นฐานของงานข้อมูลด้วย Python

งานข้อมูลด้วย Python มักดำเนินไปตามลำดับต่อไปนี้

1. **Import libraries** — เตรียมเครื่องมือที่ต้องใช้
2. **Load data** — นำเข้าข้อมูล
3. **Inspect data** — ตรวจสอบโครงสร้างและคุณภาพเบื้องต้น
4. **Clean data** — แก้ไขข้อมูลที่ไม่พร้อมใช้งาน
5. **Transform data** — สร้างหรือเปลี่ยนรูปข้อมูล
6. **Analyze data** — คำนวณและสรุปผล
7. **Present or export results** — นำเสนอหรือส่งออกผลลัพธ์

ลำดับอาจปรับเปลี่ยนตามลักษณะงาน แต่ควรจัดขั้นตอนให้ชัดเจนและสามารถตรวจสอบได้

### เปรียบเทียบ Workflow ใน Excel กับ Python

| ขั้นตอน | ตัวอย่างใน Excel | ตัวอย่างใน Python |
|---|---|---|
| เตรียมเครื่องมือ | เปิดโปรแกรมหรือ Add-in | Import library |
| นำเข้าข้อมูล | เปิดไฟล์หรือ Import Data | ใช้คำสั่งอ่านไฟล์ |
| ตรวจสอบข้อมูล | เลื่อนดูตารางและใช้ Filter | ตรวจจำนวนแถว คอลัมน์ และชนิดข้อมูล |
| ทำความสะอาด | ลบแถว แก้ข้อความ หรือ Find & Replace | เขียนคำสั่งทำความสะอาด |
| แปลงข้อมูล | ใช้สูตรสร้างคอลัมน์ | สร้างคอลัมน์ด้วยโค้ด |
| วิเคราะห์ | ใช้สูตร Filter หรือ PivotTable | ใช้คำสั่งกรองและสรุปข้อมูล |
| ส่งออก | Save As หรือ Copy ไปไฟล์ใหม่ | ใช้คำสั่งส่งออก Excel หรือ CSV |

### ตัวอย่าง Workflow สำหรับข้อมูลแบบสำรวจ

สมมติว่าเราได้รับข้อมูลแบบสำรวจจากหลายพื้นที่

Workflow อาจประกอบด้วย

1. อ่านไฟล์ข้อมูลจากทุกพื้นที่
2. รวมข้อมูลเป็นตารางเดียว
3. ตรวจสอบจำนวนแถวและชื่อคอลัมน์
4. ตรวจสอบค่าว่างและข้อมูลซ้ำ
5. ทำให้ชื่อพื้นที่มีรูปแบบเดียวกัน
6. สรุปจำนวนผู้ตอบตามจังหวัด
7. ส่งออกตารางสรุปเป็นไฟล์รายงาน

เมื่อจัดขั้นตอนเป็น workflow เราจะเห็นได้ชัดว่าข้อมูลผ่านการเปลี่ยนแปลงใดบ้างก่อนกลายเป็นรายงาน

## 4. Reproducibility: การทำงานที่ตรวจสอบและทำซ้ำได้

**Reproducibility** ในบริบทของบทเรียนนี้ หมายถึง การจัดกระบวนการทำงานให้สามารถนำข้อมูลชุดเดิมหรือข้อมูลชุดใหม่ที่มีโครงสร้างเดียวกันมาประมวลผลซ้ำตามขั้นตอนเดิมได้

กระบวนการที่ดีควรตอบคำถามได้ว่า

- ข้อมูลมาจากที่ใด
- ตรวจสอบข้อมูลอย่างไร
- แก้ไขหรือลบข้อมูลใด
- ใช้สูตรหรือเงื่อนไขอะไร
- ได้ผลลัพธ์จากขั้นตอนใด
- หากได้รับข้อมูลเดือนใหม่ จะรันกระบวนการเดิมอย่างไร

### ปัญหาที่อาจเกิดขึ้นเมื่อทำงานด้วยมือ

สมมติว่าเราต้องสรุปรายงานด้วย Excel ทุกเดือน ปัญหาที่อาจเกิดขึ้น ได้แก่

- คัดลอกข้อมูลมาไม่ครบ
- วางข้อมูลผิดตำแหน่ง
- สูตรไม่ได้ลากลงมาครบทุกแถว
- ใช้ Filter ค้างไว้โดยไม่รู้ตัว
- PivotTable ไม่ได้ Refresh
- แก้ไขข้อมูลต้นฉบับโดยไม่บันทึกขั้นตอน
- มีไฟล์รายงานหลายเวอร์ชันจนไม่แน่ใจว่าไฟล์ใดล่าสุด
- ผู้ทำงานคนอื่นไม่ทราบว่ารายงานถูกคำนวณอย่างไร

Python ช่วยลดความเสี่ยงเหล่านี้ได้ เพราะขั้นตอนต่าง ๆ สามารถเขียนและเก็บไว้เป็นโค้ด

### ตัวอย่างแนวคิดการทำซ้ำ

สมมติว่าในแต่ละเดือนเราได้รับไฟล์ต่อไปนี้

```text
survey_2026_01.csv
survey_2026_02.csv
survey_2026_03.csv
```

หากไฟล์ทั้งสามมีโครงสร้างเดียวกัน เราสามารถใช้ workflow เดิมในการ

1. อ่านไฟล์
2. ตรวจสอบข้อมูล
3. กรองข้อมูล
4. สรุปผล
5. ส่งออกรายงาน

สิ่งที่เปลี่ยนอาจมีเพียงชื่อไฟล์หรือเดือนที่ต้องการวิเคราะห์ โดยไม่จำเป็นต้องสร้างขั้นตอนใหม่ทั้งหมด

## 5. Python ในบทบาทต่าง ๆ ของงานข้อมูล

Python ถูกนำไปใช้แตกต่างกันตามหน้าที่ของผู้ปฏิบัติงาน

บทบาทที่พบได้บ่อย ได้แก่

- Data Analyst
- Data Engineer
- Data Scientist

แต่ละบทบาทมีเป้าหมายต่างกัน แต่ใช้พื้นฐาน Python และการจัดการข้อมูลร่วมกัน

### Data Analyst

Data Analyst ใช้ Python เพื่อ

- อ่านข้อมูลจาก Excel, CSV หรือฐานข้อมูล
- ตรวจสอบคุณภาพข้อมูลเบื้องต้น
- ทำความสะอาดข้อมูล
- กรองข้อมูล
- สร้างคอลัมน์คำนวณ
- สรุปข้อมูลตามกลุ่ม
- สร้างกราฟ
- จัดทำตารางหรือรายงาน

Python ช่วยให้กระบวนการวิเคราะห์มีขั้นตอนชัดเจนและทำซ้ำได้

### Data Engineer

Data Engineer ใช้ Python เพื่อ

- รับข้อมูลจากหลายแหล่ง
- รวมข้อมูลจากหลายไฟล์
- เชื่อมต่อฐานข้อมูล
- ดึงข้อมูลจาก API
- ตรวจสอบและแปลงรูปแบบข้อมูล
- สร้าง Data Pipeline
- ทำงานแบบอัตโนมัติ
- จัดการ Error และบันทึก Log

Python ช่วยให้ข้อมูลเคลื่อนจากแหล่งต้นทางไปยังระบบปลายทางอย่างเป็นขั้นตอน

### Data Scientist

Data Scientist ใช้ Python เพื่อ

- สำรวจข้อมูลเชิงลึก
- วิเคราะห์ความสัมพันธ์ของตัวแปร
- เตรียมข้อมูลสำหรับสร้างแบบจำลอง
- สร้างตัวแปรหรือ Feature
- ฝึก Machine Learning Model
- ประเมินผล Model
- ทดลองสมมติฐาน
- อธิบายผลลัพธ์ด้วยตารางและกราฟ

Python ช่วยสนับสนุนกระบวนการทดลองและสร้างแบบจำลองจากข้อมูล

### ภาพรวมการใช้ Python ตามบทบาท

| บทบาท | เป้าหมายหลัก | ตัวอย่างงาน |
|---|---|---|
| Data Analyst | วิเคราะห์และสื่อสารผล | สรุปข้อมูล สร้างกราฟ จัดทำรายงาน |
| Data Engineer | จัดการการไหลของข้อมูล | รวมไฟล์ เชื่อมต่อระบบ สร้าง Pipeline |
| Data Scientist | ทดลองและสร้างแบบจำลอง | วิเคราะห์เชิงสถิติและ Machine Learning |

พื้นฐานที่ทั้งสามบทบาทใช้ร่วมกัน ได้แก่

- การเข้าใจชนิดและโครงสร้างข้อมูล
- การเขียนคำสั่งตามลำดับ
- การใช้เงื่อนไข
- การทำงานซ้ำ
- การสร้าง Function
- การจัดการข้อมูลตาราง

## 6. Python Libraries สำหรับงานข้อมูล

**Library** คือชุดเครื่องมือหรือคำสั่งที่ถูกพัฒนาไว้ให้เรานำมาใช้งาน โดยไม่ต้องเขียนทุกอย่างขึ้นใหม่ด้วยตนเอง

Python มี Library สำหรับงานข้อมูลหลายประเภท เช่น การจัดการตาราง การคำนวณ การสร้างกราฟ การเชื่อมต่อระบบ และ Machine Learning

### Library ที่พบได้บ่อยในงานข้อมูล

| Library | ตัวอย่างการใช้งาน |
|---|---|
| `pandas` | จัดการข้อมูลตารางจาก Excel และ CSV |
| `numpy` | คำนวณเชิงตัวเลขและจัดการ Array |
| `matplotlib` | สร้างกราฟพื้นฐาน |
| `seaborn` | สร้างกราฟเพื่อสำรวจข้อมูลเชิงสถิติ |
| `scikit-learn` | สร้างและประเมิน Machine Learning Model |
| `requests` | รับข้อมูลจาก Web API |
| `sqlalchemy` | เชื่อมต่อและทำงานกับฐานข้อมูล |

ในหลักสูตรนี้ เราจะเน้น Python พื้นฐานและ `pandas` สำหรับจัดการข้อมูลตาราง ส่วน Library อื่นจะเรียนรู้ตามความเหมาะสมของแต่ละหัวข้อ

### การนำ Library มาใช้

ก่อนใช้ Library เราต้องนำ Library นั้นเข้ามาในโปรแกรมด้วยคำสั่ง `import`

ตัวอย่างการนำ `pandas` มาใช้

In [9]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 37.7 MB/s  0:00:006m0:00:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 36.4 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd

คำสั่งด้านบนประกอบด้วย

- `import pandas` หมายถึง นำ Library ชื่อ `pandas` มาใช้งาน
- `as pd` หมายถึง กำหนดชื่อย่อของ `pandas` เป็น `pd`

การใช้ชื่อย่อช่วยให้เขียนคำสั่งได้สั้นลง เช่น

```python
pd.DataFrame(...)
pd.read_csv(...)
pd.read_excel(...)
```

ในบทนี้ยังไม่จำเป็นต้องจำคำสั่งทั้งหมด แต่ควรรู้ว่า `pd` หมายถึง Library `pandas`

## 7. ตัวอย่างจากงาน Excel สู่ Python Workflow

สมมติว่าเรามีข้อมูลยอดขายดังนี้

| order_id | product | region | sales |
|---:|---|---|---:|
| 1001 | Keyboard | Bangkok | 1200 |
| 1002 | Mouse | Chiang Mai | 450 |
| 1003 | Monitor | Bangkok | 5200 |
| 1004 | Keyboard | Khon Kaen | 1150 |
| 1005 | Mouse | Bangkok | 500 |

ใน Excel เราอาจทำงานตามขั้นตอนต่อไปนี้

1. เปิดไฟล์
2. ตรวจดูข้อมูล
3. Filter เฉพาะบางพื้นที่
4. สรุปยอดขายตามสินค้า
5. สร้าง PivotTable
6. บันทึกผลลัพธ์

ต่อไปเป็นตัวอย่างการเขียนขั้นตอนเดียวกันด้วย Python

### ขั้นตอนที่ 1: เตรียมและโหลดข้อมูลตัวอย่าง

ตัวอย่างนี้สร้างข้อมูลขึ้นภายใน Notebook เพื่อให้เห็นภาพรวมของ DataFrame

ยังไม่จำเป็นต้องเข้าใจรายละเอียดของทุกคำสั่ง เพราะการสร้างและจัดการ DataFrame จะเรียนอย่างละเอียดในบทถัดไป

In [ ]:
import pandas as pd

sales_data = pd.DataFrame(
    {
        "order_id": [1001, 1002, 1003, 1004, 1005],
        "product": [
            "Keyboard",
            "Mouse",
            "Monitor",
            "Keyboard",
            "Mouse",
        ],
        "region": [
            "Bangkok",
            "Chiang Mai",
            "Bangkok",
            "Khon Kaen",
            "Bangkok",
        ],
        "sales": [1200, 450, 5200, 1150, 500],
    }
)

sales_data

   order_id   product      region  sales
0      1001  Keyboard     Bangkok   1200
1      1002     Mouse  Chiang Mai    450
2      1003   Monitor     Bangkok   5200
3      1004  Keyboard   Khon Kaen   1150
4      1005     Mouse     Bangkok    500

ผลลัพธ์แสดงข้อมูลในรูปตารางที่เรียกว่า **DataFrame**

DataFrame มีลักษณะคล้ายตารางใน Excel โดยประกอบด้วย

- แถว
- คอลัมน์
- ชื่อคอลัมน์
- ค่าของข้อมูล

### ขั้นตอนที่ 2: ตรวจสอบข้อมูล

ก่อนวิเคราะห์ข้อมูล เราควรตรวจสอบโครงสร้างและตัวอย่างข้อมูลก่อน

In [ ]:
sales_data.shape

(5, 4)

`.shape` แสดงจำนวนแถวและจำนวนคอลัมน์ในรูปแบบ

```python
(number_of_rows, number_of_columns)
```

ผลลัพธ์ `(5, 4)` หมายความว่า ข้อมูลมี 5 แถวและ 4 คอลัมน์

In [6]:
sales_data.head()

   order_id   product      region  sales
0      1001  Keyboard     Bangkok   1200
1      1002     Mouse  Chiang Mai    450
2      1003   Monitor     Bangkok   5200
3      1004  Keyboard   Khon Kaen   1150
4      1005     Mouse     Bangkok    500

`.head()` ใช้ดูข้อมูลส่วนบนของตาราง

ในงานจริง ข้อมูลอาจมีหลายพันหรือหลายล้านแถว จึงควรดูตัวอย่างข้อมูลบางส่วนก่อนแทนการเปิดดูข้อมูลทั้งหมด

### ขั้นตอนที่ 3: กรองข้อมูล

สมมติว่าต้องการดูเฉพาะรายการขายใน Bangkok

การทำงานนี้คล้ายกับการใช้ Filter ใน Excel

In [ ]:
bangkok_sales = sales_data[
    sales_data["region"] == "Bangkok"
]

bangkok_sales

   order_id   product   region  sales
0      1001  Keyboard  Bangkok   1200
2      1003   Monitor  Bangkok   5200
4      1005     Mouse  Bangkok    500

โค้ดด้านบนเลือกเฉพาะแถวที่คอลัมน์ `region` มีค่าเท่ากับ `"Bangkok"`

ในบทนี้ให้สังเกตแนวคิดก่อน ส่วนวิธีเขียนเงื่อนไขและกรอง DataFrame จะเรียนอย่างละเอียดภายหลัง

### ขั้นตอนที่ 4: สรุปข้อมูล

สมมติว่าต้องการสรุปยอดขายรวมตามสินค้า

การทำงานนี้มีแนวคิดคล้ายกับ PivotTable ใน Excel

In [ ]:
sales_by_product = (
    sales_data
    .groupby("product")["sales"]
    .sum()
)

sales_by_product

product
Keyboard    2350
Monitor     5200
Mouse        950
Name: sales, dtype: int64

ผลลัพธ์แสดงยอดขายรวมของแต่ละสินค้า

สิ่งสำคัญในตอนนี้คือการเห็นว่า ขั้นตอนที่เคยทำผ่านเมนูหรือ PivotTable ใน Excel สามารถเขียนเป็นคำสั่งที่บันทึกและรันซ้ำได้

### ขั้นตอนที่ 5: ส่งออกผลลัพธ์

เมื่อวิเคราะห์เสร็จแล้ว เราสามารถส่งผลลัพธ์เป็นไฟล์ Excel หรือ CSV ได้

ตัวอย่างคำสั่งสำหรับส่งออกผลลัพธ์เป็น Excel คือ

```python
sales_by_product.to_excel("sales_by_product.xlsx")
```

ในบทนี้ยังไม่จำเป็นต้องรันคำสั่งส่งออก เนื่องจากจะเรียนเรื่องการอ่านและเขียนไฟล์โดยละเอียดในบทต่อไป

In [9]:
# ตัวอย่างคำสั่งสำหรับส่งออกผลลัพธ์เป็น Excel
# ยังไม่จำเป็นต้องรันในบทนี้

# sales_by_product.to_excel("sales_by_product.xlsx")

### สรุป Workflow จากตัวอย่าง

ตัวอย่างข้างต้นประกอบด้วยขั้นตอนดังนี้

1. Import `pandas`
2. สร้างหรือโหลดข้อมูล
3. ตรวจสอบขนาดและตัวอย่างข้อมูล
4. กรองข้อมูลตามเงื่อนไข
5. สรุปข้อมูลตามกลุ่ม
6. เตรียมส่งออกผลลัพธ์

เมื่อมีข้อมูลชุดใหม่ เราสามารถใช้ขั้นตอนเดิมและเปลี่ยนเฉพาะข้อมูลต้นทางหรือเงื่อนไขที่ต้องการวิเคราะห์

# แบบฝึกหัดท้ายบท

แบบฝึกหัดในบทนี้เน้นการทำความเข้าใจแนวคิดของ Python Workflow

ผู้เรียนยังไม่จำเป็นต้องจดจำไวยากรณ์ทั้งหมด แต่ควรฝึกคิดว่า

> งานที่เคยทำผ่านการคลิกและแก้ไขใน Excel สามารถแบ่งออกเป็นขั้นตอนที่ชัดเจนและเขียนเป็นโค้ดได้อย่างไร

ให้ทดลองตอบด้วยตนเองก่อนเปิดดูเฉลย

สำหรับคำถามปลายเปิด เฉลยที่ให้เป็นเพียง **ตัวอย่างคำตอบ** คำตอบของผู้เรียนอาจแตกต่างได้หากมีเหตุผลเหมาะสม

## แบบฝึกหัดที่ 1: วิเคราะห์งาน Excel ที่ทำเป็นประจำ

ให้เลือกงาน Excel ที่คุณทำเป็นประจำ 1 งาน โดยควรเป็นงานที่เกี่ยวข้องกับข้อมูลเชิงสำรวจหรือข้อมูลผู้รับบริการ

ตัวอย่างงาน ได้แก่

- รวมไฟล์แบบสำรวจจากหลายพื้นที่
- กรองข้อมูลเฉพาะผู้ตอบในจังหวัดหนึ่ง
- คำนวณคะแนนรวมจากแบบสอบถาม
- แยกกลุ่มผู้รับบริการตามระดับความต้องการ
- ตรวจสอบและลบข้อมูลซ้ำ
- สรุปจำนวนผู้ตอบตามพื้นที่
- สรุปคะแนนเฉลี่ยของแต่ละประเด็น
- เตรียมข้อมูลก่อนส่งต่อให้ทีมวิเคราะห์

### ข้อ 1.1 งาน Excel ที่เลือกคืออะไร

เขียนชื่อและคำอธิบายสั้น ๆ ของงานที่คุณเลือก

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 1.1
>
> งานที่เลือกคือการรวมไฟล์ข้อมูลแบบสำรวจครัวเรือนจากหลายจังหวัด เพื่อจัดทำตารางสรุปจำนวนครัวเรือนตามจังหวัดและประเภทความต้องการความช่วยเหลือ

### ข้อ 1.2 ข้อมูลต้นทางมาจากไหน

อธิบายแหล่งที่มาของข้อมูล เช่น บุคคล หน่วยงาน ระบบ หรือประเภทไฟล์

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 1.2
>
> ข้อมูลมาจากเจ้าหน้าที่ภาคสนามของแต่ละจังหวัด โดยส่งเป็นไฟล์ Excel จังหวัดละ 1 ไฟล์ผ่านพื้นที่จัดเก็บไฟล์ส่วนกลาง

### ข้อ 1.3 ขั้นตอนที่ทำใน Excel มีอะไรบ้าง

เขียนขั้นตอนตามลำดับตั้งแต่ได้รับข้อมูลจนถึงจัดทำผลลัพธ์

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 1.3
>
> 1. เปิดไฟล์ของแต่ละจังหวัด
> 2. ตรวจสอบชื่อคอลัมน์
> 3. คัดลอกข้อมูลมาต่อกันในไฟล์กลาง
> 4. ตรวจสอบข้อมูลซ้ำ
> 5. กรองข้อมูลที่ไม่สมบูรณ์
> 6. สร้าง PivotTable สรุปจำนวนครัวเรือน
> 7. คัดลอกตารางสรุปไปยัง Sheet รายงาน
> 8. บันทึกเป็นไฟล์ฉบับใหม่

### ข้อ 1.4 ผลลัพธ์สุดท้ายที่ต้องการคืออะไร

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 1.4
>
> ผลลัพธ์ที่ต้องการคือตารางแสดงจำนวนครัวเรือนแยกตามจังหวัดและประเภทความต้องการความช่วยเหลือ พร้อมยอดรวมสำหรับใช้ในรายงานประจำเดือน

### ข้อ 1.5 ขั้นตอนใดที่คิดว่าน่าจะให้ Python ช่วยทำแทนได้

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 1.5
>
> Python สามารถช่วยได้ในขั้นตอนต่อไปนี้
>
> - อ่านไฟล์จากทุกจังหวัด
> - รวมข้อมูลเป็นตารางเดียว
> - ตรวจสอบชื่อคอลัมน์
> - ตรวจสอบข้อมูลซ้ำและค่าว่าง
> - สรุปจำนวนครัวเรือนตามจังหวัด
> - ส่งออกตารางสรุปเป็นไฟล์ใหม่
>
> ส่วนการตรวจสอบความสมเหตุสมผลของข้อมูลบางกรณียังต้องอาศัยความรู้จากผู้ปฏิบัติงาน

## แบบฝึกหัดที่ 2: แปลงขั้นตอน Excel เป็น Python Workflow

พิจารณาสถานการณ์ต่อไปนี้

> คุณได้รับไฟล์ข้อมูลแบบสำรวจจากทีมภาคสนาม  
> ต้องการกรองเฉพาะผู้ตอบแบบสำรวจในพื้นที่ Bangkok  
> จากนั้นสรุปจำนวนผู้ตอบตามประเด็นความต้องการความช่วยเหลือ  
> และส่งออกผลลัพธ์เป็นไฟล์รายงานใหม่

ใน Excel อาจทำตามขั้นตอนดังนี้

1. เปิดไฟล์ข้อมูลแบบสำรวจ
2. ใช้ Filter เลือก `area = Bangkok`
3. สร้าง PivotTable สรุปจำนวนตาม `support_need`
4. คัดลอกผลลัพธ์ไปยัง Sheet ใหม่
5. บันทึกเป็นไฟล์รายงาน

ให้เขียนลำดับ Python Workflow ที่สอดคล้องกับขั้นตอนดังกล่าว โดยยังไม่จำเป็นต้องเขียนโค้ดจริง

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยแบบฝึกหัดที่ 2
>
> Python Workflow ที่สอดคล้องกัน ได้แก่
>
> 1. Import Library ที่ต้องใช้
> 2. อ่านไฟล์ข้อมูลแบบสำรวจ
> 3. ตรวจสอบโครงสร้างและตัวอย่างข้อมูล
> 4. กรองแถวที่ `area` เท่ากับ `"Bangkok"`
> 5. จัดกลุ่มข้อมูลตาม `support_need`
> 6. นับจำนวนผู้ตอบในแต่ละกลุ่ม
> 7. ตรวจสอบตารางสรุป
> 8. ส่งออกผลลัพธ์เป็นไฟล์ Excel หรือ CSV

## แบบฝึกหัดที่ 3: อ่านโค้ด Python Workflow

พิจารณาโค้ดต่อไปนี้

```python
import pandas as pd

survey_data = pd.DataFrame(
    {
        "respondent_id": [1, 2, 3, 4, 5],
        "area": [
            "Bangkok",
            "Chiang Mai",
            "Bangkok",
            "Khon Kaen",
            "Bangkok",
        ],
        "support_need": [
            "Income",
            "Housing",
            "Mental health",
            "Income",
            "Housing",
        ],
    }
)

bangkok_survey = survey_data[
    survey_data["area"] == "Bangkok"
]

need_summary = (
    bangkok_survey
    .groupby("support_need")["respondent_id"]
    .count()
)

need_summary
```

### ข้อ 3.1 โค้ดส่วนใดใช้สร้างข้อมูลตัวอย่าง

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### เฉลยข้อ 3.1
>
> ส่วนที่ใช้สร้างข้อมูลตัวอย่างคือคำสั่ง 
>```python
>survey_data = pd.DataFrame(
>    {
>        "respondent_id": [1, 2, 3, 4, 5],
>        "area": [
>            "Bangkok",
>            "Chiang Mai",
>            "Bangkok",
>            "Khon Kaen",
>            "Bangkok",
>        ],
>        "support_need": [
>            "Income",
>            "Housing",
>            "Mental health",
>            "Income",
>            "Housing",
>        ],
>    }
>)
>```

### ข้อ 3.2 โค้ดส่วนใดคล้ายกับการใช้ Filter ใน Excel

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### เฉลยข้อ 3.2
>
> ส่วนที่คล้ายกับการใช้ Filter คือคำสั่งที่เลือกเฉพาะแถวซึ่ง `area` เท่ากับ `"Bangkok"`
>
>```python
>bangkok_survey = survey_data[
>    survey_data["area"] == "Bangkok"
>]
>```

### ข้อ 3.3 โค้ดส่วนใดคล้ายกับ PivotTable หรือการสรุปจำนวนใน Excel

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### เฉลยข้อ 3.3
>
> ส่วนที่คล้ายกับ PivotTable คือการจัดกลุ่มตาม `support_need` แล้วนับ `respondent_id`
>
>```python
>need_summary = (
>    bangkok_survey
>    .groupby("support_need")["respondent_id"]
>    .count()
>)
>```

### ข้อ 3.4 ผลลัพธ์สุดท้ายช่วยตอบคำถามอะไรในงานสังคมสงเคราะห์

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 3.4
>
> ผลลัพธ์ช่วยตอบว่า ผู้ตอบแบบสำรวจในพื้นที่ Bangkok มีความต้องการความช่วยเหลือแต่ละประเภทจำนวนกี่คน
>
> จากข้อมูลตัวอย่างพบว่า
>
> - Housing มี 2 คน
> - Income มี 1 คน
> - Mental health มี 1 คน
>
> ข้อมูลนี้อาจใช้ประกอบการวางแผนทรัพยากรหรือบริการในแต่ละประเด็นได้ แต่ตัวอย่างมีข้อมูลเพียงเล็กน้อยจึงยังไม่ควรใช้สรุปแทนข้อมูลจริง

### ข้อ 3.5 หากต้องการเปลี่ยนจาก Bangkok เป็นพื้นที่อื่น ควรแก้โค้ดส่วนใด

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### เฉลยข้อ 3.5
>
> ต้องแก้ค่าที่ใช้เปรียบเทียบในเงื่อนไขกรอง จาก `"Bangkok"` เป็นชื่อพื้นที่ที่ต้องการ
>
>```python
>chiang_mai_survey = survey_data[
>    survey_data["area"] == "Chiang Mai"
>]
>```

## แบบฝึกหัดที่ 4: ทดลองปรับ Workflow

ให้รันโค้ดด้านล่าง แล้วเปลี่ยนค่าของ `selected_area` จาก `"Bangkok"` เป็น `"Chiang Mai"`

จากนั้นรันโค้ดใหม่และสังเกตการเปลี่ยนแปลงของผลลัพธ์

In [1]:
import pandas as pd

survey_data = pd.DataFrame(
    {
        "respondent_id": [1, 2, 3, 4, 5],
        "area": [
            "Bangkok",
            "Chiang Mai",
            "Bangkok",
            "Khon Kaen",
            "Bangkok",
        ],
        "support_need": [
            "Income",
            "Housing",
            "Mental health",
            "Income",
            "Housing",
        ],
    }
)

selected_area = "Bangkok"

filtered_survey = survey_data[
    survey_data["area"] == selected_area
]

need_summary = (
    filtered_survey
    .groupby("support_need")["respondent_id"]
    .count()
)

need_summary

support_need
Housing          1
Income           1
Mental health    1
Name: respondent_id, dtype: int64

In [2]:
# เปลี่ยน selected_area แล้วรัน Workflow อีกครั้ง

selected_area = "Chiang Mai"

filtered_survey = survey_data[
    survey_data["area"] == selected_area
]

need_summary = (
    filtered_survey
    .groupby("support_need")["respondent_id"]
    .count()
)

need_summary

support_need
Housing    1
Name: respondent_id, dtype: int64

### ข้อ 4.1 เมื่อเปลี่ยน `selected_area` เป็น `"Chiang Mai"` ผลลัพธ์เปลี่ยนอย่างไร

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### เฉลยข้อ 4.1
>
> ผลลัพธ์เหลือเพียงความต้องการด้าน `Housing` จำนวน 1 คน เพราะข้อมูลตัวอย่างมีผู้ตอบใน Chiang Mai เพียงหนึ่งรายการ

### ข้อ 4.2 Bangkok และ Chiang Mai มีประเด็นความต้องการเหมือนหรือต่างกันอย่างไร

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### เฉลยข้อ 4.2
>
> จากข้อมูลตัวอย่าง
>
> - Bangkok มีความต้องการด้าน Income, Housing และ Mental health
> - Chiang Mai มีความต้องการด้าน Housing เท่านั้น
>
> ทั้งสองพื้นที่มีประเด็น Housing เหมือนกัน แต่ Bangkok มีประเด็นอื่นเพิ่มอีกสองประเภท
>
> อย่างไรก็ตาม ข้อมูลตัวอย่างมีเพียง 5 แถว จึงใช้เพื่อฝึกอ่านผลลัพธ์เท่านั้น ไม่ควรนำไปสรุปสถานการณ์จริงของแต่ละพื้นที่

### ข้อ 4.3 หากทำงานนี้ใน Excel ต้องคลิกหรือเปลี่ยนอะไรบ้าง

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 4.3
>
> ใน Excel อาจต้อง
>
> 1. เปิด Filter ของคอลัมน์พื้นที่
> 2. ยกเลิกการเลือก Bangkok
> 3. เลือก Chiang Mai
> 4. กดตกลง
> 5. Refresh หรือสร้าง PivotTable ใหม่
> 6. ตรวจสอบว่าตารางสรุปอ้างอิงข้อมูลที่กรองล่าสุด

### ข้อ 4.4 หากต้องทำรายงานแบบเดียวกันทุกเดือนหรือทุกพื้นที่ Python Workflow ช่วยลดงานซ้ำอย่างไร

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 4.4
>
> สามารถใช้คำสั่งเดิมในการกรองและสรุปข้อมูล แล้วเปลี่ยนเฉพาะชื่อพื้นที่หรือไฟล์ข้อมูลของเดือนใหม่ จากนั้นรัน Workflow อีกครั้ง โดยไม่ต้องสร้างขั้นตอนใหม่ทั้งหมด

### ข้อ 4.5 หากมีข้อมูลจริงหลายพันรายการ Python มีข้อดีอย่างไรเมื่อเทียบกับการคลิกทำซ้ำใน Excel

-- เขียนคำตอบของคุณใน Markdown Cell นี้ --

> ### ตัวอย่างเฉลยข้อ 4.5
>
> Python มีข้อดีดังนี้
>
> - ประมวลผลข้อมูลจำนวนมากตามคำสั่งเดียวกันได้
> - ลดการคัดลอกและแก้ไขข้อมูลด้วยมือ
> - ใช้เงื่อนไขเดียวกันอย่างสม่ำเสมอ
> - ตรวจสอบย้อนหลังได้ว่าใช้ขั้นตอนใด
> - เปลี่ยนพื้นที่หรือช่วงเวลาแล้วรันซ้ำได้
> - สามารถขยายไปทำงานกับหลายไฟล์ได้
> - ลดความเสี่ยงจากการคลิกหรือเลือก Filter ผิด

## แบบฝึกหัดที่ 5: ระบุบทบาทของ Python ในงานข้อมูล

จากตัวอย่างงานต่อไปนี้ ให้ระบุบทบาทที่ใกล้เคียงที่สุด

เลือกจาก

- Data Analyst
- Data Engineer
- Data Scientist

| งาน | บทบาทที่ใกล้เคียงที่สุด |
|---|---|
| 1. สรุปจำนวนผู้ตอบแบบสำรวจตามพื้นที่และประเภทความต้องการ | |
| 2. ดึงข้อมูลจากระบบแบบฟอร์มออนไลน์ทุกวันและบันทึกลงฐานข้อมูลกลาง | |
| 3. สร้างโมเดลคาดการณ์ว่าครัวเรือนใดมีความเสี่ยงสูง | |
| 4. รวมไฟล์ CSV จากทีมภาคสนามหลายจังหวัดให้เป็นไฟล์เดียว | |
| 5. สร้างกราฟแนวโน้มจำนวนผู้ขอรับความช่วยเหลือรายเดือน | |
| 6. ตรวจสอบความครบถ้วนของข้อมูลก่อนนำเข้า Data Warehouse | |
| 7. วิเคราะห์คะแนนเฉลี่ยความพึงพอใจตามพื้นที่ | |
| 8. สร้าง Pipeline รวมข้อมูลแบบสำรวจจากหลายแหล่งโดยอัตโนมัติ | |

> ### เฉลยแบบฝึกหัดที่ 5
>
> | งาน | บทบาทที่ใกล้เคียงที่สุด | เหตุผล |
> |---|---|---|
> | 1. สรุปจำนวนผู้ตอบแบบสำรวจตามพื้นที่และประเภทความต้องการ | Data Analyst | เน้นการสรุปและวิเคราะห์ข้อมูล |
> | 2. ดึงข้อมูลจากระบบออนไลน์ทุกวันและบันทึกลงฐานข้อมูลกลาง | Data Engineer | เน้นการรับส่งและจัดเก็บข้อมูลอัตโนมัติ |
> | 3. สร้างโมเดลคาดการณ์ว่าครัวเรือนใดมีความเสี่ยงสูง | Data Scientist | เน้นการสร้างแบบจำลองคาดการณ์ |
> | 4. รวมไฟล์ CSV จากหลายจังหวัดให้เป็นไฟล์เดียว | Data Engineer | เน้นการรวบรวมและเตรียมข้อมูลจากหลายแหล่ง |
> | 5. สร้างกราฟแนวโน้มจำนวนผู้ขอรับความช่วยเหลือรายเดือน | Data Analyst | เน้นการวิเคราะห์และนำเสนอผล |
> | 6. ตรวจสอบความครบถ้วนก่อนนำเข้า Data Warehouse | Data Engineer | เป็นส่วนหนึ่งของการควบคุมคุณภาพใน Pipeline |
> | 7. วิเคราะห์คะแนนเฉลี่ยความพึงพอใจตามพื้นที่ | Data Analyst | เน้นการคำนวณและเปรียบเทียบข้อมูล |
> | 8. สร้าง Pipeline รวมข้อมูลจากหลายแหล่งโดยอัตโนมัติ | Data Engineer | เน้นการพัฒนากระบวนการข้อมูลอัตโนมัติ |
>
> การจัดกลุ่มนี้พิจารณาจากเป้าหมายหลักของงาน ในการทำงานจริง งานบางประเภทอาจมีความเกี่ยวข้องกับหลายบทบาท