# บทที่ 1: Python สำหรับงานข้อมูล

ในบทนี้ เราจะทำความเข้าใจว่า **Python ถูกใช้ในงานข้อมูลอย่างไร**

บทนี้ไม่ได้เน้นการเรียน syntax ของ Python แบบละเอียด แต่เน้นให้เห็นภาพรวมว่า Python ช่วยทำให้งานข้อมูลที่เคยทำใน Excel กลายเป็นงานที่

- ทำซ้ำได้
- ตรวจสอบย้อนหลังได้
- ลดความผิดพลาดจากการทำงานด้วยมือ
- รองรับข้อมูลขนาดใหญ่ขึ้น
- เชื่อมต่อกับเครื่องมืออื่นได้ดีขึ้น
- ต่อยอดไปสู่งาน Data Engineering และ Data Science ได้

ในหลักสูตรนี้ Python จะไม่ใช่แค่ “ภาษาเขียนโปรแกรม” แต่จะเป็นเครื่องมือหลักสำหรับการทำงานกับข้อมูล

## ผลการเรียนรู้ที่คาดหวัง

เมื่อเรียนจบบทนี้ ผู้เรียนจะสามารถ

1. อธิบายได้ว่า Python มีบทบาทอย่างไรในงานข้อมูล
2. เปรียบเทียบการทำงานข้อมูลด้วย Excel กับ Python ได้
3. เข้าใจความแตกต่างของการใช้ Python ในบทบาท Data Analyst, Data Engineer และ Data Scientist
4. อธิบาย workflow พื้นฐานของงานวิเคราะห์ข้อมูลด้วย Python ได้
5. เข้าใจแนวคิดเรื่อง reproducibility หรือการทำงานซ้ำได้อย่างเป็นระบบ
6. รู้จัก library สำคัญที่ใช้ในงานข้อมูล เช่น pandas, matplotlib, scikit-learn
7. เห็นตัวอย่างเบื้องต้นของการเปลี่ยนงานที่เคยทำใน Excel มาเป็น Python workflow

## ลำดับเนื้อหา

บทเรียนนี้ประกอบด้วยหัวข้อต่อไปนี้

## 1. ทำไมคนทำงานข้อมูลจึงใช้ Python

Python เป็นหนึ่งในเครื่องมือที่ได้รับความนิยมมากในงานข้อมูล เพราะมีจุดเด่นหลายด้าน

- เขียนอ่านง่าย เหมาะกับผู้เริ่มต้น
- มี library สำหรับงานข้อมูลจำนวนมาก
- ใช้ได้ตั้งแต่งานวิเคราะห์ข้อมูลเบื้องต้นไปจนถึง Machine Learning
- ทำงานซ้ำ ๆ ได้ดี
- เชื่อมต่อกับไฟล์ ฐานข้อมูล API และระบบอื่นได้
- สามารถทำงานร่วมกับเครื่องมือด้านข้อมูลอื่น ๆ ได้หลากหลาย

สำหรับผู้ที่ใช้ Excel มาก่อน Python ไม่ได้จำเป็นต้องมาแทน Excel ทั้งหมดทันที  
แต่ Python ช่วยให้เราทำงานที่ Excel เริ่มไม่สะดวกได้ดีขึ้น

## 2. Excel กับ Python เหมาะกับงานแบบใด

Excel เป็นเครื่องมือที่ดีมากสำหรับงานข้อมูลหลายประเภท โดยเฉพาะงานที่ต้องดูข้อมูลอย่างรวดเร็ว หรือต้องการแก้ไขข้อมูลด้วยตนเอง

แต่เมื่อข้อมูลงานเริ่มมีความซับซ้อนมากขึ้น Python จะเริ่มมีข้อได้เปรียบ

## เปรียบเทียบ Excel กับ Python ในงานข้อมูล

| ประเด็น | Excel | Python |
|---|---|---|
| การดูข้อมูลอย่างรวดเร็ว | ทำได้ดีมาก | ทำได้ดีผ่าน pandas |
| การแก้ไขข้อมูลด้วยมือ | สะดวก | ไม่ใช่จุดเด่นหลัก |
| การทำงานซ้ำทุกวัน/ทุกเดือน | ต้อง copy, paste, refresh หรือใช้ macro | เขียน workflow ให้ทำซ้ำได้ |
| การตรวจสอบขั้นตอนย้อนหลัง | ตรวจสอบได้บางส่วนจากสูตรหรือไฟล์ | ตรวจสอบได้จาก code ทีละขั้น |
| การทำงานกับไฟล์จำนวนมาก | ทำได้ แต่เริ่มยุ่งยาก | ทำได้ดีมาก |
| การทำงานกับข้อมูลขนาดใหญ่ | มีข้อจำกัด | รองรับได้ดีกว่า |
| การเชื่อมต่อฐานข้อมูล/API | ทำได้บางกรณี | ทำได้ยืดหยุ่น |
| การทำ Machine Learning | ไม่ใช่จุดเด่นหลัก | เป็นหนึ่งในเครื่องมือหลัก |

## ตัวอย่างสถานการณ์ที่ Python ช่วยได้ดี

ลองนึกถึงงานที่มักเกิดขึ้นใน Excel เช่น

1. ได้ไฟล์ยอดขายรายเดือนจากหลายสาขา
2. ต้องรวมไฟล์ทั้งหมดเข้าด้วยกัน
3. ต้องลบแถวที่ไม่สมบูรณ์
4. ต้องสร้างคอลัมน์ใหม่ เช่น ยอดขายสุทธิ
5. ต้องสรุปยอดขายตามภูมิภาค
6. ต้องส่งออกเป็นรายงานใหม่ทุกเดือน

ถ้าทำใน Excel เราอาจต้องเปิดหลายไฟล์ copy ข้อมูล วางสูตร สร้าง PivotTable และบันทึกไฟล์ใหม่

ถ้าใช้ Python เราสามารถเขียน workflow เดิมไว้ครั้งเดียว แล้วนำกลับมาใช้ซ้ำได้ทุกเดือน

## 3. Python ในบทบาทต่าง ๆ ของงานข้อมูล

ในหลักสูตรนี้ ผู้เรียนจะเริ่มจากพื้นฐานร่วมกันในวันแรก  
จากนั้นจะแยกต่อยอดตามบทบาทในวันถัดไป

Python ถูกใช้ต่างกันตามหน้าที่ของแต่ละบทบาท

## Data Analyst

Data Analyst ใช้ Python เพื่อ

- อ่านข้อมูลจากไฟล์ Excel, CSV หรือฐานข้อมูล
- ตรวจสอบคุณภาพข้อมูลเบื้องต้น
- ทำความสะอาดข้อมูล
- กรองข้อมูล
- สร้างคอลัมน์คำนวณ
- สรุปข้อมูลด้วย groupby หรือ pivot table
- สร้างกราฟ
- จัดทำรายงาน

สำหรับ Data Analyst, Python มักทำหน้าที่เป็นเครื่องมือที่ช่วยทำงานวิเคราะห์ข้อมูลให้เป็นระบบและทำซ้ำได้

## Data Engineer

Data Engineer ใช้ Python เพื่อ

- อ่านและเขียนข้อมูลจากหลายแหล่ง
- รวมข้อมูลจากหลายไฟล์
- เชื่อมต่อฐานข้อมูล
- ดึงข้อมูลจาก API
- ตรวจสอบและแปลงรูปแบบข้อมูล
- สร้าง data pipeline
- ทำงานแบบอัตโนมัติ
- จัดการ error และ log

สำหรับ Data Engineer, Python มักทำหน้าที่เป็นเครื่องมือสร้างระบบที่ทำให้ข้อมูลไหลจากแหล่งข้อมูลไปยังปลายทางได้อย่างถูกต้อง

## Data Scientist

Data Scientist ใช้ Python เพื่อ

- สำรวจข้อมูลเชิงลึก
- วิเคราะห์ความสัมพันธ์ของตัวแปร
- เตรียมข้อมูลสำหรับสร้างแบบจำลอง
- สร้าง feature
- ฝึก Machine Learning model
- ประเมินผล model
- สร้างกราฟเพื่ออธิบายผลลัพธ์
- ทดลองสมมติฐานด้วยข้อมูล

สำหรับ Data Scientist, Python มักทำหน้าที่เป็นเครื่องมือสำหรับการทดลอง วิเคราะห์ และสร้างแบบจำลองจากข้อมูล

## ภาพรวมการใช้ Python ตามบทบาท

| บทบาท | งานหลัก | ตัวอย่างการใช้ Python |
|---|---|---|
| Data Analyst | วิเคราะห์และสรุปข้อมูล | pandas, visualization, reporting |
| Data Engineer | จัดการการไหลของข้อมูล | file processing, database, API, pipeline |
| Data Scientist | สร้าง insight และ model | statistics, machine learning, model evaluation |

แม้แต่ละบทบาทจะใช้ Python ไม่เหมือนกัน แต่พื้นฐานที่ต้องใช้ร่วมกัน ได้แก่

- การเข้าใจโครงสร้างข้อมูล
- การเขียนคำสั่งอย่างเป็นลำดับ
- การใช้เงื่อนไข
- การทำงานซ้ำ
- การเขียน function
- การอ่านและจัดการข้อมูลตาราง

## 4. Workflow พื้นฐานของงานข้อมูลด้วย Python

งานข้อมูลด้วย Python มักมีลำดับการทำงานคล้ายกัน ไม่ว่าจะเป็นงานของ Data Analyst, Data Engineer หรือ Data Scientist

โดยทั่วไป workflow พื้นฐานประกอบด้วย

1. Import library
2. Load data
3. Inspect data
4. Clean data
5. Transform data
6. Analyze data
7. Present or export results

## Workflow: จาก Excel สู่ Python

| ขั้นตอน | ถ้าทำใน Excel | ถ้าทำใน Python |
|---|---|---|
| Load data | เปิดไฟล์ Excel | ใช้คำสั่งอ่านไฟล์ |
| Inspect data | ดูแถว/คอลัมน์ด้วยสายตา | ใช้คำสั่งตรวจสอบโครงสร้างข้อมูล |
| Clean data | ลบแถว แก้ชื่อคอลัมน์ กรองข้อมูล | เขียนคำสั่ง clean ข้อมูล |
| Transform data | ใส่สูตร สร้างคอลัมน์ใหม่ | สร้างคอลัมน์ใหม่ด้วย code |
| Analyze data | ใช้ Filter, Sort, PivotTable | ใช้ pandas เช่น filter, groupby, pivot_table |
| Export result | Save As หรือ Copy ไปไฟล์ใหม่ | ใช้คำสั่ง export เป็น Excel/CSV |

## 5. Reproducibility คืออะไร

คำว่า **reproducibility** หมายถึง การที่เราสามารถทำงานเดิมซ้ำแล้วได้ผลลัพธ์แบบเดิม โดยมีขั้นตอนที่ชัดเจนและตรวจสอบได้

ในงานข้อมูล เรื่องนี้สำคัญมาก

เพราะหลายครั้งเราต้องตอบคำถาม เช่น

- ข้อมูลนี้มาจากไฟล์ไหน
- ลบข้อมูลแถวใดออกไปบ้าง
- คำนวณตัวเลขนี้อย่างไร
- ใช้เงื่อนไขอะไรในการกรองข้อมูล
- ถ้าได้ไฟล์ใหม่เดือนหน้า จะทำซ้ำอย่างไร

## ตัวอย่างปัญหาที่มักเกิดขึ้นเมื่อทำงานด้วยมือ

สมมติว่าเราต้องสรุปยอดขายทุกเดือนด้วย Excel

อาจเกิดปัญหา เช่น

- ลืม copy ข้อมูลบางแถว
- สูตรบาง cell ไม่ถูก drag ลงมาครบ
- PivotTable ไม่ได้ refresh
- ใช้ filter ค้างไว้โดยไม่รู้ตัว
- แก้ไขข้อมูลต้นฉบับโดยไม่ได้บันทึกขั้นตอน
- ส่งรายงานหลายเวอร์ชันจนไม่แน่ใจว่าไฟล์ไหนคือไฟล์ล่าสุด

Python ช่วยลดปัญหาเหล่านี้ได้ เพราะทุกขั้นตอนถูกเขียนเป็น code และสามารถรันซ้ำได้

## 6. Python Libraries สำหรับงานข้อมูล

Python มี library จำนวนมากที่ช่วยให้ทำงานข้อมูลได้สะดวกขึ้น

Library คือชุดคำสั่งที่มีคนเตรียมไว้ให้เราใช้งาน

เราไม่จำเป็นต้องเขียนทุกอย่างเองตั้งแต่ต้น

## Library สำคัญที่มักใช้ในงานข้อมูล

| Library | ใช้ทำอะไร |
|---|---|
| pandas | จัดการข้อมูลตาราง เช่น Excel หรือ CSV |
| numpy | คำนวณเชิงตัวเลขและจัดการ array |
| matplotlib | สร้างกราฟพื้นฐาน |
| seaborn | สร้างกราฟเชิงสถิติ |
| scikit-learn | สร้าง Machine Learning model |
| requests | ดึงข้อมูลจาก API |
| sqlalchemy | เชื่อมต่อฐานข้อมูล |

ในวันแรกของหลักสูตรนี้ เราจะเน้นที่ Python พื้นฐานและ pandas เบื้องต้น  
ส่วน library อื่น ๆ จะไปต่อยอดในวันที่ 2 และวันที่ 3 ตามบทบาทของผู้เรียน

## การนำ library มาใช้

ก่อนใช้ library ใน Python เราต้อง import library เข้ามาก่อน

ตัวอย่างเช่น ถ้าต้องการใช้ pandas เรามักเขียนว่า

In [2]:
%pip install pandas

Requirement already satisfied: pandas in /workspaces/MSDHS_OJT/.venv/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /workspaces/MSDHS_OJT/.venv/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/MSDHS_OJT/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspaces/MSDHS_OJT/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

คำสั่งด้านบนหมายความว่า

- `import pandas` คือการนำ library ชื่อ pandas มาใช้งาน
- `as pd` คือการตั้งชื่อย่อให้ pandas เพื่อให้เขียนสั้นลง

ในงานข้อมูล เราจะพบคำสั่งนี้บ่อยมาก

```python
import pandas as pd

## 7. ตัวอย่างภาพรวม: จากงาน Excel สู่ Python Workflow

ในส่วนนี้ เราจะดูตัวอย่างภาพรวมของ workflow แบบง่าย

สมมติว่าเรามีข้อมูลยอดขายดังนี้

| order_id | product | region | sales |
|---|---|---|---:|
| 1001 | Keyboard | Bangkok | 1200 |
| 1002 | Mouse | Chiang Mai | 450 |
| 1003 | Monitor | Bangkok | 5200 |
| 1004 | Keyboard | Khon Kaen | 1150 |
| 1005 | Mouse | Bangkok | 500 |

ใน Excel เราอาจทำสิ่งต่อไปนี้

1. เปิดไฟล์
2. ตรวจดูข้อมูล
3. Filter เฉพาะบาง region
4. สรุปยอดขายตามสินค้า
5. ทำ PivotTable
6. Save ผลลัพธ์

ใน Python เราสามารถเขียน workflow เดียวกันเป็นขั้นตอนที่ตรวจสอบและรันซ้ำได้

In [4]:
import pandas as pd

sales_data = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005],
    "product": ["Keyboard", "Mouse", "Monitor", "Keyboard", "Mouse"],
    "region": ["Bangkok", "Chiang Mai", "Bangkok", "Khon Kaen", "Bangkok"],
    "sales": [1200, 450, 5200, 1150, 500]
})

sales_data

   order_id   product      region  sales
0      1001  Keyboard     Bangkok   1200
1      1002     Mouse  Chiang Mai    450
2      1003   Monitor     Bangkok   5200
3      1004  Keyboard   Khon Kaen   1150
4      1005     Mouse     Bangkok    500

Code ด้านบนเป็นเพียงตัวอย่างภาพรวมเท่านั้น

ตอนนี้ยังไม่จำเป็นต้องเข้าใจรายละเอียดของทุกบรรทัด  
ให้สังเกตว่า Python สามารถแสดงข้อมูลในลักษณะตาราง คล้ายกับที่เราคุ้นเคยใน Excel ได้

## Inspect Data: ตรวจสอบข้อมูลเบื้องต้น

ใน Excel เราอาจดูจำนวนแถว จำนวนคอลัมน์ หรือเลื่อนดูข้อมูลด้วยสายตา

ใน Python เราสามารถใช้คำสั่งเพื่อตรวจสอบข้อมูลอย่างเป็นระบบ

In [5]:
sales_data.shape

(5, 4)

ผลลัพธ์จาก `.shape` แสดงจำนวนแถวและจำนวนคอลัมน์ของข้อมูล

รูปแบบผลลัพธ์คือ

```python
(number_of_rows, number_of_columns)
```

ตัวอย่างเช่น ถ้าได้ผลลัพธ์ (5, 4) หมายความว่า ข้อมูลมี 5 แถว และ 4 คอลัมน์

In [6]:
sales_data.head()

   order_id   product      region  sales
0      1001  Keyboard     Bangkok   1200
1      1002     Mouse  Chiang Mai    450
2      1003   Monitor     Bangkok   5200
3      1004  Keyboard   Khon Kaen   1150
4      1005     Mouse     Bangkok    500

คำสั่ง `.head()` ใช้ดูข้อมูลส่วนบนของตาราง

ในงานจริง ข้อมูลอาจมีหลายพันหรือหลายล้านแถว  
เราจึงมักดูข้อมูลบางส่วนก่อน แทนที่จะเปิดดูทั้งหมด

## Filter Data: กรองข้อมูล

ใน Excel เรามักใช้ Filter เพื่อเลือกเฉพาะข้อมูลที่สนใจ

เช่น ต้องการดูเฉพาะรายการขายใน Bangkok

ใน Python เราสามารถใช้คำสั่งเพื่อกรองข้อมูลตามเงื่อนไขได้

In [7]:
bangkok_sales = sales_data[sales_data["region"] == "Bangkok"]

bangkok_sales

   order_id   product   region  sales
0      1001  Keyboard  Bangkok   1200
2      1003   Monitor  Bangkok   5200
4      1005     Mouse  Bangkok    500

ตัวอย่างนี้แสดงแนวคิดว่า Python สามารถกรองข้อมูลแบบเดียวกับ Filter ใน Excel ได้

เรายังไม่จำเป็นต้องจำ syntax นี้ทั้งหมดในตอนนี้  
ในบทถัด ๆ ไป เราจะเรียนเรื่องการเลือกข้อมูลและการกรองข้อมูลอย่างเป็นระบบ

## Summarize Data: สรุปข้อมูล

ใน Excel เรามักใช้ PivotTable เพื่อสรุปยอดขายตามกลุ่ม

เช่น สรุปยอดขายตามสินค้า

ใน Python เราสามารถใช้แนวคิดเดียวกัน โดยใช้คำสั่งสำหรับสรุปข้อมูลเป็นกลุ่ม

In [8]:
sales_by_product = sales_data.groupby("product")["sales"].sum()

sales_by_product

product
Keyboard    2350
Monitor     5200
Mouse        950
Name: sales, dtype: int64

ผลลัพธ์ด้านบนคือยอดขายรวมตามสินค้า

แนวคิดนี้คล้ายกับการใช้ PivotTable ใน Excel

สิ่งสำคัญในตอนนี้คือให้เห็นว่า Python สามารถเปลี่ยนขั้นตอนที่เราเคยคลิกใน Excel ให้กลายเป็น workflow ที่รันซ้ำได้

## Export Result: ส่งออกผลลัพธ์

หลังจากวิเคราะห์ข้อมูลแล้ว เราอาจต้องส่งผลลัพธ์กลับไปเป็นไฟล์ Excel หรือ CSV

ตัวอย่างด้านล่างเป็นคำสั่งสำหรับส่งออกผลลัพธ์เป็นไฟล์ Excel

> หมายเหตุ: ในบางสภาพแวดล้อม อาจต้องติดตั้ง library เพิ่มเติมสำหรับการ export Excel  
> ในบทนี้ให้ดูเป็นภาพรวมก่อน

In [9]:
# ตัวอย่างคำสั่งสำหรับส่งออกผลลัพธ์เป็น Excel
# ยังไม่จำเป็นต้องรันในบทนี้

# sales_by_product.to_excel("sales_by_product.xlsx")

## 8. แนวคิดสำคัญของบทนี้

สิ่งที่อยากให้จำจากบทนี้คือ

Python สำหรับงานข้อมูลไม่ได้เริ่มจากการเขียนโปรแกรมที่ซับซ้อน  
แต่เริ่มจากการเปลี่ยนขั้นตอนการทำงานกับข้อมูลให้เป็นระบบ

จากเดิมที่เราอาจทำงานใน Excel ด้วยการ

- เปิดไฟล์
- คลิก filter
- ใส่สูตร
- สร้าง PivotTable
- copy ผลลัพธ์
- save เป็นไฟล์ใหม่

เราสามารถเปลี่ยนเป็น Python workflow ที่มีขั้นตอนชัดเจน เช่น

```text
load data → inspect data → clean data → transform data → analyze data → export result
```

เมื่อ workflow นี้ถูกเขียนเป็น code เราจะสามารถตรวจสอบ แก้ไข และรันซ้ำได้ง่ายขึ้น

# แบบฝึกหัดท้ายบท

แบบฝึกหัดในบทนี้เน้นให้ผู้เรียนเข้าใจแนวคิดการเปลี่ยนงาน Excel ให้เป็น workflow ด้วย Python

ยังไม่เน้นให้จำ syntax ทั้งหมด  
แต่ให้ฝึกคิดว่า “งานที่เคยทำด้วยการคลิกใน Excel” สามารถแปลงเป็น “ขั้นตอนที่เขียนเป็น code” ได้อย่างไร

## แบบฝึกหัดที่ 1: วิเคราะห์งาน Excel ที่ทำเป็นประจำ

ให้เลือกงาน Excel ที่คุณทำเป็นประจำ 1 งาน

ตัวอย่างงานที่อาจเลือกได้

- รวมไฟล์รายเดือน
- กรองข้อมูลเฉพาะบางเงื่อนไข
- คำนวณคอลัมน์ใหม่
- ลบข้อมูลที่ซ้ำ
- สร้าง PivotTable
- สรุปรายงานยอดขาย
- เตรียมข้อมูลก่อนส่งต่อให้ทีมอื่น

ให้ตอบคำถามต่อไปนี้ใน Markdown Cell ด้านล่าง

1. งาน Excel ที่เลือกคืออะไร
2. ข้อมูลต้นทางมาจากไหน
3. ขั้นตอนที่ทำใน Excel มีอะไรบ้าง
4. ผลลัพธ์สุดท้ายที่ต้องการคืออะไร
5. ขั้นตอนใดที่คิดว่าน่าจะให้ Python ช่วยทำแทนได้

## แบบฝึกหัดที่ 2: แปลงขั้นตอน Excel เป็น Python Workflow

จากสถานการณ์ต่อไปนี้

> คุณได้รับไฟล์ยอดขายรายเดือนจากทีมขาย  
> ต้องการกรองเฉพาะรายการขายใน Bangkok  
> จากนั้นสรุปยอดขายรวมตามสินค้า  
> และส่งออกผลลัพธ์เป็นไฟล์ใหม่

ใน Excel คุณอาจทำขั้นตอนดังนี้

1. เปิดไฟล์
2. ใช้ Filter เลือก region = Bangkok
3. สร้าง PivotTable เพื่อสรุปยอดขายตาม product
4. Copy ผลลัพธ์ไปยัง sheet ใหม่
5. Save เป็นไฟล์รายงาน

ให้เติม Python workflow ที่สอดคล้องกับขั้นตอนด้านบน

## แบบฝึกหัดที่ 3: อ่านโค้ด Python Workflow

พิจารณาโค้ดตัวอย่างต่อไปนี้

```python
import pandas as pd

sales_data = pd.DataFrame({
    "product": ["Keyboard", "Mouse", "Monitor", "Keyboard", "Mouse"],
    "region": ["Bangkok", "Chiang Mai", "Bangkok", "Khon Kaen", "Bangkok"],
    "sales": [1200, 450, 5200, 1150, 500]
})

bangkok_sales = sales_data[sales_data["region"] == "Bangkok"]

sales_by_product = bangkok_sales.groupby("product")["sales"].sum()

sales_by_product
```

ให้ตอบคำถามต่อไปนี้

1. โค้ดส่วนใดคือการเตรียมข้อมูล
2. โค้ดส่วนใดคล้ายกับการใช้ Filter ใน Excel
3. โค้ดส่วนใดคล้ายกับการใช้ PivotTable ใน Excel
4. ผลลัพธ์สุดท้ายน่าจะตอบคำถามทางธุรกิจเรื่องใด

## แบบฝึกหัดที่ 4: ทดลองปรับ workflow

ให้รันโค้ดตัวอย่างด้านล่าง แล้วทดลองปรับจากการกรอง `Bangkok` เป็น `Chiang Mai`

จากนั้นสังเกตว่าผลลัพธ์เปลี่ยนไปอย่างไร

In [10]:
import pandas as pd

sales_data = pd.DataFrame({
    "product": ["Keyboard", "Mouse", "Monitor", "Keyboard", "Mouse"],
    "region": ["Bangkok", "Chiang Mai", "Bangkok", "Khon Kaen", "Bangkok"],
    "sales": [1200, 450, 5200, 1150, 500]
})

selected_region = "Bangkok"

filtered_sales = sales_data[sales_data["region"] == selected_region]

sales_by_product = filtered_sales.groupby("product")["sales"].sum()

sales_by_product

product
Keyboard    1200
Monitor     5200
Mouse        500
Name: sales, dtype: int64

### คำถามหลังทดลอง

1. เมื่อเปลี่ยน `selected_region` จาก `"Bangkok"` เป็น `"Chiang Mai"` ผลลัพธ์เปลี่ยนอย่างไร
2. ถ้าทำงานนี้ใน Excel คุณต้องคลิกหรือเปลี่ยนอะไรบ้าง
3. ถ้าต้องทำรายงานแบบเดียวกันทุกเดือน Python workflow นี้ช่วยลดงานซ้ำได้อย่างไร

## แบบฝึกหัดที่ 5: ระบุบทบาทของ Python ในงานข้อมูล

จากตัวอย่างงานต่อไปนี้ ให้ระบุว่างานนั้นใกล้เคียงกับบทบาทใดมากที่สุด

เลือกจาก

- Data Analyst
- Data Engineer
- Data Scientist

| งาน | บทบาทที่ใกล้เคียงที่สุด |
|---|---|
| สรุปยอดขายรายเดือนตามภูมิภาค | |
| ดึงข้อมูลจาก API ทุกวันแล้วบันทึกลงฐานข้อมูล | |
| สร้างโมเดลทำนายลูกค้าที่มีโอกาสยกเลิกบริการ | |
| รวมไฟล์ CSV จำนวน 100 ไฟล์ให้เป็นไฟล์เดียว | |
| สร้างกราฟแสดงแนวโน้มยอดขาย | |
| ตรวจสอบความถูกต้องของข้อมูลก่อนเข้า data warehouse | |